### PR TITLE
Towards better mempool

### LINKED ISSUE #741: Bugs and issues in Mempool
Bugs:
1. `Pool::add_transaction` does not check whether the transaction is already known and erases all knowledge of whom this transaction is known to when it is re-added https://github.com/nearprotocol/nearcore/blob/e46a7c36d275ec77d552e345bb1ee30cfeb1dfac/core/mempool/src/lib.rs#L119 This in combination with how payload gossip is implemented will cause transactions to bounce between peers (even if they already know them) until the block is produced.

Incorrect assumptions:
1. `Pool::known_to` is updated when the payload is gossiped, but if payload never arrives due to network issues we would incorrectly assume that peer has that transaction. Payload gossip depends on this assumption;
2. `Pool::add_transaction` will reject transaction if the account from which it is send is created in the same block;

Dead code:
1. `Pool::ready_snapshots` on a first glance looks like it is used, but it is filled and immediately drained within the same function `process_payload_response`. Could've just used a temporary variable. See: https://github.com/nearprotocol/nearcore/blob/8b370c01b096978fac20a4a3cf264cfc2b97074c/node/coroutines/src/client_task.rs#L394 
2. `PayloadResponse::General` is never constructed, but there is code to process receiving it. Therefore `Pool::add_payload` is also unused;
3. `PayloadRequest::General` is never constructed, but there is code to process receiving it;
4. `Pool::pending_snapshots` is populated but never used;

Race conditions:
1. If peer A receives a snapshot request from peer B, but the corresponding block was just popped due to block production then A will mark B as potentially malicious.
see: https://github.com/nearprotocol/nearcore/blob/fc9b9228564d66b0584a83a605b2b25595cba52f/node/network/src/protocol.rs#L105

### PR DESCRIPTION
**Pull request by bowenwang1996**
- Improve payload gossiping. Before we send the entire payload to peers when snapshotting, which is suboptimal. Now only the hashes of of transactions and receipts are sent and if peers are not aware of some transactions/receipts, they actively fetch them.

- Clean up some dead code and fix some issues mentioned in #741 , mostly around payload gossiping/fetching, in mempool.

### CODE REVIEW

**Comment by nearmax** [comment]
Does it fix all issues of #741  or just some of them?

**Comment by bowenwang1996** [comment]
I think it fixes everything except all `known_to` is updated. @ilblackdragon suggested that we deal with that after testing the network with throttling.

File: core/mempool/src/lib.rs [hunk 1]
```diff
@@ -26,15 +29,16 @@ pub struct Pool {
     // transactions need to be grouped by account, and within each account,
     // ordered by nonce so that runtime will not ignore some of the transactions
     transactions: RwLock<HashMap<AccountId, BTreeMap<u64, SignedTransaction>>>,
+    // store the map that allows us to lookup transaction by hash
+    transaction_info: RwLock<HashMap<CryptoHash, (AccountId, u64)>>,
```
Comment (nearmax) [inline core/mempool/src/lib.rs]: Please expand comment to explain exactly what it maps to what: transaction hash -> (account id of the sender, nonce).

Comment (nearmax) [reply core/mempool/src/lib.rs]: Maybe create `type Nonce = u64`.

File: core/mempool/src/lib.rs [hunk 2]
```diff
@@ -142,18 +151,50 @@ impl Pool {
...
-    // TODO: Check snapshots on `pending_snapshots` which get unblocked and move them to `ready_snapshots`
-    pub fn add_payload(&self, payload: ChainPayload) -> Result<(), String> {
-        for transaction in payload.transactions {
-            self.add_transaction(transaction)?;
-        }
-        for receipt in payload.receipts {
-            self.add_receipt(receipt)?;
+    /// add requested transactions and receipts from peer. Move snapshot from pending_snapshots
+    /// to snapshots
+    pub fn add_missing_payload(
```
Comment (nearmax) [inline core/mempool/src/lib.rs]: Please explain arguments in the docstring.

File: core/mempool/src/lib.rs [hunk 3]
```diff
@@ -142,18 +151,50 @@ impl Pool {
...
     }
 
-    // TODO: Check snapshots on `pending_snapshots` which get unblocked and move them to `ready_snapshots`
-    pub fn add_payload(&self, payload: ChainPayload) -> Result<(), String> {
-        for transaction in payload.transactions {
-            self.add_transaction(transaction)?;
-        }
-        for receipt in payload.receipts {
-            self.add_receipt(receipt)?;
+    /// add requested transactions and receipts from peer. Move snapshot from pending_snapshots
```
Comment (nearmax) [inline core/mempool/src/lib.rs]: We should in general follow good punctuation and formatting in docstrings and error messages (see below). Start them with capital letters and when makes sense end with punctuation.

File: core/mempool/src/lib.rs [hunk 4]
```diff
@@ -26,15 +29,16 @@ pub struct Pool {
...
     trie: Arc<Trie>,
     state_viewer: TrieViewer,
-    snapshots: RwLock<HashSet<ChainPayload>>,
-    /// List of requested snapshots that can't be fetched yet.
-    pending_snapshots: RwLock<Vec<(AuthorityId, CryptoHash)>>,
     /// List of requested snapshots that are unblocked and can be confirmed.
-    ready_snapshots: RwLock<Vec<(AuthorityId, CryptoHash)>>,
+    snapshots: RwLock<HashSet<Snapshot>>,
+    /// List of requested snapshots that can't be fetched yet.
+    pending_snapshots: RwLock<HashSet<Snapshot>>,
```
Comment (nearmax) [inline core/mempool/src/lib.rs]: What is the logic behind having a `Snapshot` instead of its hash in `pending_snapshots`? To my understanding we either have an entire snapshot or we have none of its transactions.

File: core/mempool/src/lib.rs [hunk 5]
```diff
@@ -300,46 +395,95 @@ impl Pool {
...
+        };
+        let receipts: Vec<_> = {
+            let guard = self.receipts.read().expect(POISONED_LOCK_ERR);
+            request.receipts.into_iter().filter_map(|hash| guard.get(&hash).cloned()).collect()
+        };
+
+        MissingPayloadResponse { transactions, receipts, snapshot_hash: request.snapshot_hash }
     }
 
+    /// add snapshot sent by peer to pending_snapshots and request the missing
```
Comment (nearmax) [inline core/mempool/src/lib.rs]: The docstring says that it adds snapshot to `pending_snapshots`, but it only adds them to `pending_snaphots` when some transactions/receipts are missing, otherwise it adds it to `snapshots`. Please fix the docstring.

**Comment by nearmax** [comment]
Does it fix, the following?
> If peer A receives a snapshot request from peer B, but the corresponding block was just popped due to block production then A will mark B as potentially malicious.
see:

File: core/mempool/src/lib.rs (hunk 4 above)
Comment (bowenwang1996) [reply core/mempool/src/lib.rs]: The snapshot itself has to be stored somewhere.
