### PR TITLE
Show /status error if node doesn't receive block within expected time

### LINKED ISSUE #1078: /status endpoint shouldn't return success when node is stuck
E.g. node is out of free space and clearly has detected an error:

```
Other Error: IO error: No space left on deviceWhile appending to file: testdir/data/043974.log: No space left on de
vice } })
[2019-07-17T22:32:06Z ERROR near_client::client] Block production failed: Chain(Error { inner: 
```

but `/status` still returns success:
```
http http://34.94.13.241:3030/status

HTTP/1.1 200 OK
content-length: 331
content-type: application/json
date: Wed, 17 Jul 2019 22:34:32 GMT

{
    "chain_id": "test-chain-J1UGb",
    "rpc_addr": "0.0.0.0:3030",
    "sync_info": {
        "latest_block_hash": "FVWgbBM7QM3HZaEJCTpvBW9wpN8NTExjGRyF2kiFBZif",
        "latest_block_height": 9292465,
        "latest_block_time": "2019-07-17T19:36:46.817254235Z",
        "latest_state_root": "98AnTyWc2opjeeTDtsHZEgs6XvcfBotJrmTGi7FmSo8i",
        "syncing": false
    },
    "validators": [
        "test.near"
    ]
}
```

### PR DESCRIPTION
**Pull request by ilblackdragon**
Fixes #1078

### CODE REVIEW

File: chain/jsonrpc/tests/rpc_query.rs [hunk 1]
```diff
@@ -155,6 +156,32 @@ fn test_status() {
...
+        WaitOrTimeout::new(
+            Box::new(move |_| {
+                actix::spawn(client.status().then(|res| {
+                    if res.is_err() {
+                        System::current().stop();
+                    }
+                    future::result(Ok(()))
+                }));
+            }),
+            100,
```
Comment (vgrichina) [inline chain/jsonrpc/tests/rpc_query.rs]: better use named constants instead of magic numbers?

Comment (ilblackdragon) [reply chain/jsonrpc/tests/rpc_query.rs]: this is in tests.
also in clion we actually see what are those numbers mean

Comment (vgrichina) [reply chain/jsonrpc/tests/rpc_query.rs]: in GitHub we don't and that's where most of code reading happens
