### PR TITLE
fix(rpc): better error handling for transaction submissions

### LINKED ISSUE #2867: Improve transaction status and submission RPCs
There are two flows that can be improved by changing few things:
 - `tx-status` should optionally take transaction bytes. This would allow to not only check for the status of transaction hash inclusion, but also identify if transaction already became invalid. E.g. `tx-status` can return 3 statuses: `Success/Failure` (transaction was included but), `InvalidTx` (transaction is invalid as of this point), `Unknown`.

 - `broadcast_tx_commit` should:
   - check if transaction is valid, if not - return `InvalidTx`.
   - submit tx for execution
   - use `tx-status` on this transaction for one of the 3 statuses.
Ths will still have Timeout error in case of real timeout because validators are slow, but will allow to resend transaction via the same end point and get `InvalidTx` or `Success` if for example this transaction was included. Same as if you query `tx-status` of this transaction.

Internally, it's a small change for `tx_status_fetch` can take either hash or transaction itself. And ping TxStatus ViewClient with that. And it can then `InvalidTx` return if transaction becomes invalid during polling.

Previous discussion was here: https://github.com/near/near-api-js/issues/344

### PR DESCRIPTION
**Pull request by bowenwang1996**
Changes how `broadcast_tx_commit` and `tx` rpc work to allow easier handling of transaction submissions. More specifically,
* `broadcast_tx_commit` now checks whether tx is still valid while polling its result.
* transaction status query can also take transaction itself and will return an error if the transaction is no longer valid.

Fixes #2867

### CODE REVIEW

File: chain/jsonrpc/src/lib.rs [hunk 1]
```diff
@@ -261,25 +265,47 @@ impl JsonRpcHandler {
...
                     Ok(Err(err)) => break Err(err),
                     Err(_) => break Err(TxStatusError::InternalError),
                 }
                 let _ = delay_for(self.polling_config.polling_interval).await;
             }
         })
         .await
-        .map_err(|_| TxStatusError::TimeoutError)?
+        .map_err(|_| {
+            if let Some(e) = nonce_error {
```
Comment (bowenwang1996) [inline chain/jsonrpc/src/lib.rs:294]: @ilblackdragon I am not sure what's the best way to handle this. We cannot return it inside the loop since we poll quote frequently and the state will have been updated before the transaction is fully complete.

File: chain/jsonrpc/src/lib.rs [hunk 2]
```diff
@@ -250,9 +250,12 @@ impl JsonRpcHandler {
 
     async fn tx_status_fetch(
         &self,
-        tx_hash: CryptoHash,
-        account_id: AccountId,
+        tx_info: TransactionInfo,
```
Comment (frol) [inline chain/jsonrpc/src/lib.rs:253]: Wouldn't it make sense to have `tx_info` a borrowed TransactionInfo instead of owned? (This will avoid unnecessary clones on the call sight)

File: chain/jsonrpc/src/lib.rs [hunk 3]
```diff
@@ -499,12 +508,21 @@ impl JsonRpcHandler {
...
+                if !is_valid_account_id(&account_id) {
+                    return Err(RpcError::invalid_params(format!(
+                        "Invalid account id: {}",
+                        account_id
+                    )));
+                }
+                TransactionInfo::TransactionId { hash, account_id }
+            } else {
+                let tx = parse_tx(params)?;
+                TransactionInfo::Transaction(tx)
```
Comment (frol) [inline chain/jsonrpc/src/lib.rs:522]: :+1:

File: chain/jsonrpc/src/lib.rs (hunk 2 above)
Comment (bowenwang1996) [reply chain/jsonrpc/src/lib.rs:253]: good point

Comment (bowenwang1996) [reply chain/jsonrpc/src/lib.rs:253]: actually it seems that the cloning at call sight cannot be avoided

File: chain/jsonrpc/src/lib.rs [hunk 4]
```diff
@@ -262,6 +265,18 @@ impl JsonRpcHandler {
...
                     Ok(Ok(None)) => {}
+                    Ok(Err(TxStatusError::MissingTransaction(_))) => {
+                        if let TransactionInfo::Transaction(tx) = &tx_info {
+                            if let Ok(NetworkClientResponses::InvalidTx(e)) =
+                                self.send_tx(tx.clone(), true).await
+                            {
+                                break Err(TxStatusError::InvalidTx(e));
+                            }
+                        }
+                        if let Ok(Err(e)) = tx_status_result {
```
Comment (SkidanovAlex) [inline chain/jsonrpc/src/lib.rs:276]: We are in the `match` arm that corresponds to `tx_status_result = Ok(Err(TxStatusError::MissingTransaction(_)))`. `tx_status_result` seems to be a local variable that doesn't change within the arm, so I'd expect this condition to be always `true`?

**Comment by vgrichina** [comment]
@bowenwang1996 will `broadcast_tx_commit` return success if transaction is already submitted?

**Comment by bowenwang1996** [comment]
@vgrichina it is now, except that if you submit a transaction that has been garbage collected it will be considered invalid instead of returning you the status of the transaction.

**Comment by vgrichina** [comment]
@bowenwang1996 is it possible to determine whether it's been garbage collected vs just invalid?

**Comment by bowenwang1996** [comment]
@vgrichina no. Is it important?
