### PR TITLE
Alphanet entry point. Chain spec generator. Alphanet robustness integration test. Keygen fix

### LINKED ISSUE #662: Alphanet nodes do not produce blocks when ran as separate programs
To reproduce:
Follow the instructions to start 4 nodes of alpanet net, see: #658

Observe that the nodes connect, but they do not produce blocks.

### PR DESCRIPTION
**Pull request by nearmax**
* Adds integration test for checking for how long multi-node alphanet can run and accept transactions before it crashes;
* Added entry point for running alphanet nodes;
* Added test chain spec generator for starting multiple alphanet nodes.
* Fixes #662

Example of starting 4 alphanet nodes:
```
rm -rf test1 test2 test3 test4
cargo run --package alphanet --bin generate_test_spec
cargo run --package keystore -- keygen --test-seed near.0 -p test1/storage/keystore/
cargo run --package keystore -- keygen --test-seed near.1 -p test2/storage/keystore/
cargo run --package keystore -- keygen --test-seed near.2 -p test3/storage/keystore/
cargo run --package keystore -- keygen --test-seed near.3 -p test4/storage/keystore/
```
In separate terminals:
```
cargo run -- --addr 127.0.0.1:3000 --rpc_port 3030 --base-path=test1 --test-network-key-seed 1 --chain-spec-file ./node/configs/res/alphanet_chain.json -a near.0 -k 82M8LNM7AzJHhHKn6hymVW1jBzSwFukHp1dycVcU7MD
cargo run -- --addr 127.0.0.1:3001 --rpc_port 3031 --base-path=test2 --test-network-key-seed 2 --chain-spec-file ./node/configs/res/alphanet_chain.json -a near.1 -k CTVkQMjLyr4QzoXrTDVzfCUp95sCJPwLJZ34JTiekxMV --boot-nodes 127.0.0.1:3000/GuMriipt4yUXfkZL2z3zLPbYaozkZG6zjV6vg4QruEvY
cargo run -- --addr 127.0.0.1:3002 --rpc_port 3032 --base-path=test3 --test-network-key-seed 3 --chain-spec-file ./node/configs/res/alphanet_chain.json -a near.2 -k EJ1DMa6s2ngC5GtZb3Z2DZzat2xFZ34j15VLY37dcdXX --boot-nodes 127.0.0.1:3000/GuMriipt4yUXfkZL2z3zLPbYaozkZG6zjV6vg4QruEvY
cargo run -- --addr 127.0.0.1:3003 --rpc_port 3033 --base-path=test4 --test-network-key-seed 4 --chain-spec-file ./node/configs/res/alphanet_chain.json -a near.3 -k 3DToePHssYc75SsxZgzgVLwXE8XQXKjdpdL7CT7D34UE --boot-nodes 127.0.0.1:3000/GuMriipt4yUXfkZL2z3zLPbYaozkZG6zjV6vg4QruEvY
```
To submit a transaction:
```
cd pynear
python setup.py develop
pynear send_money -u http://127.0.0.1:3030/ -o near.0 -d ../keystore -k 82M8LNM7AzJHhHKn6hymVW1jBzSwFukHp1dycVcU7MD -r near.1 -a 1
```

### CODE REVIEW

File: node/alphanet/src/lib.rs [hunk 1]
```diff
@@ -147,16 +142,23 @@ mod tests {
         );
         let alice_signer = alice.signer();
         let bob_signer = bob.signer();
-        println!("Alice pk={:?}, bls pk={:?}", alice_signer.public_key.to_readable(), alice_signer.bls_public_key.to_readable());
-        println!("Bob pk={:?}, bls pk={:?}", bob_signer.public_key.to_readable(), bob_signer.bls_public_key.to_readable());
+        println!(
```
Comment (ilblackdragon) [inline node/alphanet/src/lib.rs]: we can remove this

File: node/alphanet/src/testing_utils.rs [hunk 2]
```diff
@@ -122,3 +128,29 @@ where
         }
     }
 }
+
+/// Generates chainspec for running multiple nodes.
+pub fn generate_test_chain_spec(account_names: &Vec<String>, balance: u64) -> ChainSpec {
```
Comment (ilblackdragon) [inline node/alphanet/src/testing_utils.rs]: remove then configure_chain_spec (idae was to add configuration there).
Also add option to specify number of authorities out of this account_names

Comment (nearmax) [reply node/alphanet/src/testing_utils.rs]: I think there is still usage of `configure_chain_spec`, because `generate_test_chain_spec` does not strictly supersede it. Also for the sake of unblocking everyone I'll just go ahead and merge this.

>Also add option to specify number of authorities out of this account_names
Not sure I understand what it means.

File: node/alphanet/src/lib.rs (hunk 1 above)
Comment (nearmax) [reply node/alphanet/src/lib.rs]: Done

File: node/alphanet/src/testing_utils.rs (hunk 2 above)
Comment (ilblackdragon) [reply node/alphanet/src/testing_utils.rs]: You currently making all the accounts authorities
Instead it should be k out of n accounts are authorities, the rest are just regular accounts. E.g. k should be a parameter.
