### PR TITLE
fix(rpc): better error handling for transaction submission

### LINKED ISSUE #2039: Invalid transactions dropped from the pool don't have the error
When a frontend send 2 transactions with the same nonce, both of them are accepted by the node and added to the pool. Then when a block is being produced, one of the transactions become invalid and is dropped from the pool. There are no way to notify the front-end about the results of the transaction or what error caused the transaction to being dropped.

### PR DESCRIPTION
**Pull request by bowenwang1996**
Add two experimental rpcs:
* `EXPERIMENTAL_broadcast_tx_sync` that sends the transaction and waits for its validity to be checked before returning, but doesn't wait for the transaction to be processed.
* `EXPERIMENTAL_check_tx` that checks whether a transaction is still valid. For the rpc to work, the node that the request is sent to must track the shard of the sender, otherwise it will return `Cannot determine whether the transaction is valid`.

Fixes #2039.

Test plan
---------
* `test_check_invalid_tx` that does a sanity check on `EXPERIMENTAL_check_tx`.
* pytest `rpc_tx_submission` that checks transactions can be submitted in all three ways and work well. Also check that invalid transactions can be caught by `EXPERIMENTAL_check_tx`.

### CODE REVIEW

File: chain/jsonrpc/src/lib.rs [hunk 1]
```diff
@@ -283,16 +287,68 @@ impl JsonRpcHandler {
...
+                }
+            }
+            NetworkClientResponses::InvalidTx(err) => {
+                Err(RpcError::server_error(Some(ServerError::TxExecutionError(err.into()))))
+            }
+            NetworkClientResponses::NoResponse => {
+                // this is only possible if something went wrong with the node internally.
+                Err(RpcError::server_error(Some(ServerError::InternalError)))
+            }
+            _ => unreachable!(),
```
Comment (frol) [inline chain/jsonrpc/src/lib.rs:343]: You suggested previously that we should not crash the node if some RPC fails. I guess it is a good idea to just respond with InternalError here.

File: chain/jsonrpc/src/lib.rs [hunk 2]
```diff
@@ -283,16 +287,68 @@ impl JsonRpcHandler {
...
+                    Ok(Value::String(tx_hash))
+                }
+            }
+            NetworkClientResponses::RequestRouted => {
+                if check_only {
+                    Ok(Value::String("Node doesn't track this shard. Cannot determine whether the transaction is valid".to_string()))
+                } else {
+                    Ok(Value::String("Transaction is routed".to_string()))
+                }
+            }
```
Comment (frol) [inline chain/jsonrpc/src/lib.rs:335]: 1. The return value should be an object (JSON key-value). Consider the RPC client perspective, you will need to guess if the returned string an error or a transaction hash; that is going to feel unreliable. We should always return an object (a structure / JSON key-value) instead of a plain string, this way it is also going to help us to extend the API response without breaking changes in the future (if needed).
2. This whole `check_only` looks a bit ugly to me, but I don't have better suggestions at the moment.

File: chain/client/src/client.rs [hunk 3]
```diff
@@ -1193,6 +1197,9 @@ impl Client {
                     Ok(NetworkClientResponses::NoResponse)
                 }
             }
+        } else if check_only {
+            // this response indicates that the node doesn't track the shard
+            Ok(NetworkClientResponses::RequestRouted)
```
Comment (SkidanovAlex) [inline chain/client/src/client.rs:1202]: Can we have a separate response for this?

File: chain/jsonrpc/src/lib.rs [hunk 4]
```diff
@@ -283,16 +287,68 @@ impl JsonRpcHandler {
...
+        self.send_or_check_tx(params, true).await
+    }
+
+    async fn send_or_check_tx(
+        &self,
+        params: Option<Value>,
+        check_only: bool,
+    ) -> Result<Value, RpcError> {
+        let tx = parse_tx(params)?;
+        let tx_hash = (&tx.get_hash()).to_base();
```
Comment (frol) [inline chain/jsonrpc/src/lib.rs:320]: We migrate from the positional arguments to the RPC API. Define `RpcTransactionStatusCheckRequest` in `primitives/rpc.rs` and parse it here as:

```rust
let params: RpcTransactionStatusCheckRequest = parse_params(params)?;
```

The new style API is already implemented for `query`, `EXPERIMENTAL_*` methods, so you can take inspiration from there.

File: chain/jsonrpc/src/lib.rs (hunk 2 above)
Comment (bowenwang1996) [reply chain/jsonrpc/src/lib.rs:335]: >  you will need to guess if the returned string an error or a transaction hash; that is going to feel unreliable

You don't need to guess. They are two different rpcs

Comment (bowenwang1996) [reply chain/jsonrpc/src/lib.rs:335]: > We should always return an object (a structure / JSON key-value) instead of a plain string

What do you suggest here?

Comment (frol) [reply chain/jsonrpc/src/lib.rs:335]: > They are two different rpcs

I was referring to the fact that the RPC can either return `"some-tx-hash"` or `"Node does't track this..."`, so from the type perspective they are both strings. To distinguish them you need to either hardcode the error text messages or try to parse that string as hash (check base58 validity).

Comment (frol) [reply chain/jsonrpc/src/lib.rs:335]: > They are two different rpcs

I was referring to the fact that the RPC can either return `"some-tx-hash"` or `"Node does't track this..."`, so from the type perspective they are both strings. To distinguish them you need to either hardcode the error text messages or try to parse that string as hash (check base58 validity).

Currently, the response is:

```js
{
  "jsonrpc": "2.0",
  "result": "some-tx-hash"
}
```

or 

```js
{
  "jsonrpc": "2.0",
  "result": "Node doesn't track ..."
}
```

This is really hard to work with, and also it is not extendible without a breaking change.

I suggest to have:

```js
{
  "jsonrpc": "2.0",
  "result": {
    "transaction_hash": "some-tx-hash",
  }
}
```

and

```js
{
  "jsonrpc": "2.0",
  "error": {
    "code": ...
    "data": "Node doesn't track...",
    "message": "Server error"
  }
}
```

Comment (frol) [reply chain/jsonrpc/src/lib.rs:335]: Well, I just noticed that the OK response is null value. Can we provide anything helpful in the response? (e.g. block height, block hash, chunk hash the transaction landed, if that is trivial to get)

**Comment by bowenwang1996** [comment]
@SkidanovAlex the naming follows tendermint API https://docs.tendermint.com/master/rpc/#/Tx/broadcast_tx_sync. It waits until the transaction gets into mempool before returning.

File: chain/jsonrpc/src/lib.rs (hunk 4 above)
Comment (bowenwang1996) [reply chain/jsonrpc/src/lib.rs:320]: Well transaction is special because it is serialized in borsh. That is why we have `parse_tx`. I can wrap it in an object but I don't see the point of doing so, as you still have to use a special routing to deserialize it.

File: chain/client/src/test_utils.rs [hunk 5]
```diff
@@ -920,7 +920,7 @@ impl TestEnv {
             100,
             self.clients[id].chain.head().unwrap().last_block_hash,
         );
-        self.clients[id].process_tx(tx, false)
+        self.clients[id].process_tx(tx, false, false)
```
[the remark this answers is not in the document]
Comment (bowenwang1996) [reply chain/client/src/test_utils.rs:923]: It's mostly used for internal stuff so I guess it's fine.

File: chain/jsonrpc/src/lib.rs (hunk 2 above)
Comment (bowenwang1996) [reply chain/jsonrpc/src/lib.rs]: That is for checking the transaction. If you just want to check whether the transaction is valid I don't know what else you want to include in the response.

**Comment by frol** [comment]
We seem to miss a structured error handling here (as per similar discussion https://github.com/nearprotocol/nearcore/issues/2518#issuecomment-619452654) /cc @fckt

**Comment by bowenwang1996** [comment]
@frol I created a separate issue #2536 for this.

File: chain/jsonrpc/src/lib.rs [hunk 6]
```diff
@@ -283,16 +288,73 @@ impl JsonRpcHandler {
...
+                } else {
+                    jsonify(Ok(Ok(RpcBroadcastTxSyncResponse {
+                        transaction_hash: tx_hash,
+                        is_routed: false,
+                    })))
+                }
+            }
+            NetworkClientResponses::RequestRouted => {
+                if check_only {
+                    Err(RpcError::server_error(Some("Node doesn't track this shard. Cannot determine whether the transaction is valid".to_string())))
```
Comment (fckt) [inline chain/jsonrpc/src/lib.rs:335]: @bowenwang1996  
What does this error mean for user?

Comment (frol) [reply chain/jsonrpc/src/lib.rs:335]: @fckt Good catch.

We should help users to understand that they are expected to reach another node that tracks the shard.

Comment (bowenwang1996) [reply chain/jsonrpc/src/lib.rs:335]: @frol how to better phrase it? Should we include something like "try another node"?

Comment (fckt) [reply chain/jsonrpc/src/lib.rs:335]: I was thinking the node must be found automatically? (maybe the request should contain a sender_id?) How to use this method?
