### PR TITLE
fix: Filter trie keys for state changes

### LINKED ISSUE #2563: StateChanges can break if there is more than one shard
#1910 introduces StateChanges, with the idea that a node should store all changes to the state.

Each shard has its own state transition and set of changes, and a node can track only a subset of all shards. The way the current implementation works is it flattens the sets of changes for all known shards, and writes them to `ColStateChanges` using the following code:
```
            let storage_key = KeyForStateChanges::new_from_trie_key(
                &self.block_hash,
                &change_with_trie_key.trie_key,
            );
            store_update.set(
                DBCol::ColStateChanges,
                storage_key.as_ref(),
                &change_with_trie_key.try_to_vec()?,
            );
```
This can cause a conflict of storage keys as long as `TrieKey` for changes in shards can be the same, which is a possibility:
```
pub enum TrieKey {
...
    /// Used to store indices of the delayed receipts queue (`node-runtime::DelayedReceiptIndices`).
    /// NOTE: It is a singleton per shard.
    DelayedReceiptIndices,
    /// Used to store a delayed receipt `primitives::receipt::Receipt` for a given index `u64`
    /// in a delayed receipt queue. The queue is unique per shard.
    DelayedReceipt { index: u64 },
...
```

@nearmax @frol @evgenykuzyakov

### PR DESCRIPTION
**Pull request by evgenykuzyakov**
Fixes #2563 

# Test plan:
- RPC sanity test
- CI

### CODE REVIEW

File: core/store/src/trie/mod.rs [hunk 1]
```diff
@@ -594,6 +594,16 @@ impl WrappedTrieChanges {
...
+            // Filtering trie keys.
+            // NOTE: If the trie key is not one of the account specific, it may cause key conflict
+            // when the node tracks multiple shards. See #2563.
+            match &change_with_trie_key.trie_key {
+                TrieKey::Account { .. }
+                | TrieKey::ContractCode { .. }
+                | TrieKey::AccessKey { .. }
+                | TrieKey::ContractData { .. } => (),
+                _ => continue,
+            };
```
Comment (bowenwang1996) [inline core/store/src/trie/mod.rs:606]: I am confused. Why are these keys skipped?

Comment (mikhailOK) [reply core/store/src/trie/mod.rs:606]: If I understood correctly, by design of `StateChanges` - rather than a transaction log that can be an alternative to applying blocks, it's a user-facing log for RPC purposes only

File: core/store/src/trie/mod.rs [hunk 2]
```diff
@@ -594,6 +594,16 @@ impl WrappedTrieChanges {
...
                 "NotWritableToDisk changes must never be finalized."
             );
+            // Filtering trie keys.
+            // NOTE: If the trie key is not one of the account specific, it may cause key conflict
+            // when the node tracks multiple shards. See #2563.
+            match &change_with_trie_key.trie_key {
+                TrieKey::Account { .. }
+                | TrieKey::ContractCode { .. }
+                | TrieKey::AccessKey { .. }
+                | TrieKey::ContractData { .. } => (),
```
Comment (frol) [inline core/store/src/trie/mod.rs:604]: `{}` looks more appropriate.

File: core/store/src/trie/mod.rs (hunk 1 above)
Comment (frol) [reply core/store/src/trie/mod.rs:606]: @mikhailOK that is correct. `StateChanges` are recorded specifically for RPC needs, and we only expose these types of changes.

Comment (bowenwang1996) [reply core/store/src/trie/mod.rs:606]: I see
