### PR TITLE
fix(chain): fix garbage collection stop height

### LINKED ISSUE #2269: GC: super long epochs should be processed properly
According to @mikhailOK https://github.com/nearprotocol/nearcore/pull/2084#discussion_r390512876

### PR DESCRIPTION
**Pull request by bowenwang1996**
Currently garbage collection uses purely height to determine the end height of GC, which is problematic when there is an epoch with a lot of skipped heights: blocks in the current epoch can be garbage collected and that will result in no node being able to sync into the network. This PR addresses this issue by not allowing gc to go over the start height of the epoch that is five epochs from the current one.

Test plan
---------
* Make sure existing gc unit tests work.
* Add `test_garbage_collection`, which tests that garbage collection works under normal circumstances with real runtime.
* Pytest `garbage_collection.py` which tests the scenario that if there are a lot of skipped heights in an epoch (more than 5 * epoch length), a node should still be able to sync.

### CODE REVIEW

**Comment by SkidanovAlex** [comment]
Can you add a test that
1. Has five nodes, two offline
2. Waits until an Epoch is long enough
3. Starts one node, waits until it recovers
4. Starts the second node.

I'd expect it to fail, since bringing the first node will switch the Epoch, and trigger the GC

**Comment by bowenwang1996** [comment]
> Can you add a test that
> 
> 1. Has five nodes, two offline
> 2. Waits until an Epoch is long enough
> 3. Starts one node, waits until it recovers
> 4. Starts the second node.
> 
> I'd expect it to fail, since bringing the first node will switch the Epoch, and trigger the GC

Why would it fail? Since the epoch is switched the first node should state sync into the new epoch. Is that not how it works?

File: chain/chain/src/store.rs [hunk 1]
```diff
@@ -2528,18 +2527,11 @@ mod tests {
         assert!(chain.clear_old_data().is_ok());
 
         assert!(chain.get_block(&blocks[0].hash()).is_ok());
+
+        // epoch didn't change so no data is garbage collected.
```
Comment (SkidanovAlex) [inline chain/chain/src/store.rs]: Seems like this test is not testing anything now?

The correct fix of the test is probably to introduce an epoch switch.

Comment (bowenwang1996) [reply chain/chain/src/store.rs]: It tests that when epoch doesn't switch the blocks are not garbage collected. I had a separate test `test_garbage_collection` that tests the scenario you mentioned.

**Comment by bowenwang1996** [comment]
> We state sync from the epoch of the current_height - 50 or something like that, so after the epoch switch and immediate GC the new node cna't really state sync
> It probably passes because it eventually retries after enough heights? Which is probably fine.

I am confused. We run state sync when we detect that header head and block head are in different epochs. https://github.com/nearprotocol/nearcore/blob/5d61fe5de89157381c6d2fe4fba5f9a8eec2a0ac/chain/chain/src/chain.rs#L757

File: chain/chain/src/store.rs (hunk 1 above)
Comment (Kouprin) [reply chain/chain/src/store.rs]: @bowenwang1996 could you add epoch switching explicitly and add a bool parameter which says should epoch switching happen or not? Then you can remove separate test `test_garbage_collection`.

**Comment by Kouprin** [comment]
This solution doesn't leave us a gap to store states for several epochs. In addition to possible malicious actors, forks and unpredictable number of blocks per epoch, it may lead us to impossibility of restoring the state.
Let's say, there was a long epoch E. Block A is the last block of epoch E, then there is a fork from A: A->B and A->C. 
Node 1 gets block B and GCs epoch E.
Node 2 gets block C and GCs epoch E.
Node 3 appears and tries to State Sync. It gets a chain started with B. Then C becomes canonical. Node 3 will never restore.

File: chain/chain/src/store.rs (hunk 1 above)
Comment (bowenwang1996) [reply chain/chain/src/store.rs]: I cannot set the epoch length in this test easily and also this test uses `KeyValueRuntime`. I prefer to have a separate test that uses the real runtime.

Comment (Kouprin) [reply chain/chain/src/store.rs]: Got it.
Does it mean that this change may affect GC fork test infrastructure negatively (gc_fork_common) in https://github.com/nearprotocol/nearcore/pull/2084? `gc_fork_common` uses `KeyValueRuntime` without real epoch switching.

Comment (bowenwang1996) [reply chain/chain/src/store.rs]: Yes. I think we need some modification to `get_gc_head_height` in `KeyValueRuntime`.

File: chain/chain/src/test_utils.rs [hunk 2]
```diff
@@ -831,6 +831,10 @@ impl RuntimeAdapter for KeyValueRuntime {
         }
     }
 
+    fn get_gc_head_height(&self, _block_hash: &CryptoHash) -> Result<BlockHeight, Error> {
+        Ok(0)
```
Comment (Kouprin) [inline chain/chain/src/test_utils.rs]: `get_gc_head_height` should be turned on for KV runtime
To do that, use the formula `block height - NUM_EPOCHS_TO_KEEP_STORE_DATA * epoch length`

File: chain/chain/src/store.rs (hunk 1 above)
Comment (Kouprin) [reply chain/chain/src/store.rs]: Okay, please do.

File: chain/chain/src/store.rs [hunk 3]
```diff
@@ -2528,18 +2527,11 @@ mod tests {
...
-                assert!(chain
-                    .mut_store()
-                    .get_all_block_hashes_by_height(i as BlockHeight)
-                    .is_err());
-            } else {
-                assert!(chain.get_block(&blocks[i].hash()).is_ok());
-                assert!(chain.mut_store().get_all_block_hashes_by_height(i as BlockHeight).is_ok());
-            }
+            assert!(chain.get_block(&blocks[i].hash()).is_ok());
+            assert!(chain.mut_store().get_all_block_hashes_by_height(i as BlockHeight).is_ok());
```
Comment (Kouprin) [inline chain/chain/src/store.rs]: Revert this. Let the test checks GC sanity in KV runtime.

File: chain/client/tests/process_blocks.rs [hunk 4]
```diff
@@ -825,3 +828,29 @@ fn test_minimum_gas_price() {
     let block = env.clients[0].chain.get_block_by_height(100).unwrap();
     assert!(block.header.inner_rest.gas_price >= min_gas_price);
 }
+
+#[test]
+fn test_garbage_collection() {
```
Comment (Kouprin) [inline chain/client/tests/process_blocks.rs]: 1. Modify the test to accept `epoch_length` as a parameter.
2. At the end of the test please assert that all blocks in range `0..should_be_GCd` are deleted and all blocks in range `should_be_GCd..head` are exist.
3. Run the test with different `epoch_length` parameter.

File: chain/client/tests/process_blocks.rs [hunk 5]
```diff
@@ -825,3 +828,29 @@ fn test_minimum_gas_price() {
...
+    genesis.config.epoch_length = epoch_length;
+    let runtimes: Vec<Arc<dyn RuntimeAdapter>> = vec![Arc::new(near::NightshadeRuntime::new(
+        Path::new("."),
+        store,
+        Arc::new(genesis),
+        vec![],
+        vec![],
+    ))];
+    let mut chain_genesis = ChainGenesis::test();
+    chain_genesis.epoch_length = epoch_length;
```
Comment (Kouprin) [inline chain/client/tests/process_blocks.rs]: I'm not sure how is it possible, but can we imitate not finalizing epoch in TestEnv easily? If yes, please add one more parameter to the test `is_finalizing` to make sure we're not GCing in Nightshade non-finalized epochs.

File: chain/chain/src/store.rs (hunk 1 above)
Comment (SkidanovAlex) [reply chain/chain/src/store.rs]: Also please rename the test so that it's more clear what it's testing

File: chain/client/tests/process_blocks.rs (hunk 5 above)
Comment (bowenwang1996) [reply chain/client/tests/process_blocks.rs]: it's inconvenient to combine the two so I made a separate test for this

File: near/src/runtime.rs [hunk 6]
```diff
@@ -793,6 +794,27 @@ impl RuntimeAdapter for NightshadeRuntime {
...
+        // an epoch must have a first block.
+        let epoch_first_block = epoch_manager.get_block_info(block_hash)?.epoch_first_block;
+        let epoch_first_block_info = epoch_manager.get_block_info(&epoch_first_block)?;
+        // maintain pointers to avoid cloning.
+        let mut last_block_in_prev_epoch = epoch_first_block_info.prev_hash;
+        let mut epoch_start_height = epoch_first_block_info.height;
+        for _ in 0..NUM_EPOCHS_TO_KEEP_STORE_DATA - 1 {
+            let epoch_first_block = match epoch_manager.get_block_info(&last_block_in_prev_epoch) {
+                Ok(block_info) => block_info.epoch_first_block,
+                Err(EpochError::MissingBlock(_)) => return Ok(epoch_start_height),
```
Comment (SkidanovAlex) [inline near/src/runtime.rs]: shall this return the tail instead?

Comment (bowenwang1996) [reply near/src/runtime.rs]: What do you mean by tail?

Comment (bowenwang1996) [reply near/src/runtime.rs]: It's the same things I think. Every epoch must have a last block so the only way this can happen is that we are at genesis block, which means this would return genesis block height.
