### PR TITLE
Optional account

### LINKED ISSUE #282: Fix loading account / keys
Currently, keystore is separate from account id when starting node. Account id also has a default.

### LINKED ISSUE #757: Run node without keys if they are not provided
Currently, we either create a new key pair or crash if keys are not provided.
We should allow running node without any keys (e.g. just sync with the network) or if key file is provided - use that.
Let's make it explicit.
Also while we on it, let's move keystore file into $BASE_PATH instead of $BASE_PATH/storage.

### PR DESCRIPTION
**Pull request by ilblackdragon**
Fixes #757
Fixes #282

Currently we have signer, pool and consensus within client, which is probably not the best container.
Made things optional for now, just to keep architecture, but probably the "validator" functionality should be moved out.

Made `Signable` trait that converts object into bytes that can be sign. Updated signers to work based on that (limitations of Rust to do that way)

### CODE REVIEW

**Comment by ilblackdragon** [comment]
@bowenwang1996 no exactly, because for example Block &[u8] I would expect serialized block, versus `Signable` is actually hash of that block.

**Comment by nearmax** [comment]
> Currently we have signer, pool and consensus within client, which is probably not the best container.

We were just discussing with @mikhailOK that we need to extract sub-structs from the client and client task, e.g. something that encapsulates signer in a larger scope. Validator is an option.

File: node/shard/src/lib.rs [hunk 1]
```diff
@@ -78,15 +80,11 @@ impl ShardClient {
...
-        Self { 
-            chain,
-            trie,
-            storage,
-            runtime,
-            trie_viewer,
-            pool
-        }
+        let pool = match signer {
+            Some(signer) => Some(Arc::new(Pool::new(signer, storage.clone(), trie.clone()))),
```
Comment (nearmax) [inline node/shard/src/lib.rs]: This is an implicit logic. We determine whether the pool should be created by checking whether signer is created. Let's make it more explicit by adding a docstring to new that explains that if signer is optional it becomes a non-validating shard client which does not have a pool.

File: node/coroutines/src/client_task.rs [hunk 2]
```diff
@@ -690,7 +697,9 @@ impl ClientTask {
         let (owner_uid, uid_to_authority_map) = self.client.get_uid_to_authority_map(index);
 
         if owner_uid.is_none() {
-            self.client.shard_client.pool.reset(None, None);
+            if let Some(pool) = &self.client.shard_client.pool {
```
Comment (nearmax) [inline node/coroutines/src/client_task.rs]: To my understanding only two scenarios are possible:
1) Validator: Pool and signer are not None, and consensus is running;
2) Non-validator; Pool and signer are None, and consensus is not running.
Therefore `process_payload_response` should never be called on a non-validating node, and if it does we should panic because that would be bug in our code.

File: test-utils/testlib/src/alphanet_utils.rs [hunk 3]
```diff
@@ -244,9 +237,14 @@ impl Node for ThreadNode {
 impl ThreadNode {
     /// Side effects: create storage, open database, lock database
     pub fn new(config: NodeConfig) -> ThreadNode {
-        let account_id = &config.client_cfg.account_id;
-        let signer = Arc::new(InMemorySigner::from_seed(account_id, account_id));
-        let client = Arc::new(Client::new_with_signer(&config.client_cfg, signer));
+        let signer = match &config.client_cfg.account_id {
```
Comment (nearmax) [inline test-utils/testlib/src/alphanet_utils.rs]: Use `map` here.

**Comment by nearmax** [comment]
> @bowenwang1996 no exactly, because for example Block &[u8] I would expect serialized block, versus `Signable` is actually hash of that block.

Good point. There are some issues with that: we should not have API that exposes byte representation of Rust objects or their protos except internally when we run serialization, which should be encapsulated. Currently, this is not a problem (even though our serialization code seems a bit off, see #833 ) since only crypto keys implement `ToBytes` and `AsRef<[u8]>`.
