### PR TITLE
fix(network): Compute neighbor properly.

### LINKED ISSUE #2547: Nightly failure: sanity/state_sync_routed.py manytx 100 times out
Times out consistently. Example runs:

http://nightly.neartest.com/run/f625606891dec008a572ca61ec37da500c2a95cd_200428_135923
http://nightly.neartest.com/run/2cef4105736ab969470df2751e78fd3f0fc0a81d_200428_102644

### PR DESCRIPTION
**Pull request by mfornet**
While choosing neighbor node to send a message that is going
to be routed, if the list of neighbors is two, and they are sorted
by nonce there was a bug that indicated that target node was
disconnected.

Test Plan
=========
In sanity/state_sync_routed.py check that no message is dropped
because a Peer is Disconnected, this should only happen when
peer which was online goes offline (not the case in this test).

Fix #2547

### CODE REVIEW

File: chain/network/src/peer_manager.rs [hunk 1]
```diff
@@ -787,6 +787,14 @@ impl PeerManagerActor {
     /// Route signed message to target peer.
     /// Return whether the message is sent or not.
     fn send_signed_message_to_peer(&mut self, ctx: &mut Context<Self>, msg: RoutedMessage) -> bool {
+        // Check if the message is for myself and don't try to send it in that case.
```
Comment (bowenwang1996) [inline chain/network/src/peer_manager.rs:790]: why would this happen to begin with?

File: chain/network/src/routing.rs [hunk 2]
```diff
@@ -327,17 +327,24 @@ impl RoutingTable {
...
-                } else {
+            // Find node with min nonce and node with max nonce.
+            // If there are no routes both min_v and max_v will be None.
+            // If there is only one route max_v will be None.
+            let (min_v, max_v) =
+                routes.iter().fold((None, None), |(mut min_v, mut max_v), peer_id| {
+                    let nonce = self.route_nonce.cache_get(&peer_id).cloned().unwrap_or(0usize);
+                    let mut current = Some((nonce, peer_id.clone()));
+
+                    if min_v.is_none() || *current.as_ref().unwrap() < *min_v.as_ref().unwrap() {
```
Comment (SkidanovAlex) [inline chain/network/src/routing.rs:338]: This is damn convoluted. Some comments describing basic scenarios (e.g. just one nonce, two nonces that increase, two nonces that decrease) and why those basic scenarios end up in the state we want would definitely help.

Comment (bowenwang1996) [inline chain/network/src/routing.rs:338]: It seems that you can compare `min_v` with `current` directly. Isn't that what you did with `max_v < current`?

Comment (SkidanovAlex) [reply chain/network/src/routing.rs:338]: Also, why `*current.as_ref().unwrap() < *min_v.as_ref().unwrap()` here, but just `max_v < current` below?

Comment (bowenwang1996) [reply chain/network/src/routing.rs:338]: I think it is just trying to compare the order of two things. The reason it looks complicated is because of `Option`.

Comment (mfornet) [reply chain/network/src/routing.rs:338]: Yep, at first current could be None, but it ended being always Some and didn't fix that.

Comment (mfornet) [reply chain/network/src/routing.rs:338]: Probably will implement a `min_max` function to get this logic out.

File: chain/network/src/peer_manager.rs (hunk 1 above)
Comment (mfornet) [reply chain/network/src/peer_manager.rs:790]: This is always the case with `ForwardTx`.
