### PR TITLE
fix(genesis): Don't write genesis records on restart

### LINKED ISSUE #3063: Investigate RAM usage for newly started node
Currently on TestNet node uses 4-4.5GB right after starting. This seems pretty high usage.

Causes:
 - Genesis json file is ~1GB and there might be a bunch of caches filled with it even though it's not really needed after creating initial block.
 - There are a lot of transactions that are been processed to catch up with the network, caches or leaks are possible.

### LINKED ISSUE #3151: Don't write genesis to storage on restart
Discovered in #3065. It's faster after the fix, but we should also not write genesis state again.

### PR DESCRIPTION
**Pull request by mikhailOK**
- When the node starts for the first time, save the hash of genesis in
storage, and assert on every restart that same genesis is used.

- Save the genesis state roots on first start, and don't rebuild the
trie on every restart.

Fixes #3151
Fixes #3063

Test plan
---------
existing tests

### CODE REVIEW

File: core/chain-configs/src/genesis_config.rs [hunk 1]
```diff
@@ -235,6 +236,16 @@ impl Genesis {
         )
         .expect("Failed to create / write a genesis config file.");
     }
+
+    /// Hash of the json-serialized input.
+    /// DEVNOTE: the representation is not unique, and could change on upgrade.
+    pub fn json_hash(&self) -> CryptoHash {
```
Comment (bowenwang1996) [inline core/chain-configs/src/genesis_config.rs:242]: Why do we serialize it in json instead of borsh? Also it seems that we don't need to hash `Genesis` entirely since records will go into state root and it suffices to hash genesis config.

File: core/store/src/db.rs [hunk 2]
```diff
@@ -234,6 +234,8 @@ pub const FINAL_HEAD_KEY: &[u8; 10] = b"FINAL_HEAD";
 pub const LATEST_KNOWN_KEY: &[u8; 12] = b"LATEST_KNOWN";
 pub const LARGEST_TARGET_HEIGHT_KEY: &[u8; 21] = b"LARGEST_TARGET_HEIGHT";
 pub const VERSION_KEY: &[u8; 7] = b"VERSION";
+pub const GENESIS_JSON_HASH_KEY: &[u8; 17] = b"GENESIS_JSON_HASH";
+pub const GENESIS_STATE_ROOTS_KEY: &[u8; 19] = b"GENESIS_STATE_ROTOS";
```
Comment (frol) [inline core/store/src/db.rs:238]:
```suggestion
pub const GENESIS_STATE_ROOTS_KEY: &[u8; 19] = b"GENESIS_STATE_ROOTS";
```

File: neard/src/runtime.rs [hunk 3]
```diff
@@ -216,7 +222,8 @@ impl NightshadeRuntime {
         epoch_manager.get_epoch_info(&epoch_id).map(|info| info.epoch_height).map_err(Error::from)
     }
 
-    fn genesis_state_from_dump(store: Arc<Store>, home_dir: &Path) -> (Arc<Store>, Vec<StateRoot>) {
+    fn genesis_state_from_dump(store: Arc<Store>, home_dir: &Path) -> Vec<StateRoot> {
+        error!(target: "near", "Loading genesis from a state dump file. Do not use this outside of genesis-tools");
```
Comment (frol) [inline neard/src/runtime.rs:226]: Target "near" looks odd here; is it on puprose? We use "runtime" here.

Why is it an error?

File: neard/src/runtime.rs [hunk 4]
```diff
@@ -227,21 +234,18 @@ impl NightshadeRuntime {
...
-        (store, state_roots)
+        state_roots
     }
 
-    fn genesis_state_from_records(
-        store: Arc<Store>,
-        genesis: &Genesis,
-    ) -> (Arc<Store>, ShardTries, Vec<StateRoot>) {
+    fn genesis_state_from_records(store: Arc<Store>, genesis: &Genesis) -> Vec<StateRoot> {
+        info!(target: "near", "Genesis state has {} records, computing state roots", genesis.records.0.len());
```
Comment (frol) [inline neard/src/runtime.rs:241]:
```suggestion
        info!(target: "runtime", "Genesis state has {} records, computing state roots", genesis.records.0.len());
```

File: core/chain-configs/src/genesis_config.rs (hunk 1 above)
Comment (mikhailOK) [reply core/chain-configs/src/genesis_config.rs:242]: This change uses the hash to avoid recomputing state roots. No changes to the protocol.

Genesis uses too many types that don't support borsh and some aren't in our crates, need a big refactor.

**Review by frol — APPROVED** [review]

File: neard/src/runtime.rs (hunk 3 above)
Comment (mikhailOK) [reply neard/src/runtime.rs:226]: This code is bad and should not be used by anyone. Seems like there is something in genesis-tools that still uses it, but otherwise we should remove it.

The reasoning was that this is genesis computation that happens once at the first start of the node, but can use runtime

Comment (mikhailOK) [reply neard/src/runtime.rs:226]: Actually for some reason target runtime does not show up for me, maybe it's disabled by default

Comment (frol) [reply neard/src/runtime.rs:226]: It could be the case, and that is fine. If you want to make something visible to the users of neard, I suggest you display the message from neard, not the runtime. The usage warning should go into the docstrings or deprecation attribute.

**Review by bowenwang1996 — APPROVED** [review]

File: neard/src/runtime.rs (hunk 3 above)
Comment (mikhailOK) [reply neard/src/runtime.rs:226]: this is neard crate

**Review by evgenykuzyakov — APPROVED** [review]
