### PR TITLE
fix(store): Fix refcount logic slowness

### LINKED ISSUE #3065: Opening database takes a very long time
After the hard-fork on testnet yesterday we observe that when restarting a node, it can potentially take more than half an hour to just open the database. To reproduce, initialize and start a testnet node by
```
neard --home=<home> init --chain-id="testnet" --genesis=genesis.json
neard --home=<home> run
```
where genesis.json can be found at https://s3-us-west-1.amazonaws.com/build.nearprotocol.com/nearcore-deploy/testnet/genesis.json.

After the node starts, you should be able to see that it is "Waiting for peers". Now shut down the node and restart by `neard --home=<home> run` and observe that it gets stuck.

### PR DESCRIPTION
**Pull request by mikhailOK**
Use rocksdb merge operator for ColState. No longer need to atomically
read + write on update.

Fixes #3065

Test plan
---------
sanity test
manually check performance

### CODE REVIEW

File: core/store/src/db.rs [hunk 1]
```diff
@@ -431,3 +464,125 @@ impl TestDB {
         Self { db: RwLock::new(db) }
     }
 }
+
+impl RocksDB {
+    /// ColState has refcounted values.
+    /// Merge adds refcounts, zero refcount becomes empty value.
+    /// Empty values get filtered by get methods, and removed by compaction.
+    fn refcount_merge(
+        _new_key: &[u8],
```
Comment (bowenwang1996) [inline core/store/src/db.rs:473]: why do we have an unused argument?

File: core/store/src/db.rs [hunk 2]
```diff
@@ -431,3 +464,125 @@ impl TestDB {
...
+        existing_val: Option<&[u8]>,
+        operands: &mut MergeOperands,
+    ) -> Option<Vec<u8>> {
+        let mut result = vec![];
+        if let Some(val) = existing_val {
+            // Error is only possible if decoding refcount fails (=value is between 1 and 3 bytes)
```
Comment (bowenwang1996) [inline core/store/src/db.rs:479]: why cannot value be between 1 and 3 bytes?

File: core/store/src/db.rs [hunk 3]
```diff
@@ -431,3 +464,125 @@ impl TestDB {
...
+        }
+        for val in operands {
+            // Error is only possible if decoding refcount fails (=value is between 1 and 3 bytes)
+            merge_refcounted_records(&mut result, val).unwrap();
+        }
+        Some(result)
+    }
+
+    fn empty_value_filter(_level: u32, _key: &[u8], value: &[u8]) -> Decision {
+        if value.len() == 0 {
```
Comment (bowenwang1996) [inline core/store/src/db.rs:490]:
```suggestion
        if value.is_empty() {
```

File: core/store/src/db.rs [hunk 4]
```diff
@@ -431,3 +464,125 @@ impl TestDB {
...
+
+    fn iter_empty_value_filtering<'a, I>(
+        column: DBCol,
+        iterator: I,
+    ) -> Box<dyn Iterator<Item = (Box<[u8]>, Box<[u8]>)> + 'a>
+    where
+        I: Iterator<Item = (Box<[u8]>, Box<[u8]>)> + 'a,
+    {
+        if column == DBCol::ColState {
+            Box::new(iterator.filter(|(_k, v)| v.len() != 0))
```
Comment (bowenwang1996) [inline core/store/src/db.rs:513]:
```suggestion
            Box::new(iterator.filter(|(_k, v)| !v.is_empty()))
```

File: core/store/src/trie/mod.rs [hunk 5]
```diff
@@ -395,21 +396,21 @@ impl RawTrieNodeWithSize {
...
+fn encode_trie_node_with_rc(data: &[u8], rc: i32) -> Vec<u8> {
     let mut cursor = Cursor::new(Vec::with_capacity(data.len() + 4));
     cursor.write_all(data).unwrap();
-    cursor.write_u32::<LittleEndian>(rc).unwrap();
+    cursor.write_i32::<LittleEndian>(rc).unwrap();
     cursor.into_inner()
 }
 
-fn decode_trie_node_with_rc(bytes: &[u8]) -> Result<(&[u8], u32), StorageError> {
+fn decode_trie_node_with_rc(bytes: &[u8]) -> Result<(&[u8], i32), StorageError> {
```
Comment (SkidanovAlex) [inline core/store/src/trie/mod.rs:406]: Why is it `i32` now?

File: core/store/src/db.rs (hunk 1 above)
Comment (mikhailOK) [reply core/store/src/db.rs:473]: this is the rocksdb MergeFn interface

File: core/store/src/db.rs (hunk 2 above)
Comment (mikhailOK) [reply core/store/src/db.rs:479]: we write (4 bytes of refcount + value), or empty to delete (because merge cannot delete).
1..3 is the only case when `merge_refcounted_records` can error, and it shouldn't be possible

File: core/store/src/trie/mod.rs (hunk 5 above)
Comment (mikhailOK) [reply core/store/src/trie/mod.rs:406]: Update writes encoded positive or negative refcount delta, and merge adds up updates. Records/partial sum can be negative, but the result from db.get() should always be positive (if it is <= 0, there is a bug in gc). Probably need to add a new assert, this change deleted the one from apply_deletions.

**Comment by mikhailOK** [comment]
In #3065 the bottleneck was calling `db.get()` 2.5 million times when we apply genesis, which was slow when we did it for the second time. Now this is just a batch write which is instant. Merging happens on `get()` and compaction, didn't measure but should be fast.

**Comment by mikhailOK** [comment]
Applying a block should become faster

File: core/store/src/db.rs [hunk 6]
```diff
@@ -415,9 +448,9 @@ impl RocksDB {
     pub fn new<P: AsRef<std::path::Path>>(path: P) -> Result<Self, DBError> {
         let options = rocksdb_options();
         let cf_names: Vec<_> = (0..NUM_COLS).map(|col| format!("col{}", col)).collect();
```
Comment (frol) [inline core/store/src/db.rs:450]: You can use `strum::EnumIter` to implement `.iter()` for DbCol and then iterate over it instead of relying implicitly on `0..NUM_COLS`: https://github.com/Peternator7/strum/wiki/Derive-EnumIter

File: core/store/src/db.rs [hunk 7]
```diff
@@ -415,9 +448,9 @@ impl RocksDB {
...
-        let cf_descriptors = cf_names
-            .iter()
-            .map(|cf_name| ColumnFamilyDescriptor::new(cf_name, rocksdb_column_options()));
+        let cf_descriptors = cf_names.iter().enumerate().map(|(col_index, cf_name)| {
+            ColumnFamilyDescriptor::new(cf_name, rocksdb_column_options(col_index))
```
Comment (frol) [inline core/store/src/db.rs:452]: Would you have a native iterator over all the enum variants (see ^^^), you would be able to pass a DBCol value and avoid the use of `usize` casting which creates implicit connections between an index and the DBCol value. We can leverage strong type system to help us avoid possible bugs.

File: core/store/src/db.rs [hunk 8]
```diff
@@ -431,3 +464,125 @@ impl TestDB {
...
+    /// Empty values get filtered by get methods, and removed by compaction.
+    fn refcount_merge(
+        _new_key: &[u8],
+        existing_val: Option<&[u8]>,
+        operands: &mut MergeOperands,
+    ) -> Option<Vec<u8>> {
+        let mut result = vec![];
+        if let Some(val) = existing_val {
+            // Error is only possible if decoding refcount fails (=value is between 1 and 3 bytes)
+            merge_refcounted_records(&mut result, val).unwrap();
```
Comment (frol) [inline core/store/src/db.rs:480]: Let's use `.expect(message)` instead of a comment + `.unwrap()`

File: core/store/src/db.rs [hunk 9]
```diff
@@ -431,3 +464,125 @@ impl TestDB {
...
+
+    fn empty_value_filter(_level: u32, _key: &[u8], value: &[u8]) -> Decision {
+        if value.is_empty() {
+            Decision::Remove
+        } else {
+            Decision::Keep
+        }
+    }
+
+    fn empty_value_filtering(column: DBCol, value: Option<Vec<u8>>) -> Option<Vec<u8>> {
```
Comment (frol) [inline core/store/src/db.rs:497]: This naming is hard to reason about :disappointed:

File: core/store/src/trie/mod.rs [hunk 10]
```diff
@@ -395,21 +396,21 @@ impl RawTrieNodeWithSize {
     }
 }
 
-fn encode_trie_node_with_rc(data: &[u8], rc: u32) -> Vec<u8> {
+fn encode_trie_node_with_rc(data: &[u8], rc: i32) -> Vec<u8> {
```
Comment (frol) [inline core/store/src/trie/mod.rs:399]: Should the naming reflect that this is now working with delta values instead of absolute values?

File: core/store/src/trie/trie_storage.rs [hunk 11]
```diff
@@ -113,16 +119,36 @@ pub struct TrieCachingStorage {
     pub(crate) shard_id: ShardId,
 }
 
+pub fn merge_refcounted_records(result: &mut Vec<u8>, val: &[u8]) -> Result<(), StorageError> {
+    if val.len() == 0 {
```
Comment (frol) [inline core/store/src/trie/trie_storage.rs:123]:
```suggestion
    if val.is_empty() {
```

File: core/store/src/trie/trie_storage.rs [hunk 12]
```diff
@@ -113,16 +119,36 @@ pub struct TrieCachingStorage {
...
+        return Ok(());
+    }
+    let add_rc = TrieCachingStorage::vec_to_rc(val)?;
+    if result.len() != 0 {
```
Comment (frol) [inline core/store/src/trie/trie_storage.rs:127]:
```suggestion
    if !result.is_empty() {
```

File: core/store/src/db.rs (hunk 6 above)
Comment (mikhailOK) [reply core/store/src/db.rs:451]: Hmm this will break compatibility for sure, but now we don't need to think if adding a merge operator breaks it.

File: core/store/src/trie/mod.rs (hunk 10 above)
Comment (mikhailOK) [reply core/store/src/trie/mod.rs:399]: It's actually both: we write deltas, but read absolute values (aggregation happens in merge operator). Makes sense to do a refactor to move refcount logic from Trie to Store, but we can do it separately

File: core/store/src/db.rs (hunk 6 above)
Comment (frol) [reply core/store/src/db.rs:451]: How would it break it?

The values are fixed numbers, so when you iterate over there enum variants and do `variant as usize` you will get the same number as it is not, but strictly typed up until the point of casting

Comment (mikhailOK) [reply core/store/src/db.rs]: makes sense now

**Comment by mikhailOK** [comment]
Manually tested restarting with this change on old storage
