### PR TITLE
Fixes #682: handling listening meta-address

### LINKED ISSUE #682: Running two nodes with the same port
Triggers:
```
thread 'tokio-runtime-worker-1' panicked at 'Received info about itself. Contr-adversarial behavior is not implemented yet.', node/network/src/peer.rs:297:33
```

Repro:
Machine1: 
```bash
cargo run --release -- --addr 0.0.0.0:3000 --rpc_port 3030 --base-path=test1 --test-network
-key-seed 1 --chain-spec-file ./node/configs/res/testnet_chain.json -a alice.near
```

Machine2: 
```bash
cargo run --release -- --addr 0.0.0.0:3000 --rpc_port 3030 --base-path=test2 --test-network
-key-seed 2 --chain-spec-file ./node/configs/res/testnet_chain.json -a bob.near --boot-nodes 34.73.11.29:3000/GuMri
ipt4yUXfkZL2z3zLPbYaozkZG6zjV6vg4QruEvY
```

### PR DESCRIPTION
**Pull request by ilblackdragon**
Fixes #682

### CODE REVIEW

File: core/primitives/src/network.rs [hunk 1]
```diff
@@ -3,6 +3,35 @@ use std::borrow::Borrow;
 use std::fmt;
 use std::hash::{Hash, Hasher};
 use std::net::SocketAddr;
+use std::convert::TryFrom;
+
+#[derive(Clone, Debug, Serialize, Deserialize)]
+pub struct NodeAddr {
```
Comment (nearmax) [inline core/primitives/src/network.rs]: Should it be `PeerAddr`. Also, what is the distinction between `NodeAddr` and `PeerInfo`?

File: node/alphanet/src/testing_utils.rs [hunk 2]
```diff
@@ -49,7 +49,7 @@ impl Node {
             chain_spec
         )
     }
-    pub fn for_test_passive(test_prefix: &str, test_port: u16, account_id: &str, peer_id: u16, boot_nodes: Vec<PeerInfo>, chain_spec: ChainSpec) -> Self {
+    pub fn for_test_passive(test_prefix: &str, test_port: u16, account_id: &str, peer_id: u16, boot_nodes: Vec<NodeAddr>, chain_spec: ChainSpec) -> Self {
```
Comment (nearmax) [inline node/alphanet/src/testing_utils.rs]: Could we add a docstring on what `for_test_passive` does?

File: node/alphanet/src/testing_utils.rs [hunk 3]
```diff
@@ -125,6 +125,12 @@ impl Node {
         });
         thread::sleep(Duration::from_secs(1));
     }
+
+    pub fn node_addr(&self) -> NodeAddr {
+        let addr = self.network_cfg.listen_addr.expect("Node doesn't have an address").to_string();
+        let chunks: Vec<_> = addr.split(':').collect();
```
Comment (nearmax) [inline node/alphanet/src/testing_utils.rs]: Use `SocketAddr::port` instead of doing manual parsing.

File: node/network/src/peer.rs [hunk 4]
```diff
@@ -39,8 +40,12 @@ const POISONED_LOCK_ERR: &str = "The lock was poisoned.";
 pub struct Handshake {
     /// Protocol version.
     pub version: u32,
-    /// Sender's peer information.
-    pub info: PeerInfo,
+    /// Sender's peer id.
+    pub peer_id: PeerId,
```
Comment (nearmax) [inline node/network/src/peer.rs]: Why do we need to replace `info: PeerInfo` with three separate fields that represent exactly the same information?

File: node/network/src/peer_manager.rs [hunk 5]
```diff
@@ -60,7 +57,7 @@ impl<T: ChainStateRetriever> PeerManager<T> {
         // Spawn peers that represent boot nodes.
         Peer::spawn_from_known(
             node_info.clone(),
-            boot_nodes.to_vec(),
+            boot_nodes.to_vec().drain(..).map(std::convert::Into::into).collect(),
```
Comment (nearmax) [inline node/network/src/peer_manager.rs]: `drain` and `into_iter` are somewhat redundant to each other, but when the drained collection is not planned to be used it makes sense to use `into_iter` instead.
```suggestion
            boot_nodes.to_vec().into_iter().map(std::convert::Into::into).collect(),
```

File: node/alphanet/src/testing_utils.rs (hunk 2 above)
Comment (nearmax) [reply node/alphanet/src/testing_utils.rs]: Fixed.

File: node/alphanet/src/testing_utils.rs (hunk 3 above)
Comment (nearmax) [reply node/alphanet/src/testing_utils.rs]: Fixed.

File: core/primitives/src/network.rs (hunk 1 above)
Comment (nearmax) [reply core/primitives/src/network.rs]: Fixed.

File: node/network/src/peer_manager.rs (hunk 5 above)
Comment (nearmax) [reply node/network/src/peer_manager.rs]: Fixed.
