### PR TITLE
Write authority info to storage

### LINKED ISSUE #612: Authority should be using disk storage
DevNet has a very slow start when it launches on an existing storage. To reproduce:
- Unpack the storage: https://drive.google.com/open?id=1gCmFjQw_BbC02_Fiq1nDQctIjWOfb8jS
- Check out the commit from the mater: 0b2e2613a506a2fc848dd9e3cc60e6cd6464b7dd
- Observe that DevNet takes >>10mins to start.

### Root cause
What slows down DevNet is computation of the authority schedule and the fact that we use stake rollover. Specifically, in order to compute which authorities are participating in a block of epoch E we need to know all the blocks in epoch E-2 and the authorities of epoch E-2. In order to know authorities of blocks in epoch E-2 we need to know authorities of epoch E-4.

This long-range dependency happens because we allow the stake to rollover without re-staking. So if some authority staked themselves in epoch E-2X the only way to know whether this authority is participating in epoch E is to know all its participation in epochx E-2X, E-2X+2, ... . 

### Short-term solution
Currently there is no way to avoid computation of authorities for each block starting from genesis, even if the node joins the network on the block index far in the future. However, if we have a node (or Devnet) that was stopped and then restarted we can avoid recomputing authorities for all blocks starting from the genesis. This can be done by storing computed authorities in the storage, which is already allowed by current chain/storage architecture.

Specifically, the following code is where the slowness happens: https://github.com/nearprotocol/nearcore/blob/master/node/beacon/src/authority.rs#L111
It iterates over the headers starting from genesis and computes authorities for each of them. Instead we need to:
* Store `proposals`, `participation`, `thresholds`, and `accepted_authorities` in storage in addition to keeping these fields in `Authority`;
* `compute_accepted_authorities` and `process_block_header` would then check whether the information is already available in the storage before processing it;
* To operate with storage `Authority` would need to have a dependency on  `BeaconChainStorage`. And would need to have additional methods that store and retrieve `proposals`, `participation`, `thresholds`, and `accepted_authorities` from the corresponding columns in the storage https://github.com/nearprotocol/nearcore/blob/master/core/storage/src/storages/beacon.rs See for the reference how `ShardChainStorage` has special method to store and retrieve transaction addresses and transaction results: https://github.com/nearprotocol/nearcore/blob/master/core/storage/src/storages/shard.rs

### Long-term solution
Currently, `BeaconBlock` has not additional information compared to `BeaconBlockHeader`. Instead it should store the computed authorities for that block. ( `BeaconBlockHeader` only stares proposals, which is not enough because we need to know whether the stake was rolled over).

### PR DESCRIPTION
**Pull request by bowenwang1996**
Fixes #612 by writing `proposals`, `participation`, `processed_blocks`, `thresholds`, and `accepted_authorities` to storage when `process_header` is called. Those information is read from storage when authority is initialized.

### CODE REVIEW

File: node/beacon/src/authority.rs [hunk 1]
```diff
@@ -81,51 +90,106 @@ impl Authority {
...
+    fn prune_epoch<V: Clone>(&self, data: &HashMap<Epoch, V>) -> HashMap<Epoch, V> {
+        data.iter()
+            .filter(|(&k, &_)| k >= self.current_epoch)
+            .map(|(k, v)| (k.clone(), v.clone()))
+            .collect()
+    }
+
+    fn write_to_storage(&self) {
+        // prune old epochs
+        let proposals = self.prune_slot(&self.proposals);
```
Comment (ilblackdragon) [inline node/beacon/src/authority.rs]: should we also update self.proposals/participation/etc here?
e.g. as we write, we actually prune the old data as well in memory?

File: node/beacon/src/authority.rs [hunk 2]
```diff
@@ -81,51 +90,106 @@ impl Authority {
...
-        while index <= blockchain.best_block().header().body.index {
-            if log_enabled!(target: "client", Debug) {
-                let best_block_index = blockchain.best_block().header().body.index;
-                let progress = index * 100 / best_block_index;
-                if progress != last_progress {
-                    debug!(target: "client", "Processing blocks {} out of {}", index, best_block_index);
-                    last_progress = progress;
+            // Catch up with the blockchain. Note, the last block is allowed to progress while we
+            // are iterating.
+            // TODO: Take care of the fork being changed while we are iterating.
```
Comment (ilblackdragon) [inline node/beacon/src/authority.rs]: we can have forks in two cases:
  - less then 2/3 sigs (e.g. block is not finalized, we should not process it here)
 - malicious 2/3 sigs on a block, and we have network split. Here we can actually can have switching of the preferred fork. But should think through this on across client in general.

File: node/beacon/src/authority.rs [hunk 3]
```diff
@@ -81,51 +90,106 @@ impl Authority {
...
-            result.authority_config.initial_proposals.to_vec(),
-            vec![],
-        );
-        let mut slot = 0;
-        for epoch in 0..=1 {
-            result.thresholds.insert(epoch, threshold);
-            for slot_auth in &accepted_authorities {
-                slot += 1;
-                result.accepted_authorities.insert(slot, slot_auth.to_vec());
+        result.read_from_storage();
```
Comment (ilblackdragon) [inline node/beacon/src/authority.rs]: what about current_epoch? 
doesn't seem like it's calculated if read from storage?

File: node/beacon/src/authority.rs [hunk 4]
```diff
@@ -440,4 +506,26 @@ mod test {
         assert_eq!(find_threshold(&[1000, 1, 1, 1, 1, 1, 1, 1, 1, 1], 1).unwrap(), 1000);
         assert!(find_threshold(&[1, 1, 2], 100).is_err());
     }
+
+    #[test]
+    fn test_write_to_storage() {
```
Comment (ilblackdragon) [inline node/beacon/src/authority.rs]: this test doesn't acutally check that you restored the state correctly. please test here:
  - create blockchain with storage and write blocks
  - re-create blockchain with the same storage and check that `get_authorities` is the same.

File: node/beacon/src/authority.rs (hunk 3 above)
Comment (bowenwang1996) [reply node/beacon/src/authority.rs]: I don't think it is necessary to calculate that. `self.current_epoch` is only used for pruning and is  only updated when we need to write to storage.

File: node/beacon/src/authority.rs (hunk 2 above)
Comment (bowenwang1996) [reply node/beacon/src/authority.rs]: I think it is out of the scope of this PR

File: node/beacon/src/authority.rs (hunk 4 above)
Comment (bowenwang1996) [reply node/beacon/src/authority.rs]: Fixed

File: node/beacon/src/authority.rs (hunk 1 above)
Comment (bowenwang1996) [reply node/beacon/src/authority.rs]: Fixed

Comment (bowenwang1996) [reply node/beacon/src/authority.rs]: Looks like we cannot prune this right now because of the hard coded block index in protocol https://github.com/nearprotocol/nearcore/blob/29957183f8d60310710f9a455b08c882f73ad4af/node/network/src/protocol.rs#L162

File: node/beacon/src/authority.rs (hunk 3 above)
Comment (ilblackdragon) [reply node/beacon/src/authority.rs]: Let's then not have it as a field, instead pass it to `write_to_storage(epoch)` and to prune methods.
Ppl will use it if it's available and it will lead to weird bugs.

File: node/beacon/src/authority.rs [hunk 5]
```diff
@@ -440,4 +507,29 @@ mod test {
...
+        let block2 = SignedBeaconBlock::new(2, header1.block_hash(), vec![], CryptoHash::default());
+        let mut header2 = block2.header();
+        header2.signature.authority_mask = vec![true, true];
+        authority.process_block_header(&header1);
+        authority.process_block_header(&header2);
+        let next_authorities = authority.get_authorities(3);
+        assert!(next_authorities.is_ok());
+
+        let bc1 = BeaconClient::new(
+            block2.clone(),
```
Comment (ilblackdragon) [inline node/beacon/src/authority.rs]: isn't this a genesis block as the first argument and you are passing block with `index=2`? how is this not failing - it's offtopic to this PR, but let's add a check that if BeaconClient started with different genesis, it should fail.

File: core/storage/src/storages/beacon.rs [hunk 6]
```diff
@@ -1,9 +1,19 @@
...
-use primitives::beacon::SignedBeaconBlock;
-use primitives::beacon::SignedBeaconBlockHeader;
+use primitives::beacon::{SignedBeaconBlock, SignedBeaconBlockHeader};
+use primitives::types::{AuthorityStake, AuthorityMask};
+use primitives::serialize::{Encode, Decode};
 use std::sync::Arc;
+use std::collections::{HashMap, HashSet};
+use std::hash::Hash;
+
+type Epoch = u64;
```
Comment (nearmax) [inline core/storage/src/storages/beacon.rs]: `Epoch` and `Slot` types are already defined somewhere else, see authority. Use `use` instead of redefining them.

File: core/storage/src/storages/beacon.rs [hunk 7]
```diff
@@ -22,6 +32,74 @@ impl GenericStorage<SignedBeaconBlockHeader, SignedBeaconBlock> for BeaconChainS
...
+    pub fn get_accepted_authorities(&mut self) -> HashMap<Slot, Vec<AuthorityStake>> {
+        read_one_column(self.generic_storage.storage.as_ref(), COL_ACCEPTED_AUTHORITY)
+    }
+
+    pub fn set_accepted_authorities(&mut self, accepted_authorities: &HashMap<Slot, Vec<AuthorityStake>>) {
+        write_one_column(self.generic_storage.storage.as_ref(), COL_ACCEPTED_AUTHORITY, accepted_authorities);
+    }
+}
+
+fn read_one_column<K, V>(storage: &KeyValueDB, col: u32) -> HashMap<K, V>
```
Comment (nearmax) [inline core/storage/src/storages/beacon.rs]: This implementation is going to be very expensive. We should not be retrieving the entire column from the storage.

File: node/beacon/src/authority.rs [hunk 8]
```diff
@@ -57,12 +61,17 @@ pub struct Authority {
     participation: HashMap<Slot, AuthorityMask>,
```
Comment (nearmax) [inline node/beacon/src/authority.rs]: This implementation should be doing caching in the same way we do caching for `storage/src/storages/{beacon.rs, shard.rs}`. Specifically, collections like `thresholds`, `accepted_authorities`, `processed_blocks`, `participation`, `proposals` should be used similarly to how we use e.g. `transaction_results` in `ShardChainStorage`. In other words, they should be moved into `storage/src/storages/beacon.rs`.

We then should implement pruning as the generic feature of our `storage/src/storages/mod.rs` because we will be applying it to other columns and not just authority-related data.

File: core/storage/src/storages/beacon.rs (hunk 7 above)
Comment (bowenwang1996) [reply core/storage/src/storages/beacon.rs]: We only do this when we initialize the authority struct, which does not happen very often

File: node/beacon/src/authority.rs (hunk 8 above)
Comment (bowenwang1996) [reply node/beacon/src/authority.rs]: The API for reading from and writing to storage is very limited and does not work well with the code in authority that uses them, unless we expose more methods like iterators, entry, etc.

Comment (nearmax) [reply node/beacon/src/authority.rs]: Why do we need to expose iterators and entry?

File: core/storage/src/storages/beacon.rs (hunk 6 above)
Comment (bowenwang1996) [reply core/storage/src/storages/beacon.rs]: It was defined in authority. To avoid cyclic dependency, I moved them to primitives.

File: node/beacon/src/authority.rs (hunk 3 above)
Comment (bowenwang1996) [reply node/beacon/src/authority.rs]: Fixed

File: core/storage/src/storages/beacon.rs (hunk 7 above)
Comment (nearmax) [reply core/storage/src/storages/beacon.rs]: This is still very inefficient. We should not be loading all of the objects in the cache upon initialization. What should be happening is whenever someone requests information on slot X, this information is retrieved from the storage, added to cache and the reference is returned.

File: node/beacon/src/authority.rs (hunk 8 above)
Comment (nearmax) [reply node/beacon/src/authority.rs]: Also, the other point that I brought is that the implementation should be explicit about what containers are used as cache, and these cache containers should live in storage structs and not authorities.

Comment (nearmax) [reply node/beacon/src/authority.rs]: Also, we want pruning to be a feature of the storage, so that we can apply it to other stuff and not just authorities. And it will prevent code duplication, because otherwise every component that uses storage will be implementing its own version of pruning.

Comment (bowenwang1996) [reply node/beacon/src/authority.rs]: There are things like https://github.com/nearprotocol/nearcore/blob/7ffb2698fc9fe4b908423f13b9352856cdaab26a/node/beacon/src/authority.rs#L281, https://github.com/nearprotocol/nearcore/blob/7ffb2698fc9fe4b908423f13b9352856cdaab26a/node/beacon/src/authority.rs#L273,
https://github.com/nearprotocol/nearcore/blob/7ffb2698fc9fe4b908423f13b9352856cdaab26a/node/beacon/src/authority.rs#L307, which can be done with the current API but will make code less readable.

Comment (bowenwang1996) [reply node/beacon/src/authority.rs]: I thought we want pruning to be domain-specific.

File: node/beacon/src/authority.rs (hunk 5 above)
Comment (bowenwang1996) [reply node/beacon/src/authority.rs]: Created an issue for this https://github.com/nearprotocol/nearcore/issues/690

File: node/beacon/src/authority.rs (hunk 8 above)
Comment (nearmax) [reply node/beacon/src/authority.rs]: The above pieces of code would change to:
```
self.storage.get_processed_slots(epoch)
```
```
if slot >0 && !self.storage.has_slot(&slot) {
```
```
self.storage.get_processed_slots(epoch).len()
```
(Btw, there is a typo, we should be passing epoch and not slot above)

Are you suggesting this is less readable? To me it looks more readable.

Comment (nearmax) [reply node/beacon/src/authority.rs]: It most cases pruning would be either time-based or LRU-based. We can have a domain-specific pruning strategy, but I do not think we have a strong need in it at the moment.

**Comment by bowenwang1996** [comment]
I switched to using cache when writing to storage. However pruning cannot be enabled because of #693

File: node/beacon/src/authority.rs [hunk 9]
```diff
@@ -251,51 +258,68 @@ impl Authority {
...
+                let len = processed_slots.len();
+                storage.set_processed_blocks(epoch, processed_slots);
+                (len == self.authority_config.epoch_length as usize, epoch)
             };
+            
             // Check if we have processed all slots from the given epoch.
             if all_slots_processed {
                 // Compute accepted authorities for epoch+2.
                 self.compute_accepted_authorities(epoch + 2);
+                self.storage.write().expect(POISONED_LOCK_ERR).prune_authority_storage(
```
Comment (nearmax) [inline node/beacon/src/authority.rs]: So pruning currently heavily relies on the assumption that once we prune epoch X, we will never need to know authorities for this epoch, because if we do (for whatever reason) authority has no mechanism to ask client to re-feed it the old headers of blocks in epoch X. An attempt to get pruned authorities, however should then either panic or return `Err`. If we return `Err` then the client code that uses it will need an additional layer of logic that recovers from it. Pruning seems to be making our code more complex at the moment. Also, it is not decided yet whether we should be pruning blocks/headers, if we do not then it does not make much sense to prune authorities because they are negligibly smaller than blocks/headers.

I suggest we do to things right now:
* Add code to the client that recovers from the `Err` that we should return when the pruned authorities are requested;
* Have a separate issue for other pruning of the storage, like blocks, headers, transactions, etc.

File: core/storage/src/storages/beacon.rs [hunk 10]
```diff
@@ -22,6 +39,175 @@ impl GenericStorage<SignedBeaconBlockHeader, SignedBeaconBlock> for BeaconChainS
...
+            &self.generic_storage.enc_index(slot)
+        ).expect("Failed to read from storage")
+    }
+
+    pub fn set_participation(&mut self, slot: Slot, mask: AuthorityMask) {
+        write_with_cache(
+            self.generic_storage.storage.as_ref(),
+            COL_PARTICIPATION,
+            &mut self.participation,
+            &self.generic_storage.enc_index(slot),
```
[the remark this answers is not in the document]
Comment (nearmax) [reply core/storage/src/storages/beacon.rs]: I just realized that we might not be able to implement `Borrow<[u8]>` for `Slot` and `Epoch`, because `Slot` and `Epoch` are type aliases of the types outside our crates.

File: node/beacon/src/authority.rs [hunk 11]
```diff
@@ -251,51 +258,68 @@ impl Authority {
             // Second, use the proposals and the rollovers.
             // TODO(#308): Use proper seed.
             let (mut accepted_authorities, new_threshold) = {
-                let proposals =
-                    self.epoch_to_slots(epoch - 2).flat_map(|s| self.proposals[&s].iter().cloned());
+                let mut proposals = vec![];
+                for s in self.epoch_to_slots(epoch - 2) {
+                    let new_proposals = storage.get_proposal(s).cloned().unwrap_or_else(|| vec![]);
```
[the remark this answers is not in the document]
Comment (bowenwang1996) [reply node/beacon/src/authority.rs]: Because of lifetimes issues. Both new_proposals and participation require mutable reference to storage.

File: node/beacon/src/authority.rs (hunk 9 above)
Comment (bowenwang1996) [reply node/beacon/src/authority.rs]: How does client recover from the error we return?

File: node/beacon/src/authority.rs [hunk 12]
```diff
@@ -203,16 +201,25 @@ impl Authority {
...
+        let mut storage = self.storage.write().expect(POISONED_LOCK_ERR);
+        if let Some(threshold) = storage.get_threshold(epoch - 2).cloned() {
             // First, compute the rollovers. Using Vec for rollovers to enforce determinism.
             let mut ordered_rollovers: Vec<AuthorityStake> = vec![];
             let mut indices = HashMap::new();
             let mut penalties = HashMap::new();
             for s in self.epoch_to_slots(epoch - 2) {
-                let accepted = self.accepted_authorities[&s].iter();
-                let participation = self.participation[&s].iter();
+                let accepted = storage
```
[the remark this answers is not in the document]
Comment (bowenwang1996) [reply node/beacon/src/authority.rs]: Because of lifetimes issues. Both new_proposals and participation require mutable reference to storage.

File: node/beacon/src/authority.rs (hunk 11 above)
[the remark this answers is not in the document]
Comment (nearmax) [reply node/beacon/src/authority.rs]: So we only need to clone one of them, not both.

File: core/storage/src/storages/beacon.rs (hunk 10 above)
[the remark this answers is not in the document]
Comment (bowenwang1996) [reply core/storage/src/storages/beacon.rs]: True. We can wrap them in new types if we really want to, but then there need to be more boilerplate code when converting from/to slices.

File: node/beacon/src/authority.rs (hunk 9 above)
Comment (nearmax) [reply node/beacon/src/authority.rs]: It should depends on the where in the clients code we request authorities. This would require an investigation on your part, go through every part of client that calls authority and make sure that if it requests a pruned authority then it does not just crash and burn.

File: core/storage/src/storages/beacon.rs (hunk 10 above)
[the remark this answers is not in the document]
Comment (nearmax) [reply core/storage/src/storages/beacon.rs]: Yeah, let's not do this for now.

File: node/beacon/src/authority.rs [hunk 13]
```diff
@@ -203,16 +201,25 @@ impl Authority {
...
+                    .get_accepted_authorities(s)
+                    .cloned()
+                    .unwrap_or_else(|| vec![])
```
[the remark this answers is not in the document]
Comment (bowenwang1996) [reply node/beacon/src/authority.rs]: Fixed

File: node/beacon/src/authority.rs [hunk 14]
```diff
@@ -203,16 +201,25 @@ impl Authority {
...
+                    .into_iter();
+                let participation = storage
+                    .get_participation(s)
+                    .cloned()
+                    .unwrap_or_else(|| vec![])
```
[the remark this answers is not in the document]
Comment (bowenwang1996) [reply node/beacon/src/authority.rs]: Fixed

File: node/beacon/src/authority.rs (hunk 12 above)
[the remark this answers is not in the document]
Comment (bowenwang1996) [reply node/beacon/src/authority.rs]: Changed to cloning only one

File: node/beacon/src/authority.rs (hunk 11 above)
[the remark this answers is not in the document]
Comment (bowenwang1996) [reply node/beacon/src/authority.rs]: Here cloning is necessary

File: node/beacon/src/authority.rs (hunk 9 above)
Comment (bowenwang1996) [reply node/beacon/src/authority.rs]: Fixed

File: node/client/src/lib.rs [hunk 15]
```diff
@@ -193,13 +195,19 @@ impl Client {
...
             .authority
             .read()
             .expect(POISONED_LOCK_ERR)
-            .get_authorities(last_block.body.header.index + 1)
-            .expect("Authorities should be present for given block to produce it");
+            .get_authorities(next_index) {
+                Ok(authority) => authority,
+                Err(e) => {
+                    warn!("Cannot find authority for index {}: {}", next_index, e);
+                    return BlockProductionResult::AuthorityNotFound { next_index }
```
Comment (nearmax) [inline node/client/src/lib.rs]: This is actually should not be happening. Block production should not be failing due to pruning removing authorities needed for the block production.

**Comment by bowenwang1996** [comment]
I don't think just pruning the cache actually helps. If the client has been running for a while, the same problem could occur. I disabled pruning for now.

File: node/client/src/lib.rs (hunk 15 above)
Comment (bowenwang1996) [reply node/client/src/lib.rs]: Fixed

**Comment by nearmax** [comment]
> I don't think just pruning the cache actually helps. If the client has been running for a while, the same problem could occur. I disabled pruning for now.

It helps because otherwise the node will be crashing because it can run out of RAM. We however then also need to prune other cached stuff, like blocks which btw are much heavier than authority info. So we will need to revisit pruning many times in the future.
