### PR TITLE
Fix Runtime RPC tests and enable them on nightly

### LINKED ISSUE #2208: Runtime expensive tests trigger an assert in `cache.rs`
**When this issue is fixed, uncomment tests in nightly.txt that were affected. Search for 2208 in the file to find the tests.**

A series of night expensive runtime tests:

```
[FAILED] | stdout (689) | stderr (3K) |   | expensive nearcore test_tps_regression test::test_highload
-- | -- | -- | -- | --
[FAILED] | stdout (16) | stderr (71K) |   | expensive nearcore test_cases_testnet_rpc test::test_smart_contract_simple_testnet
[FAILED] | stdout (16) | stderr (43K) |   | expensive nearcore test_cases_testnet_rpc test::test_smart_contract_self_call_testnet
[FAILED] | stdout (16) | stderr (71K) |   | expensive nearcore test_cases_testnet_rpc test::test_smart_contract_bad_method_name_testnet
[FAILED] | stdout (16) | stderr (72K) |   | expensive nearcore test_cases_testnet_rpc test::test_smart_contract_empty_method_name_with_no_tokens_testnet
[FAILED] | stdout (16) | stderr (71K) |   | expensive nearcore test_cases_testnet_rpc test::test_smart_contract_empty_method_name_with_tokens_testnet
[FAILED] | stdout (16) | stderr (72K) |   | expensive nearcore test_cases_testnet_rpc test::test_smart_contract_with_args_testnet
```

all fail with the same assert:

```
thread '<unnamed>' panicked at 'assertion failed: `(left == right)`
  left: ``11111111111111111111111111111111``,
 right: ``HJ757Ygix3Wfwzuc8zJm8j3JmpyB1rvnhDgvX247nKVR``', runtime/runtime/src/cache.rs:25:13
stack backtrace:
   0: backtrace::backtrace::libunwind::trace
             at /cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.37/src/backtrace/libunwind.rs:88
   1: backtrace::backtrace::trace_unsynchronized
             at /cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.37/src/backtrace/mod.rs:66
   2: std::sys_common::backtrace::_print_fmt
             at src/libstd/sys_common/backtrace.rs:76
   3: <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt
             at src/libstd/sys_common/backtrace.rs:60
   4: core::fmt::write
             at src/libcore/fmt/mod.rs:1028
   5: std::io::Write::write_fmt
             at src/libstd/io/mod.rs:1412
   6: std::sys_common::backtrace::_print
             at src/libstd/sys_common/backtrace.rs:64
   7: std::sys_common::backtrace::print
             at src/libstd/sys_common/backtrace.rs:49
   8: std::panicking::default_hook::{{closure}}
             at src/libstd/panicking.rs:196
   9: std::panicking::default_hook
             at src/libstd/panicking.rs:210
  10: <alloc::boxed::Box<F> as core::ops::function::Fn<A>>::call
             at /rustc/032a53a06ce293571e51bbe621a5c480e8a28e95/src/liballoc/boxed.rs:924
  11: near_primitives::test_utils::init_stop_on_panic::{{closure}}::{{closure}}
             at core/primitives/src/test_utils.rs:76
  12: std::panicking::rust_panic_with_hook
             at src/libstd/panicking.rs:477
  13: std::panicking::continue_panic_fmt
             at src/libstd/panicking.rs:380
  14: std::panicking::begin_panic_fmt
             at src/libstd/panicking.rs:335
  15: node_runtime::cache::get_code::{{closure}}::{{closure}}
             at runtime/runtime/src/cache.rs:25
  16: core::option::Option<T>::map
             at /rustc/032a53a06ce293571e51bbe621a5c480e8a28e95/src/libcore/option.rs:447
  17: node_runtime::cache::get_code::{{closure}}
             at runtime/runtime/src/cache.rs:24
  18: node_runtime::cache::get_code
             at ./<::cached::macros::cached_key macros>:15
  19: node_runtime::actions::get_code_with_cache
             at runtime/runtime/src/actions.rs:108
  20: node_runtime::actions::action_function_call
             at runtime/runtime/src/actions.rs:125
  21: node_runtime::Runtime::apply_action
             at runtime/runtime/src/lib.rs:330
  22: node_runtime::Runtime::apply_action_receipt
             at runtime/runtime/src/lib.rs:449
  23: node_runtime::Runtime::process_receipt
             at runtime/runtime/src/lib.rs:781
  24: node_runtime::Runtime::apply::{{closure}}
             at runtime/runtime/src/lib.rs:986
  25: node_runtime::Runtime::apply
             at runtime/runtime/src/lib.rs:1053
  26: near::runtime::NightshadeRuntime::process_state_update
             at near/src/runtime.rs:298
  27: <near::runtime::NightshadeRuntime as near_chain::types::RuntimeAdapter>::apply_transactions_with_optional_storage_proof
             at near/src/runtime.rs:870
  28: near_chain::types::RuntimeAdapter::apply_transactions
             at ./chain/chain/src/types.rs:339
  29: near_chain::chain::ChainUpdate::apply_chunks
             at chain/chain/src/chain.rs:2402
  30: near_chain::chain::ChainUpdate::process_block
             at ./chain/chain/src/chain.rs:2626
  31: near_chain::chain::Chain::process_block_single
             at ./chain/chain/src/chain.rs:928
  32: near_chain::chain::Chain::process_block
             at ./chain/chain/src/chain.rs:610
  33: near_client::client::Client::process_block
             at chain/client/src/client.rs:624
  34: near_client::client_actor::ClientActor::process_block
             at chain/client/src/client_actor.rs:694
  35: near_client::client_actor::ClientActor::produce_block
             at chain/client/src/client_actor.rs:631
  36: near_client::client_actor::ClientActor::handle_block_production
             at chain/client/src/client_actor.rs:600
  37: near_client::client_actor::ClientActor::block_production_tracking
             at chain/client/src/client_actor.rs:613
  38: near_client::client_actor::ClientActor::block_production_tracking::{{closure}}
             at chain/client/src/client_actor.rs:621
  39: <F as actix::utils::TimerFuncBox<A>>::call
             at /home/alex/.cargo/registry/src/github.com-1ecc6299db9ec823/actix-0.9.0/src/utils.rs:114
  40: <actix::utils::TimerFunc<A> as actix::fut::ActorFuture>::poll
             at /home/alex/.cargo/registry/src/github.com-1ecc6299db9ec823/actix-0.9.0/src/utils.rs:135
  41: <alloc::boxed::Box<F> as actix::fut::ActorFuture>::poll
             at /home/alex/.cargo/registry/src/github.com-1ecc6299db9ec823/actix-0.9.0/src/fut/mod.rs:299
  42: <actix::contextimpl::ContextFut<A,C> as core::future::future::Future>::poll
             at /home/alex/.cargo/registry/src/github.com-1ecc6299db9ec823/actix-0.9.0/src/contextimpl.rs:382
  43: <core::pin::Pin<P> as core::future::future::Future>::poll
             at /rustc/032a53a06ce293571e51bbe621a5c480e8a28e95/src/libcore/future/future.rs:119
  44: tokio::task::core::Core<T>::poll
             at /home/alex/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-0.2.9/src/task/core.rs:128
  45: tokio::task::harness::Harness<T,S>::poll::{{closure}}::{{closure}}
             at /home/alex/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-0.2.9/src/task/harness.rs:120
  46: core::ops::function::FnOnce::call_once
             at /rustc/032a53a06ce293571e51bbe621a5c480e8a28e95/src/libcore/ops/function.rs:227
  47: <std::panic::AssertUnwindSafe<F> as core::ops::function::FnOnce<()>>::call_once
             at /rustc/032a53a06ce293571e51bbe621a5c480e8a28e95/src/libstd/panic.rs:315
  48: std::panicking::try::do_call
             at /rustc/032a53a06ce293571e51bbe621a5c480e8a28e95/src/libstd/panicking.rs:292
  49: __rust_maybe_catch_panic
             at src/libpanic_unwind/lib.rs:80
  50: std::panicking::try
             at /rustc/032a53a06ce293571e51bbe621a5c480e8a28e95/src/libstd/panicking.rs:271
  51: std::panic::catch_unwind
             at /rustc/032a53a06ce293571e51bbe621a5c480e8a28e95/src/libstd/panic.rs:394
  52: tokio::task::harness::Harness<T,S>::poll::{{closure}}
             at /home/alex/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-0.2.9/src/task/harness.rs:101
  53: tokio::loom::std::causal_cell::CausalCell<T>::with_mut
             at /home/alex/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-0.2.9/src/loom/std/causal_cell.rs:41
  54: tokio::task::harness::Harness<T,S>::poll
             at /home/alex/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-0.2.9/src/task/harness.rs:100
  55: tokio::task::raw::poll
             at /home/alex/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-0.2.9/src/task/raw.rs:162
  56: tokio::task::raw::RawTask::poll
             at /home/alex/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-0.2.9/src/task/raw.rs:113
  57: tokio::task::Task<S>::run
             at /home/alex/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-0.2.9/src/task/mod.rs:371
  58: tokio::task::local::Scheduler::tick
             at /home/alex/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-0.2.9/src/task/local.rs:513
  59: <tokio::task::local::LocalFuture<F> as core::future::future::Future>::poll::{{closure}}
             at /home/alex/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-0.2.9/src/task/local.rs:407
  60: tokio::task::local::Scheduler::with::{{closure}}
             at /home/alex/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-0.2.9/src/task/local.rs:478
  61: std::thread::local::LocalKey<T>::try_with
             at /rustc/032a53a06ce293571e51bbe621a5c480e8a28e95/src/libstd/thread/local.rs:262
  62: std::thread::local::LocalKey<T>::with
             at /rustc/032a53a06ce293571e51bbe621a5c480e8a28e95/src/libstd/thread/local.rs:239
  63: tokio::task::local::Scheduler::with
             at /home/alex/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-0.2.9/src/task/local.rs:474
  64: <tokio::task::local::LocalFuture<F> as core::future::future::Future>::poll
             at /home/alex/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-0.2.9/src/task/local.rs:402
  65: std::future::poll_with_tls_context::{{closure}}
             at /rustc/032a53a06ce293571e51bbe621a5c480e8a28e95/src/libstd/future.rs:121
  66: std::future::get_task_context
             at /rustc/032a53a06ce293571e51bbe621a5c480e8a28e95/src/libstd/future.rs:111
  67: std::future::poll_with_tls_context
             at /rustc/032a53a06ce293571e51bbe621a5c480e8a28e95/src/libstd/future.rs:121
  68: tokio::task::local::LocalSet::run_until::{{closure}}
             at /home/alex/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-0.2.9/src/task/local.rs:358
  69: <std::future::GenFuture<T> as core::future::future::Future>::poll::{{closure}}
             at /rustc/032a53a06ce293571e51bbe621a5c480e8a28e95/src/libstd/future.rs:43
  70: std::future::set_task_context
             at /rustc/032a53a06ce293571e51bbe621a5c480e8a28e95/src/libstd/future.rs:79
  71: <std::future::GenFuture<T> as core::future::future::Future>::poll
             at /rustc/032a53a06ce293571e51bbe621a5c480e8a28e95/src/libstd/future.rs:43
  72: tokio::runtime::basic_scheduler::BasicScheduler<P>::block_on
             at /home/alex/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-0.2.9/src/runtime/basic_scheduler.rs:138
  73: tokio::runtime::Runtime::block_on::{{closure}}
             at /home/alex/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-0.2.9/src/runtime/mod.rs:411
  74: tokio::runtime::context::enter
             at /home/alex/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-0.2.9/src/runtime/context.rs:72
  75: tokio::runtime::handle::Handle::enter
             at /home/alex/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-0.2.9/src/runtime/handle.rs:33
  76: tokio::runtime::Runtime::block_on
             at /home/alex/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-0.2.9/src/runtime/mod.rs:408
  77: tokio::task::local::LocalSet::block_on
             at /home/alex/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-0.2.9/src/task/local.rs:321
  78: actix_rt::runtime::Runtime::block_on
             at /home/alex/.cargo/git/checkouts/actix-net-8b378701d4b3767e/602db17/actix-rt/src/runtime.rs:89
  79: actix_rt::builder::SystemRunner::run
             at /home/alex/.cargo/git/checkouts/actix-net-8b378701d4b3767e/602db17/actix-rt/src/builder.rs:164
  80: testlib::actix_utils::ShutdownableThread::start::{{closure}}
             at test-utils/testlib/src/actix_utils.rs:20
```

### PR DESCRIPTION
**Pull request by nearmax**
Fixes #2208

### CODE REVIEW

File: runtime/runtime/src/lib.rs [hunk 1]
```diff
@@ -1166,8 +1166,10 @@ impl Runtime {
                     state_update.set(TrieKey::ContractData { key: data_key, account_id }, value);
                 }
                 StateRecord::Contract { account_id, code } => {
+                    let acc = get_account(&state_update, &account_id).expect("Failed to read state").expect("Code state record should be preceded by the corresponding account record");
```
Comment (evgenykuzyakov) [inline runtime/runtime/src/lib.rs:1169]: This line looks long. Do you know if the fmt doesn't work.
