### PR TITLE
fix(rpc): Fix returning missing tx error

### LINKED ISSUE #2488: Tx status timeouts when transaction is missing
Currently if transaction is missing, there is no error from `tx` RPC endpoint.

Steps to reproduce
---
1. Start local node
2. Run:
```
http post http://localhost:3030/ jsonrpc=2.0 id=123 method=tx params:='["11111111111111111111111111111111", "test0"]'
```
Observe:
```
{
    "error": {
        "code": -32000,
        "data": "Timeout",
        "message": "Server error"
    },
    "id": "123",
    "jsonrpc": "2.0"
}
```

Implementation, if the node is tracking the shard on which this account is - if it's not found we should return right away here with an not found error https://github.com/nearprotocol/nearcore/blob/5254f85c70ab6413b796a69b452a12a923750d9f/chain/client/src/view_client.rs#L219

From #2039

### PR DESCRIPTION
**Pull request by ilblackdragon**
Return if tx status is missing on the node that track this shard. Fixes #2488 

CC @frol `tx` rpc actually is not having proper typed errors. I'm not fixing it here, but it's worth reviewing that.

Test Plan
----
Add a test that for a single node if query missing transaction, it returns error right away instead of Timeout.

### CODE REVIEW

File: chain/client/src/view_client.rs [hunk 1]
```diff
@@ -213,64 +217,87 @@ impl ViewClientActor {
...
-                        if self.chain.get_chunk_extra(&head.last_block_hash, dst_shard_id).is_err()
-                        {
-                            if Self::need_request(
-                                receipt_view.id,
-                                &mut self.receipt_outcome_requests,
-                            ) {
-                                let validator = self
+        let target_shard_id = self.runtime_adapter.account_id_to_shard_id(&signer_account_id);
+        // Check if we are tracking this shard.
+        println!(
```
Comment (bowenwang1996) [inline chain/client/src/view_client.rs:223]: should this be removed?

File: chain/jsonrpc/src/lib.rs [hunk 2]
```diff
@@ -245,18 +245,22 @@ impl JsonRpcHandler {
...
+                match tx_status_result {
+                    Ok(Ok(Some(ref tx_result))) => match tx_result.status {
                         FinalExecutionStatus::Started | FinalExecutionStatus::NotStarted => {}
                         FinalExecutionStatus::Failure(_)
                         | FinalExecutionStatus::SuccessValue(_) => {
-                            break jsonify(final_tx);
+                            break jsonify(tx_status_result);
                         }
+                    },
+                    Ok(Err(ref _err)) => {
```
Comment (bowenwang1996) [inline chain/jsonrpc/src/lib.rs:260]:
```suggestion
                    Ok(Err(_)) => {
```

**Comment by ilblackdragon** [comment]
@bowenwang1996 Just fixed `send_tx_commit` by having 2 functions. We can probably make this cleaner later.
