### PR TITLE
fix(chain): node should not crash when seal is already produced

### LINKED ISSUE #2785: Node crash on "seal should be already produced"
It is reported that a validator's node crashed on betanet on the this line https://github.com/nearprotocol/nearcore/blob/7eccdd76ef13f51d0bd0051532543168475458f7/chain/chunks/src/lib.rs#L275.

### PR DESCRIPTION
**Pull request by bowenwang1996**
Currently a node can crash if when it receives a partial encoded chunk, the corresponding demur is no longer active. This can be caused by, for example, a node receiving a partial encoded chunk 30 seconds after requesting it. Fixes #2785.

Test plan
----------
Expensive test `test_seal_removal` that tests the scenario mentioned above.

### CODE REVIEW

**Comment by frol** [comment]
Deployed this PR as a hot-fix to betanet, see #2785.

https://buildkite.com/nearprotocol/nearcore-private/builds/11#dcd2d1b1-bea3-49a4-9005-4cf2f04071dd

File: chain/chunks/src/lib.rs [hunk 1]
```diff
@@ -272,8 +273,9 @@ impl SealsManager {
     }
 
     fn approve_chunk(&mut self, chunk_hash: &ChunkHash) {
-        let seal = self.active_demurs.remove(chunk_hash).expect("seal should be already produced");
-        Self::insert_past_seal(&mut self.past_seals, seal.height, chunk_hash.clone());
+        if let Some(seal) = self.active_demurs.remove(chunk_hash) {
```
Comment (birchmd) [inline chain/chunks/src/lib.rs:276]: Of course! It is no longer true that the active demur will necessarily be there when the chunk is reconstructed because it may have expired and moved into the past seals. I should have removed the `expect` in the original PR.

I think it is good to check that there is an entry in `past_seals` though, since this would be the case if the demur expired recently. Please see https://github.com/nearprotocol/nearcore/pull/2788

File: chain/chunks/src/lib.rs [hunk 2]
```diff
@@ -1416,6 +1423,82 @@ mod test {
         assert!(network_adapter.requests.read().unwrap().is_empty());
     }
 
+    #[cfg(feature = "expensive_tests")]
+    #[test]
+    fn test_seal_removal() {
```
Comment (birchmd) [inline chain/chunks/src/lib.rs:1428]: Do we need an expensive test for this? Seems like a unit test would accomplish it just as well.
