### PR TITLE
fix(chain): drop blocks that are too far in the future

### LINKED ISSUE #2418: Dropping blocks that are too far in the future
Currently we observe a lot of cpu usage when the node is doing block sync, as described in #2380. This is partially caused by the orphan pool getting overwhelmed with latest blocks and when the orphan pool is full, the node stops rejecting rebroadcast blocks because orphan pool removes blocks from largest height, which means that a lot of cpu is spent on adding blocks to and removing blocks from the orphan pool, which isn't a constant time operation (in terms of orphan pool size). One way to address this problem is to drop blocks are that too far in the future so that the orphan pool wouldn't be overwhelmed during block sync.

### PR DESCRIPTION
**Pull request by bowenwang1996**
Fixes two issues:
1. Orphan pool getting overwhelmed during syncing and burns a lot of unnecessary cpu cycles. Resolves #2418.
2. We currently don't explicitly request sync block and relies on orphan sync to get to it. This means that state sync might be slow when epoch length is large (40k in practice).

Test plan
---------
It is hard to test the changes here as what is fixed here is mostly performance rather than correctness. I tested syncing with betanet and it worked well, whereas before this change the node would get stuck in state sync with high cpu usage.

### CODE REVIEW

File: chain/client/src/client_actor.rs [hunk 1]
```diff
@@ -1088,8 +1096,12 @@ impl ClientActor {
                                 highest_height_peer(&self.network_info.highest_height_peers)
                             {
                                 if let Ok(header) = self.client.chain.get_block_header(&sync_hash) {
-                                    let prev_hash = header.prev_hash;
-                                    self.request_block_by_hash(prev_hash, peer_info.peer_info.id);
+                                    for hash in vec![header.prev_hash, header.hash].into_iter() {
```
Comment (mfornet) [inline chain/client/src/client_actor.rs:1099]: Why do you need to fetch `header.hash` at this point. AFAIU to sync state you only need to fetch `header.prev_hash` and `header.hash` will be requested while catching up. 

This still makes sense since we know we shortly will be requesting such block anyway, just want to be sure if it is a simple performance update, or if it is related somehow to the goal of the PR.

Comment (bowenwang1996) [reply chain/client/src/client_actor.rs:1099]: See my PR description.

**Comment by bowenwang1996** [comment]
@SkidanovAlex see my PR description
