### PR TITLE
Fixes #771: Correct death row tracking in Trie

### LINKED ISSUE #771: Storage removes fails when there is no key
```
[2019-03-25T16:54:30Z INFO  client] Genesis root: `GuxpthaWdJEaxKyKhr5NwTCmScL1ZX1ArMWzTXBBtzgr`
[2019-03-25T16:54:30Z INFO  coroutines::client_task] Producing block for account_id="alice.near", index 1123
Failed to lookup key=0'0'7'3'7'4'7'5'6'4'6'9'6'f'2'd'6'8'3'6'6'1'6'f'6'1'7'4'3'7'6'a'6'3'2'c'6'4'3'a'3'a'3'3 for root=`DE7dTcZG1aEf4X6wKBYtkD8JdUqpPkgBWXspJqHyNkc3`: Node 3SQT711RN8H2oYfTns94ig26PHVBVWTYSJdHnCD3Bwp6 not found in storage
[2019-03-25T16:54:30Z DEBUG node_runtime] LOG: Front: {"sender":null,"text":null}
thread 'tokio-runtime-worker-1' panicked at 'Failed to remove element: "Node 3SQT711RN8H2oYfTns94ig26PHVBVWTYSJdHnCD3Bwp6 not found in storage"', src/libcore/result.rs:997:5
note: Run with `RUST_BACKTRACE=1` environment variable to display a backtrace.
```

DB Storage: https://drive.google.com/open?id=1WjLp8Zwan-bWqGdRMTt8zqJGBjfyqVqb

Reproduces at master.

### PR DESCRIPTION
**Pull request by ilblackdragon**
Added a tool to replay blockchain from another storage:
```
cargo run --package devnet -- --replay-storage=issue771
```

### CODE REVIEW

File: core/storage/src/trie/mod.rs [hunk 1]
```diff
@@ -391,41 +391,39 @@ impl Trie {
         hash: Option<CryptoHash>,
         partial: NibbleSlice,
         death_row: &mut HashMap<CryptoHash, u32>,
-    ) -> Result<Option<TrieNode>, String> {
+    ) -> Result<(Option<TrieNode>, bool), String> {
```
Comment (evgenykuzyakov) [inline core/storage/src/trie/mod.rs]: Would be nice to add a comment to delete about return value. It's not clear what bool means, especially since there is an option as well.

**Comment by ilblackdragon** [comment]
Also fixes #359

**Comment by ilblackdragon** [comment]
## Benchmarks

Old:
```
test storage_save_block     ... bench:     235,397 ns/iter (+/- 57,695)
test storage_save_get_block ... bench:       2,050 ns/iter (+/- 254)
test trie_lookup ... bench:     602,977 ns/iter (+/- 67,755)
test trie_update ... bench:     400,528 ns/iter (+/- 41,677)
```

New:
```
running 2 tests
test storage_save_block     ... bench:     238,959 ns/iter (+/- 120,344)
test storage_save_get_block ... bench:       2,079 ns/iter (+/- 549)
test trie_lookup ... bench:     632,620 ns/iter (+/- 67,178)
test trie_update ... bench:     478,058 ns/iter (+/- 64,510)
```

A bit slower update as requires more lookups to keep track of reference counters.
