### PR TITLE
Fixes #697: fix importing blocks out of order

### LINKED ISSUE #697: Receiving block from future crashes client
Example unit test (going into client.rs) that crashes:
```
    #[test]
    fn test_block_catchup() {
        let (chain_spec, signer) = generate_test_chain_spec();
        let client = get_client_from_cfg(&chain_spec, signer);

        let blocks = make_coupled_blocks(&client.beacon_chain.chain.best_block(), &client.shard_client.chain.best_block(), 10);
        client.try_import_blocks(blocks[9].0.clone(), blocks[9].1.clone());
    }
```

### PR DESCRIPTION
**Pull request by ilblackdragon**
Removed incorrect condition in importing block, added block importing unit test to Client, some test tools to produce correct blocks

### CODE REVIEW

File: node/client/src/lib.rs [hunk 1]
```diff
@@ -166,11 +166,6 @@ impl Client {
             vec![]
         } else {
             let best_index = self.beacon_chain.chain.best_index();
-            let max_pending_index = guard.values().map(SignedBlock::index).max().unwrap();
```
Comment (nearmax) [inline node/client/src/lib.rs]: This seems like a reasonable check, why was it removed?

Comment (nearmax) [reply node/client/src/lib.rs]: Upd: Check was wrong. I added actual removal of outdated pending blocks.

**Comment by nearmax** [comment]
> Where is the fix?

The assert was wrong.
