### PR TITLE
fix(network): Avoid peers connecting to itself.

### LINKED ISSUE #2601: Node keeps trying to connect to itself
**Describe the bug**
Node keep reporting that keep connecting to itself and report warning that it received info about itself.

```
May 02 11:38:10.788  WARN network: Received info about itself. Disconnecting this peer.
May 02 11:38:10.849  WARN network: Received info about itself. Disconnecting this peer.
May 02 11:38:11.092  WARN network: Received info about itself. Disconnecting this peer.
May 02 11:38:12.644  WARN network: Received info about itself. Disconnecting this peer.
```

**Expected behavior**
At most this happens once, ideally doesn't happen at all, because we shouldn't be sending our peer info to ourselves and should determine that peerId is ours and not include it into peer table.

### PR DESCRIPTION
**Pull request by mfornet**
If a node receives info about itself from other nodes
it was possible it tries to establish connection with itself.

Fix #2601

### CODE REVIEW

**Comment by mfornet** [comment]
@bowenwang1996 using `ignore_fn` to filter out peers we don't want to connect to, since it is more expressive and more efficient.

File: chain/network/src/peer_manager.rs [hunk 1]
```diff
@@ -673,9 +674,13 @@ impl PeerManagerActor {
         }
 
         if self.is_outbound_bootstrap_needed() {
-            let mut ignore_list = self.outgoing_peers.clone();
-            ignore_list.insert(self.peer_id.clone());
-            if let Some(peer_info) = self.sample_random_peer(&ignore_list) {
+            if let Some(peer_info) = self.sample_random_peer(|peer_state| {
+                // Ignore connecting to ourself
+                self.peer_id == peer_state.peer_info.id
+                    || self.config.addr == peer_state.peer_info.addr
```
Comment (ilblackdragon) [inline chain/network/src/peer_manager.rs:680]: I don't understand why `self.peer_id` wasn't enough actually? is it possible that address is the same but id is different?...

Comment (mfornet) [reply chain/network/src/peer_manager.rs:680]: It is possible when we change peer_id. We learn about our previous version that is still stored by other nodes in the network. This can happen on network updates if we nuke `~/.near` folder

File: chain/network/tests/peer_handshake.rs [hunk 2]
```diff
@@ -209,5 +209,12 @@ fn check_connection_with_new_identity() {
     runner.push(Action::CheckRoutingTable(0, vec![(1, vec![1])]));
     runner.push(Action::CheckRoutingTable(1, vec![(0, vec![0])]));
 
+    runner.push(Action::Wait(2000));
+
+    // Check the no node tried to connect to itself in this process.
+    runner.push_action(wait_for(|| {
```
Comment (bowenwang1996) [inline chain/network/tests/peer_handshake.rs:215]: Is there a better way to do this? I am not a fan of adding a counter just for testing purposes.

Comment (mfornet) [reply chain/network/tests/peer_handshake.rs:215]: This counter is indeed somehow "useful", since it is still possible you try to connect to yourself in very weird situations (more likely because you have some complex network setup and reset your node with a new PeerID).

Other approach to test this are quite involved. For example we need to store an integer/boolean in state to know whether we tried to request info to ourself, and create Actix Message Response to query PeerManagerActor for this information. 

I think it will introduce some extra unnecessary complexity. I'm not fan either of using counters for testing, but in this case, I think it is not a bad idea. One option is to hide that counter behind a flag, but I still don't think we should go that far for something this simple.

File: core/metrics/src/lib.rs [hunk 3]
```diff
@@ -126,6 +126,15 @@ pub fn inc_counter(counter: &Result<IntCounter>) {
     }
 }
 
+pub fn get_counter(counter: &Result<IntCounter>) -> std::result::Result<i64, ()> {
```
Comment (bowenwang1996) [inline core/metrics/src/lib.rs:129]: Why not do `Result<i64, String>`

File: chain/network/tests/peer_handshake.rs (hunk 2 above)
Comment (bowenwang1996) [reply chain/network/tests/peer_handshake.rs:215]: Okay I cannot think of a better way either.
