### PR TITLE
fix: Use handshake version 2

### LINKED ISSUE #3136: handshake.py consistently fails
E.g http://52.149.162.182:3000/#/test/7636

### PR DESCRIPTION
**Pull request by mfornet**
This change is only backward compatible with branch latest_supported_version, 
**We must merge and deploy that branch first.**

Fixes #3136 

Test plan
=========

1. Check latest_supported_version_2 branch is backward compatible with
latest_supported_version branch.

    Run `backward.py` with `main(near_root, "latest_supported_version", "latest_supported_version_2")` and check it passes.

2. `handshake.py` pass

### CODE REVIEW

File: chain/network/src/types.rs [hunk 1]
```diff
@@ -199,12 +199,33 @@ pub struct HandshakeV2 {
...
+
+impl From<Handshake> for HandshakeV2 {
+    fn from(handshake_old: Handshake) -> Self {
         Self {
-            // In the transition to the new version, we care about the oldest supported version
-            // by the other node.
-            version: handshake_old.oldest_supported_version,
+            // In previous version of handshake, nodes usually sent the oldest supported version instead of their current version.
+            // Computing the current version of the other as the oldest version plus 4, but not letting go bigger than 33.
+            version: std::cmp::min(33, handshake_old.version.saturating_add(4)),
```
Comment (bowenwang1996) [inline chain/network/src/types.rs:227]: Instead of using a hardcoded number, we should use a constant instead. This way in case the protocol version on master changes before this PR is merged, this code will still work

Comment (mfornet) [reply chain/network/src/types.rs]: Done

**Comment by mfornet** [comment]
> Please run a nayduck run and link here

http://nayduck.eastus.cloudapp.azure.com:3000/#/run/281

File: chain/network/src/types.rs [hunk 2]
```diff
@@ -199,12 +199,33 @@ pub struct HandshakeV2 {
...
+
+impl From<Handshake> for HandshakeV2 {
+    fn from(handshake_old: Handshake) -> Self {
         Self {
-            // In the transition to the new version, we care about the oldest supported version
-            // by the other node.
-            version: handshake_old.oldest_supported_version,
+            // In previous version of handshake, nodes usually sent the oldest supported version instead of their current version.
+            // Computing the current version of the other as the oldest version plus 4, but not letting go bigger than 33.
+            version: std::cmp::min(PROTOCOL_VERSION - 1, handshake_old.version.saturating_add(4)),
```
[the remark this answers is not in the document]
Comment (mfornet) [reply chain/network/src/types.rs]: The idea is that this changes with as the `PROTOCOL_VERSION` changes. This conversion will only be relevant during the transition from Handshake to HandshakeV2, since we were previously sending oldest supported version, we are predicting its version as `oldest_supported_version+1`, but we know for sure they should be at least one version lower than current version.

File: chain/network/src/types.rs [hunk 3]
```diff
@@ -199,12 +199,92 @@ pub struct HandshakeV2 {
...
+                _ => HandshakeV2AutoDes::deserialize(buf).map(Into::into),
+            }
+        } else {
+            // Consume the remainder of the buffer
+            // NOTE: It is important that HandshakeV2 only appears in the end of a message
+            // to be deserialized properly.
+            *buf = &buf[buf.len()..];
+
+            // If we don't support this version, create a mock HandshakeV2 with version values,
+            // and let `PeerActor` send message:
```
[the remark this answers is not in the document]
Comment (mfornet) [reply chain/network/src/types.rs:265]: Here we convert a handshake with not supported version into a HandshakeFailure

https://github.com/nearprotocol/nearcore/blob/ca592796b005702ddb46a3aff051ef52450353ec/chain/network/src/peer.rs#L670

Notice that prior this change, the client will fail to deserialize the message and would not respond to such input. The contract of deserializer, is that if we are able to deserialize the HandshakeV2 we do it as expected, otherwise, if we detect that the version is not supported we create a HandshakeV2 but only populate the fields `version`, `oldest_supported_version` and mock the remaining fields. So basically, fields from HandshakeV2 are only reliable if HandshakeV2.version is supported.

I agree this API feels somehow hacky, but the other alternative to avoid double upgrades and support this feature is relay on custom error `std::io::Result::Error::Custom(VersionNotSupported)`. Probably this is a better (less hacky) approach from a semantic point of view. I'm ok doing it this way.

[the remark this answers is not in the document]
Comment (bowenwang1996) [reply chain/network/src/types.rs:265]: > Probably this is a better (less hacky) approach from a semantic point of view. I'm ok doing it this way.

Yeah I agree

**Review by bowenwang1996 — APPROVED** [review]
Approving to unblock #3283

File: chain/network/src/peer.rs [hunk 4]
```diff
@@ -139,6 +141,9 @@ pub struct Peer {
     pub peer_type: PeerType,
     /// Peer status.
     pub peer_status: PeerStatus,
+    /// Protocol version to communicate with this peer.
+    /// None denotes latest protocol version.
```
Comment (bowenwang1996) [inline chain/network/src/peer.rs:145]: how is "latest protocol version" defined? why don't we just keep the number?

Comment (mfornet) [reply chain/network/src/peer.rs:145]: removed the option

File: chain/network/src/types.rs (hunk 3 above)
[the remark this answers is not in the document]
Comment (mfornet) [reply chain/network/src/types.rs]: done

File: chain/network/src/peer.rs (hunk 4 above)
Comment (bowenwang1996) [inline chain/network/src/peer.rs:145]: Comment is still wrong

File: chain/network/src/peer.rs [hunk 5]
```diff
@@ -605,10 +611,36 @@ impl StreamHandler<Result<Vec<u8>, ReasonForBan>> for Peer {
...
         self.tracker.increment_received(msg.len() as u64);
+
         let mut peer_msg = match bytes_to_peer_message(&msg) {
             Ok(peer_msg) => peer_msg,
             Err(err) => {
-                info!(target: "network", "Received invalid data {:?} from {}: {}", msg, self.peer_info, err);
+                if let Some(version) = err
+                    .get_ref()
+                    .map(|err| err.downcast_ref::<HandshakeFailureReason>())
+                    .flatten()
```
Comment (bowenwang1996) [inline chain/network/src/peer.rs:621]: maybe it's makes sense to use `flat_map`?

**Review by bowenwang1996 — APPROVED** [review]

**Comment by bowenwang1996** [comment]
@mfornet looks like upgradability test failed

File: chain/network/src/peer.rs (hunk 5 above)
Comment (mfornet) [reply chain/network/src/peer.rs:621]: done, it is called `and_then` in rust, just discovered them :)

File: chain/network/src/peer.rs (hunk 4 above)
Comment (mfornet) [reply chain/network/src/peer.rs:145]: fixed

**Comment by mfornet** [comment]
Both `buildkite/nearcore/backward-compatible` and `buildkite/nearcore/upgradable` are failing because, the `stable_version` that is being downloaded as `beta` is too old (version 31) vs expected beta (version 34).

It is downloading binary from: https://s3-us-west-1.amazonaws.com/build.nearprotocol.com/nearcore/
Tested locally with current beta, and it is working.

File: chain/network/src/types.rs [hunk 6]
```diff
@@ -206,6 +225,50 @@ impl Handshake {
...
+                ERROR_UNEXPECTED_LENGTH_OF_INPUT,
+            ));
+        }
+
+        let version = u32::from_le_bytes(buf[..4].try_into().unwrap());
+
+        if OLDEST_BACKWARD_COMPATIBLE_PROTOCOL_VERSION <= version && version <= PROTOCOL_VERSION {
+            // If we support this version, then try to deserialize with custom deserializer
+            match version {
+                _ => HandshakeAutoDes::deserialize(buf).map(Into::into),
```
Comment (bowenwang1996) [inline chain/network/src/types.rs:245]: this match doesn't do anything and should just be removed

Comment (mfornet) [reply chain/network/src/types.rs:245]: It was as a signal for future versions to use custom deserializers, but probably it won't be used anyway in the current design!
