### PR TITLE
fix(store): Fix ColTransactions and ColReceiptIdToShardId

### LINKED ISSUE #3247: investigate database migration failure
During a migration from database version 6 to version 7 (which changes transaction and receipt refcounting), many nodes on betanet failed with number of transactions in `ColTransaction` not matching the number of refcounts in `ColTransactionRefCount`, which indicates an inconsistency in the storage. We should investigate such failure and prevent it from happening again.

### PR DESCRIPTION
**Pull request by mikhailOK**
Fix inconsistencies between code that writes to storage and gc.

ColTransactions:
one value per transaction per chunk in ColChunks
ColReceiptIdToShardId:
one value per receipt per record in ColOutgoingReceipts

Add a store migration that doesn't change the format, but recomputes
these columns.

Fixes #3247, #2930.

Test plan
---------
re-enable chunk_tx_exists in store-validator

### CODE REVIEW

File: core/store/src/migrations/v8_to_v9.rs [hunk 1]
```diff
@@ -0,0 +1,88 @@
...
+pub(crate) fn repair_col_transactions(store: &Store, store_update: &mut StoreUpdate) {
+    let mut tx_refcount: HashMap<CryptoHash, (SignedTransaction, i64)> = HashMap::new();
+    for tx in store
+        .iter(DBCol::ColChunks)
+        .map(|(_key, value)| {
+            ShardChunk::try_from_slice(&value).expect("BorshDeserialize should not fail")
+        })
+        .flat_map(|chunk: ShardChunk| chunk.transactions)
+    {
+        tx_refcount.entry(tx.get_hash()).and_modify(|(_, rc)| *rc += 1).or_insert((tx, 1));
```
Comment (bowenwang1996) [inline core/store/src/migrations/v8_to_v9.rs:68]: This could potentially use too much memory

File: chain/chain/src/store.rs [hunk 2]
```diff
@@ -2211,13 +2212,45 @@ impl<'a> ChainStoreUpdate<'a> {
...
+                    let key: Vec<u8> = receipt_id.into();
+                    store_update.update_refcount(ColReceiptIdToShardId, &key, &[], -1);
+                    self.chain_store.receipt_id_to_shard_id.cache_remove(&key);
+                    self.inc_gc(ColReceiptIdToShardId);
+                }
+            }
+            Err(error) => {
+                match error.kind() {
+                    ErrorKind::DBNotFoundErr(_) => {
+                        // Sometimes we don't save outgoing receipts. See the usages of save_outgoing_receipt.
```
Comment (bowenwang1996) [inline chain/chain/src/store.rs:2231]: where do we save receipt_id_to_shard_id but not outgoing_receipts?

**Review by bowenwang1996 — COMMENTED** [review]
Can we test that 1) the repair works on real data and 2) the migration wouldn't cause the node to run out of memory?

File: chain/chain/src/store.rs (hunk 2 above)
Comment (mikhailOK) [reply chain/chain/src/store.rs:2231]: after this change they match

File: core/store/src/migrations/v8_to_v9.rs (hunk 1 above)
Comment (mikhailOK) [reply core/store/src/migrations/v8_to_v9.rs:68]: How big is ColTransactions on testnet?

Comment (frol) [reply core/store/src/migrations/v8_to_v9.rs:68]: @mikhailOK is there a tool we can run to learn that? Explorer shows 56k transactions on testnet (it seems that our archival nodes do not contain the blocks when benchmark loading was performed), but betanet has 11 million transactions.

File: chain/chain/src/store.rs (hunk 2 above)
Comment (bowenwang1996) [reply chain/chain/src/store.rs:2231]: I see

File: core/store/src/migrations/v8_to_v9.rs (hunk 1 above)
Comment (bowenwang1996) [reply core/store/src/migrations/v8_to_v9.rs:68]: We can get the data from an archival nodes on both testnet and betanet to see if the migration works. But note that the last time migration failed on testnet, it did fail on some nodes because of oom.

Comment (mikhailOK) [reply core/store/src/migrations/v8_to_v9.rs:68]: No tool, but we can test this change on a copy of the largest storage. 11 million should be ok

Comment (mikhailOK) [reply core/store/src/migrations/v8_to_v9.rs:68]: last time it was ColState, ColTransactions should be smaller

**Review by bowenwang1996 — COMMENTED** [review]
EDIT: nvm

**Review by bowenwang1996 — APPROVED** [review]
