### PR TITLE
Proper check for transaction history validation

### LINKED ISSUE #1386: `check_tx_history` doesn't check the hash is on the chain
Thus, replay protection doesn't work currently.

### PR DESCRIPTION
**Pull request by bowenwang1996**
Fixes #1386 by maintaining a cache of the block headers in the current fork.

### CODE REVIEW

File: chain/chain/src/store.rs [hunk 1]
```diff
@@ -234,6 +254,62 @@ impl ChainStore {
...
+        let cur_block_header = cur_header.clone();
+        let mut found_base_block_hash = false;
+        for _ in 0..max_difference_in_height {
+            let front = if let Some(elem) = self.header_history.queue.front() {
+                elem.clone()
+            } else {
+                break;
+            };
+            if front == cur_block_header.hash {
+                found_base_block_hash = true;
```
Comment (SkidanovAlex) [inline chain/chain/src/store.rs]: `found_cur_block_hash`

File: chain/chain/src/store.rs [hunk 2]
```diff
@@ -234,6 +254,62 @@ impl ChainStore {
...
+            } else {
+                self.header_history.queue.pop_front();
+                self.header_history.headers.remove(&front);
+            }
+        }
+        if found_base_block_hash && self.header_history.headers.contains_key(base_block_hash) {
+            return true;
+        }
+        if !found_base_block_hash {
+            self.header_history.headers.insert(cur_block_header.hash, cur_block_header.clone());
```
Comment (SkidanovAlex) [inline chain/chain/src/store.rs]: erase the queue to be sure?

File: chain/chain/src/store.rs [hunk 3]
```diff
@@ -234,6 +254,62 @@ impl ChainStore {
             }
         }
     }
+
+    pub fn check_blocks_on_same_chain(
```
Comment (SkidanovAlex) [inline chain/chain/src/store.rs]: Can we simplify it and only store the head and the set of blocks, and invalidate it if the head doens't match `cur_header`?

File: chain/chain/src/store.rs [hunk 4]
```diff
@@ -56,6 +56,61 @@ pub struct StateSyncInfo {
...
+    /// Update the cache. `hash` must exists in the current cache. Remove everything before `hash`
+    /// and replace them with `new_list`. `new_list` must contain contiguous block headers, ordered
+    /// from higher height to lower height.
+    fn update(&mut self, hash: &CryptoHash, new_list: Vec<BlockHeader>) {
+        assert!(self.headers.contains_key(hash));
+        loop {
+            let front = if let Some(elem) = self.queue.front() {
+                elem.clone()
+            } else {
+                break;
```
Comment (SkidanovAlex) [inline chain/chain/src/store.rs]: assert!(false) before breaking?

File: chain/chain/src/store.rs [hunk 5]
```diff
@@ -234,6 +292,58 @@ impl ChainStore {
...
+                    header.clone()
+                } else {
+                    return false;
+                };
+                if self.header_history.contains(&cur_block_header.hash) {
+                    self.header_history.update(&cur_block_header.hash, header_list);
+                    break;
+                }
+                cur_block_hash = cur_block_header.inner.prev_hash;
+                header_list.push(cur_block_header);
```
Comment (SkidanovAlex) [inline chain/chain/src/store.rs]: After the first iteration you get the invariant

`header_list = [cur_header, cur_header]`

I'm pretty sure it's not intended?

File: chain/chain/src/store.rs [hunk 6]
```diff
@@ -234,6 +292,58 @@ impl ChainStore {
...
+            }
+        }
+
+        // second step: check if `base_block_hash` exists
+        if self.header_history.contains(base_block_hash) {
+            return true;
+        }
+        let num_to_fetch = max_difference_in_height - self.header_history.len() as u64;
```
Comment (SkidanovAlex) [inline chain/chain/src/store.rs]: This will crash with underflow if the chain you just updated with was longer than the chain you already had in the history

File: chain/chain/src/store.rs (hunk 5 above)
Comment (SkidanovAlex) [reply chain/chain/src/store.rs]: My statement appears to be wrong. It's just confusing naming.
`cur_block_hash` should be `prev_block_hash` (and correpondingly `cur_block_header` in the inner loop should be `prev_block_header`)

File: chain/chain/src/store.rs [hunk 7]
```diff
@@ -234,6 +314,73 @@ impl ChainStore {
...
+                    header.clone()
+                } else {
+                    return false;
+                };
+                if self.header_history.contains(&prev_block_header.hash) {
+                    self.header_history.update(&prev_block_header.hash, header_list.clone());
+                    find_ancestor = true;
+                    break;
+                }
+                self.header_history.pop_front();
```
Comment (SkidanovAlex) [inline chain/chain/src/store.rs]: This should be before we `update`.

File: chain/chain/src/store.rs [hunk 8]
```diff
@@ -234,6 +314,73 @@ impl ChainStore {
...
+            if !find_ancestor {
+                self.header_history = HeaderList::from_headers(header_list);
+            }
+        }
+
+        // second step: check if `base_block_hash` exists
+        if self.header_history.contains(base_block_hash) {
+            return true;
+        }
+        assert!(max_difference_in_height >= self.header_history.len() as u64);
```
Comment (SkidanovAlex) [inline chain/chain/src/store.rs]: As discussed offline, the misplaced `pop_front` above can result in this assert triggering.
Move the assert above the conditional return above, and make sure there are tests that trigger it, before fixing the `pop_front`.

File: chain/chain/src/store.rs [hunk 9]
```diff
@@ -234,6 +328,74 @@ impl ChainStore {
...
+            let mut find_ancestor = false;
+            while !self.header_history.is_empty() {
+                let prev_block_header = if let Ok(header) = self.get_block_header(&prev_block_hash)
+                {
+                    header.clone()
+                } else {
+                    return false;
+                };
+                self.header_history.pop_front();
+                if self.header_history.update(&prev_block_header.hash, header_list.clone()) {
```
Comment (SkidanovAlex) [inline chain/chain/src/store.rs]: Cloning the headerlist every time makes the complexity here quadratic.
Consider my comment above
