### PR TITLE
fix: use fraction in configs

### LINKED ISSUE #1747: Use rational numbers for percentages in `GenesisConfig`
We should use rational numbers for the following:
`developer_reward_percentage`, `protocol_reward_percentage`, and `max_inflation_rate`.

It is much harder to upgrade the code than the value of the `GenesisConfig`. Therefore we should not rely on the fact that we can easily make `developer_reward_percentage`, `protocol_reward_percentage`, and `max_inflation_rate` rational in the future and instead do it now.

### PR DESCRIPTION
**Pull request by bowenwang1996**
Use rational numbers for `protocol_reward_percentage`, `developer_reward_percentage`, `gas_price_adjustment_rate`, and `max_inflation_rate` to allow us fine tune those parameters. Resolves #1747.

Test plan
---------
Tests & migration script pass.

### CODE REVIEW

File: neard/src/config.rs [hunk 1]
```diff
@@ -110,8 +111,8 @@ pub const MIN_GAS_PRICE: Balance = 5000;
 pub const GAS_PRICE_ADJUSTMENT_RATE: u8 = 1;
 
 /// Rewards
-pub const PROTOCOL_PERCENT: u8 = 10;
-pub const DEVELOPER_PERCENT: u8 = 30;
+pub const PROTOCOL_PERCENT: Fraction = Fraction { numerator: 1, denominator: 10 };
```
Comment (SkidanovAlex) [inline neard/src/config.rs:114]: it's no longer percent, it's a fraction now.

File: chain/epoch_manager/src/reward_calculator.rs [hunk 2]
```diff
@@ -25,16 +24,17 @@ impl RewardCalculator {
     ) -> (HashMap<AccountId, Balance>, Balance) {
         let mut res = HashMap::new();
         let num_validators = validator_block_chunk_stats.len();
-        let max_inflation = (U256::from(self.max_inflation_rate)
+        let max_inflation = (U256::from(self.max_inflation_rate.numerator)
             * U256::from(total_supply)
             * U256::from(self.epoch_length)
-            / (U256::from(100) * U256::from(self.num_blocks_per_year)))
+            / (U256::from(100)
```
Comment (evgenykuzyakov) [inline chain/epoch_manager/src/reward_calculator.rs:30]: Why not more it to fraction?

Comment (bowenwang1996) [reply chain/epoch_manager/src/reward_calculator.rs:30]: Move what to fraction?

Comment (bowenwang1996) [reply chain/epoch_manager/src/reward_calculator.rs]: Fixed

File: core/primitives/src/types.rs [hunk 3]
```diff
@@ -513,3 +514,44 @@ pub enum ValidatorKickoutReason {
...
 pub struct StateHeaderKey(pub ShardId, pub CryptoHash);
+
+/// Represents a rational number. This struct is used exclusively in configs so
+/// `u32` provides enough precision. Since we do not expect to have computation
+/// that returns a `Fraction`, there is no guarantee that it is an irreducible fraction.
+#[derive(Debug, Serialize, Deserialize, Hash, PartialEq, Eq, Clone, Copy)]
+pub struct Fraction {
+    pub numerator: u32,
+    pub denominator: u32,
+}
```
Comment (frol) [inline core/primitives/src/types.rs:525]: I know this is a small implementation, but have you considered using an existing crates https://crates.io/crates/num-rational and https://crates.io/crates/fraction/? :thinking:

If we still want to maintain this implementation ourselves, I want to suggest we move it into its own module as this `types.rs` is already big enough, and I suggest we only define types that represent the core blockchain types here (`Fraction` is a generic type).

File: runtime/near-runtime-fees/Cargo.toml [hunk 4]
```diff
@@ -14,3 +14,4 @@ Fees applied to near runtime encapsulated in a separate crate. Might merge it la
 
 [dependencies]
 serde = { version = "1.0", features = ["derive"] }
+near-primitives = { path = "../../core/primitives" }
```
Comment (frol) [inline runtime/near-runtime-fees/Cargo.toml:17]: I was under the impression that we deliberately avoided using most of our crates here as our dependencies mess brings in `near-crypto` and WASM contracts get into a broken state (or just gets too big?). @nearmax is this the case?

File: core/primitives/src/types.rs (hunk 3 above)
Comment (bowenwang1996) [reply core/primitives/src/types.rs:525]: We don't need most of the arithmetic operations so I prefer to have our own struct here.

File: runtime/near-runtime-fees/Cargo.toml (hunk 4 above)
Comment (nearmax) [reply runtime/near-runtime-fees/Cargo.toml:17]: Correct, we cannot do it here. Also, `near-runtime-fees` should be publishable to crates.io which means we can only have dependencies on the crates that are in crates.io

Comment (frol) [reply runtime/near-runtime-fees/Cargo.toml:17]: @bowenwang1996 Please, add a comment to this Cargo.toml, so we don't forget about this in the future.

Comment (frol) [reply runtime/near-runtime-fees/Cargo.toml:17]: @nearmax Do you think there is a way we can have a good test for this?

**Comment by bowenwang1996** [comment]
@frol @nearmax I think the fix is not that simple. We cannot just use something like https://github.com/rust-num/num-rational because it doesn't implement serde serialization traits. To do that we would have our own wrapper type, which then defeats the purpose of using a library to break the dependency.

**Comment by nearmax** [comment]
> @frol @nearmax I think the fix is not that simple. We cannot just use something like https://github.com/rust-num/num-rational because it doesn't implement serde serialization traits. To do that we would have our own wrapper type, which then defeats the purpose of using a library to break the dependency.

Have you tried using `serde` feature? https://github.com/rust-num/num-rational/blob/master/Cargo.toml#L18

**Comment by bowenwang1996** [comment]
@frol why do we need to derive `Default` on `Genesis`?

**Comment by frol** [comment]
@bowenwang1996 I believe, we use it in tests.

**Comment by bowenwang1996** [comment]
@frol hmm it is now impossible to use `Rational` directly since it doesn't implement `Default` and I cannot implement it either unless we use a wrapper type.

File: neard/src/config.rs [hunk 5]
```diff
@@ -368,8 +368,8 @@ impl Genesis {
             gas_price_adjustment_rate: GAS_PRICE_ADJUSTMENT_RATE,
             block_producer_kickout_threshold: BLOCK_PRODUCER_KICKOUT_THRESHOLD,
             validators,
-            developer_reward_percentage: DEVELOPER_PERCENT,
-            protocol_reward_percentage: PROTOCOL_PERCENT,
+            developer_reward_percentage: DEVELOPER_REWARD_RATE,
+            protocol_reward_percentage: PROTOCOL_REWARD_RATE,
```
Comment (frol) [inline neard/src/config.rs:372]: BTW, should this also become `*_rate`? And either way, it is a breaking change -- is this fine?

**Comment by frol** [comment]
> hmm it is now impossible to use Rational directly since it doesn't implement Default and I cannot implement it either unless we use a wrapper type.

There is already SmartDefault derive used for GenesisConfig, so you just mark those fields with the `#[default()]` attribute and pass the default value right there.

**Comment by bowenwang1996** [comment]
@frol thanks. But I still didn't find where in test this default is used.

**Comment by frol** [comment]
@bowenwang1996 https://github.com/nearprotocol/nearcore/blob/9016565fdf49c8fe37953a2df657d706ebf11850/neard/src/config.rs#L380

File: scripts/migrations/8-fraction.py [hunk 6]
```diff
@@ -0,0 +1,29 @@
...
+config = json.load(open(os.path.join(home, 'output.json')), object_pairs_hook=OrderedDict)
+
+assert config['protocol_version'] == 7
+
+config['protocol_version'] = 8
+config['gas_price_adjustment_rate'] = [1, 100]
+config['protocol_reward_percentage'] = [1, 10]
+config['developer_reward_percentage'] = [3, 10]
+config['max_inflation_rate'] = [1, 20]
+config['runtime_config']['transaction_costs']['burnt_gas_reward'] = [3, 10]
```
Comment (frol) [inline scripts/migrations/8-fraction.py:27]: It is fine now, but I want to rise some awareness, that we need to avoid this overriding style in the future, right? (we don't want to override any existing settings with just default values)

Also, should we remove `protocol_reward_percentage`?

Comment (bowenwang1996) [reply scripts/migrations/8-fraction.py:27]: What do you suggest instead of overriding?
> Also, should we remove protocol_reward_percentage?
Why?

File: core/chain-configs/src/genesis_config.rs [hunk 7]
```diff
@@ -19,6 +19,7 @@ use near_primitives::types::{
 use near_runtime_configs::RuntimeConfig;
 
 use crate::PROTOCOL_VERSION;
+use num_rational::Rational;
```
[the remark this answers is not in the document]
Comment (bowenwang1996) [reply core/chain-configs/src/genesis_config.rs:22]: Maybe I should stop using clion.

File: scripts/migrations/8-fraction.py [hunk 8]
```diff
@@ -20,22 +20,10 @@
...
-    'denominator': 10,
-}
-config['max_inflation_rate'] = {
-    'numerator': 5,
-    'denominator': 100,
-}
-
+config['gas_price_adjustment_rate'] = [1, 100]
+config['protocol_reward_percentage'] = [1, 10]
+config['developer_reward_percentage'] = [3, 10]
```
Comment (evgenykuzyakov) [inline scripts/migrations/8-fraction.py]: This is not user right?

File: scripts/migrations/8-fraction.py [hunk 9]
```diff
@@ -20,22 +20,10 @@
...
+config['max_inflation_rate'] = [5, 100]
+config['runtime_config']['transaction_costs']['burnt_gas_reward'] = [3, 10]
```
Comment (evgenykuzyakov) [inline scripts/migrations/8-fraction.py:29]: The reward is actually here

File: scripts/migrations/8-fraction.py (hunk 6 above)
Comment (frol) [reply scripts/migrations/8-fraction.py]: > What do you suggest instead of overriding?

I suggest computing from the previous value, so if that was percentage integer, it will become `[old value, 100]`

> Why?

My bad, nevermind.

File: scripts/migrations/8-fraction.py (hunk 9 above)
Comment (bowenwang1996) [reply scripts/migrations/8-fraction.py:29]: ah I guess that is a duplicate then.

File: scripts/migrations/8-fraction.py (hunk 6 above)
Comment (bowenwang1996) [reply scripts/migrations/8-fraction.py]: The problem is that the internal representation is an irreducible fraction so it is impossible to have 100 as the denominator if the numerator is not relatively prime to 100.

Comment (frol) [reply scripts/migrations/8-fraction.py]: Python has built-in `math.gcd`...

Comment (bowenwang1996) [reply scripts/migrations/8-fraction.py]: > Python has built-in math.gcd

Not sure what you mean here. It is not about manually reducing the fraction. The representation has to conform to internal representation otherwise the check on genesis will fail.

Comment (frol) [reply scripts/migrations/8-fraction.py]: It seems that I don't understand what internal representation you refer to. Given it is part of the genesis config, and it should be updated with great caution by someone who understands what they are going, I am fine to just let it go (though I admit, I don't understand why the existing value, e.g. 5%, we cannot convert it to a fraction representation, i.e. 1/20, and instead we override it to 3/10)

Comment (bowenwang1996) [reply scripts/migrations/8-fraction.py]: We didn't override it to 3/10. We changed it 1/20.

File: chain/epoch_manager/src/reward_calculator.rs [hunk 10]
```diff
@@ -25,16 +25,18 @@ impl RewardCalculator {
...
-            / (U256::from(100) * U256::from(self.num_blocks_per_year)))
+            / (U256::from(self.num_blocks_per_year)
+                * U256::from(*self.max_inflation_rate.denom() as u64)))
         .as_u128();
         let epoch_fee = total_validator_reward;
         let inflation = if max_inflation > epoch_fee { max_inflation - epoch_fee } else { 0 };
         let epoch_total_reward = max(max_inflation, epoch_fee);
-        let epoch_protocol_treasury =
-            epoch_total_reward * u128::from(self.protocol_reward_percentage) / 100;
+        let epoch_protocol_treasury = epoch_total_reward
```
Comment (evgenykuzyakov) [inline chain/epoch_manager/src/reward_calculator.rs:37]: Why not use U256 here as well. Do we expect that the `protocol_reward_percentage` numerator always be small enough to fit into u128?

File: runtime/near-runtime-fees/Cargo.toml (hunk 4 above)
Comment (nearmax) [reply runtime/near-runtime-fees/Cargo.toml]: https://github.com/nearprotocol/nearcore/issues/2457
