### PR TITLE
fix(rosetta-rpc): fixed duplicates by transaction identifier in /block Data API

### LINKED ISSUE #3435: fix(rosetta-rpc): Avoid duplicate "fake transaction" hashes in Rosetta Data API
"fake" transactions (block events like validator rewards get a `block:<block_hash>` as a Rosetta transaction hash) got duplicated:

```json
{
  "block": {
    "block_identifier": {
      "index": 15177032,
      "hash": "4MvNEmwBNjcVd4cH1jFuTWFs9khhzU5c2BYurA592Kky"
    },
    "parent_block_identifier": {
      "index": 15177031,
      "hash": "8hJbvdmuptP2nAc95bkeiH4AyZKxM5oHjQ26MhftcogC"
    },
    "timestamp": 1599613401351,
    "transactions": [
      {
        "transaction_identifier": { "hash": "block:4MvNEmwBNjcVd4cH1jFuTWFs9khhzU5c2BYurA592Kky" },
        "operations": [
          {
            "operation_identifier": { "index": 0 },
            "type": "TRANSFER",
            "status": "SUCCESS",
            "account": { "address": "nfvalidator2.near" },
            "amount": {
              "value": "400000000000000000000000000000",
              "currency": { "symbol": "yoctoNEAR", "decimals": 0 }
            }
          },
          {
            "operation_identifier": { "index": 1 },
            "type": "TRANSFER",
            "status": "SUCCESS",
            "account": { "address": "nfvalidator2.near", "sub_account": { "address": "LOCKED" } },
            "amount": {
              "value": "-400000000000000000000000000000",
              "currency": { "symbol": "yoctoNEAR", "decimals": 0 }
            }
          }
        ],
        "metadata": { "type": "TRANSACTION" }
      },
      {
        "transaction_identifier": {
          "hash": "receipt:CKWtvsoAdVBFToeuwmVdhmgMJAJ3WS2oP56Ex7TQZ233"
        },
        "operations": [
          {
            "operation_identifier": { "index": 0 },
            "type": "TRANSFER",
            "status": "SUCCESS",
            "account": { "address": "jerry.zest.near" },
            "amount": {
              "value": "40000000000000000000000",
              "currency": { "symbol": "yoctoNEAR", "decimals": 0 }
            }
          }
        ],
        "metadata": { "type": "TRANSACTION" }
      },
      {
        "transaction_identifier": {
          "hash": "receipt:7fKgfKHLu35bmbapzR1BfZd9tNpeMdD4rTxm8bUHRac8"
        },
        "operations": [
          {
            "operation_identifier": { "index": 0 },
            "type": "TRANSFER",
            "status": "SUCCESS",
            "account": { "address": "jerry.zest.near" },
            "amount": {
              "value": "100400000000000000000000",
              "currency": { "symbol": "yoctoNEAR", "decimals": 0 }
            }
          },
          {
            "operation_identifier": { "index": 1 },
            "type": "TRANSFER",
            "status": "SUCCESS",
            "account": {
              "address": "jerry.zest.near",
              "sub_account": { "address": "LIQUID_BALANCE_FOR_STORAGE" }
            },
            "amount": {
              "value": "120200000000000000000000",
              "currency": { "symbol": "yoctoNEAR", "decimals": 0 }
            }
          },
          {
            "operation_identifier": { "index": 2 },
            "type": "TRANSFER",
            "status": "SUCCESS",
            "account": { "address": "jerry.zest.near" },
            "amount": {
              "value": "300781674492800000000",
              "currency": { "symbol": "yoctoNEAR", "decimals": 0 }
            }
          }
        ],
        "metadata": { "type": "TRANSACTION" }
      },
      {
        "transaction_identifier": {
          "hash": "receipt:4EDaQnsSpTuSeSWHGnqEzwLkA3TjmyxZHSW5nf895Ev6"
        },
        "operations": [
          {
            "operation_identifier": { "index": 0 },
            "type": "TRANSFER",
            "status": "SUCCESS",
            "account": { "address": "jerry.zest.near" },
            "amount": {
              "value": "40000000000000000000000",
              "currency": { "symbol": "yoctoNEAR", "decimals": 0 }
            }
          }
        ],
        "metadata": { "type": "TRANSACTION" }
      },
      {
        "transaction_identifier": {
          "hash": "receipt:EuHbmnDuKm4MqGNFrbWEWnjCA7mSxhtpwpZg2aBaRcmK"
        },
        "operations": [
          {
            "operation_identifier": { "index": 0 },
            "type": "TRANSFER",
            "status": "SUCCESS",
            "account": { "address": "jerry.zest.near" },
            "amount": {
              "value": "160200000000000000000000",
              "currency": { "symbol": "yoctoNEAR", "decimals": 0 }
            }
          },
          {
            "operation_identifier": { "index": 1 },
            "type": "TRANSFER",
            "status": "SUCCESS",
            "account": {
              "address": "jerry.zest.near",
              "sub_account": { "address": "LIQUID_BALANCE_FOR_STORAGE" }
            },
            "amount": {
              "value": "88700000000000000000000",
              "currency": { "symbol": "yoctoNEAR", "decimals": 0 }
            }
          },
          {
            "operation_identifier": { "index": 2 },
            "type": "TRANSFER",
            "status": "SUCCESS",
            "account": { "address": "jerry.zest.near" },
            "amount": {
              "value": "221996461222000000000",
              "currency": { "symbol": "yoctoNEAR", "decimals": 0 }
            }
          }
        ],
        "metadata": { "type": "TRANSACTION" }
      },
      {
        "transaction_identifier": {
          "hash": "receipt:9mCsYWvXmuG7ipVqcVE76pDsNRLWWPxz7NDhY79yo6dS"
        },
        "operations": [
          {
            "operation_identifier": { "index": 0 },
            "type": "TRANSFER",
            "status": "SUCCESS",
            "account": { "address": "jerry.zest.near" },
            "amount": {
              "value": "40000000000000000000000",
              "currency": { "symbol": "yoctoNEAR", "decimals": 0 }
            }
          }
        ],
        "metadata": { "type": "TRANSACTION" }
      },
      {
        "transaction_identifier": {
          "hash": "receipt:GduRCLA6YSgVTY7kgf9MCiHLuQh9irPKYjE9BQ1WZAaG"
        },
        "operations": [
          {
            "operation_identifier": { "index": 0 },
            "type": "TRANSFER",
            "status": "SUCCESS",
            "account": { "address": "jerry.zest.near" },
            "amount": {
              "value": "248900000000000000000000",
              "currency": { "symbol": "yoctoNEAR", "decimals": 0 }
            }
          },
          {
            "operation_identifier": { "index": 1 },
            "type": "TRANSFER",
            "status": "SUCCESS",
            "account": {
              "address": "jerry.zest.near",
              "sub_account": { "address": "LIQUID_BALANCE_FOR_STORAGE" }
            },
            "amount": {
              "value": "87100000000000000000000",
              "currency": { "symbol": "yoctoNEAR", "decimals": 0 }
            }
          },
          {
            "operation_identifier": { "index": 2 },
            "type": "TRANSFER",
            "status": "SUCCESS",
            "account": { "address": "jerry.zest.near" },
            "amount": {
              "value": "215039044406800000000",
              "currency": { "symbol": "yoctoNEAR", "decimals": 0 }
            }
          }
        ],
        "metadata": { "type": "TRANSACTION" }
      },
      {
        "transaction_identifier": { "hash": "block:4MvNEmwBNjcVd4cH1jFuTWFs9khhzU5c2BYurA592Kky" },
        "operations": [
          {
            "operation_identifier": { "index": 0 },
            "type": "TRANSFER",
            "status": "SUCCESS",
            "account": { "address": "nfvalidator1.near" },
            "amount": {
              "value": "2400000000000000000000000000000",
              "currency": { "symbol": "yoctoNEAR", "decimals": 0 }
            }
          },
          {
            "operation_identifier": { "index": 1 },
            "type": "TRANSFER",
            "status": "SUCCESS",
            "account": { "address": "nfvalidator1.near", "sub_account": { "address": "LOCKED" } },
            "amount": {
              "value": "-2400000000000000000000000000000",
              "currency": { "symbol": "yoctoNEAR", "decimals": 0 }
            }
          }
        ],
        "metadata": { "type": "TRANSACTION" }
      },
      {
        "transaction_identifier": {
          "hash": "receipt:5Avo1gjGNTnTaWftL1r3RdMatBgNGDF92LKCyCd9xurs"
        },
        "operations": [
          {
            "operation_identifier": { "index": 0 },
            "type": "TRANSFER",
            "status": "SUCCESS",
            "account": { "address": "tom.zest.near" },
            "amount": {
              "value": "13111668237907776551568",
              "currency": { "symbol": "yoctoNEAR", "decimals": 0 }
            }
          }
        ],
        "metadata": { "type": "TRANSACTION" }
      },
      {
        "transaction_identifier": {
          "hash": "receipt:Aob3RtUrWZEutEg4mjPnsLLuNBXNYKTEQZ51bs5VbbUC"
        },
        "operations": [
          {
            "operation_identifier": { "index": 0 },
            "type": "TRANSFER",
            "status": "SUCCESS",
            "account": { "address": "tom.zest.near" },
            "amount": {
              "value": "13274146170578952964084",
              "currency": { "symbol": "yoctoNEAR", "decimals": 0 }
            }
          }
        ],
        "metadata": { "type": "TRANSACTION" }
      },
      {
        "transaction_identifier": {
          "hash": "receipt:2mMyzTtpb9MaZfg1bskjjGhGkrgYswF79mVrD2B9SwMV"
        },
        "operations": [
          {
            "operation_identifier": { "index": 0 },
            "type": "TRANSFER",
            "status": "SUCCESS",
            "account": { "address": "tom.zest.near" },
            "amount": {
              "value": "13274297992760376551568",
              "currency": { "symbol": "yoctoNEAR", "decimals": 0 }
            }
          }
        ],
        "metadata": { "type": "TRANSACTION" }
      },
      {
        "transaction_identifier": { "hash": "block:4MvNEmwBNjcVd4cH1jFuTWFs9khhzU5c2BYurA592Kky" },
        "operations": [],
        "metadata": { "type": "TRANSACTION" }
      }
    ]
  }
}
```

`block:4MvNEmwBNjcVd4cH1jFuTWFs9khhzU5c2BYurA592Kky` appeared 3 times due to the fact that some of the block changes happen before the transactions and receipts are processed, but some appear after those being processed, which creates this duplication.

### PR DESCRIPTION
**Pull request by frol**
*Resolves #3435*

NOTE: The order of transactions in Rosetta /block response is arbitrary. If that is critical, we need to address it separately recovering the order of events processing inside nearcore (validator accounts are updated first, then transactions are translated into receipts, then local receipts are executed, then delayed receipts are executed, then new incoming receipts are executed, then delayed receipts indices are computed)

### CODE REVIEW

File: chain/rosetta-rpc/src/adapters/mod.rs [hunk 1]
```diff
@@ -144,54 +142,66 @@ pub(crate) async fn convert_block_to_transactions(
...
+    let transactions = convert_block_changes_to_transactions(
+        &genesis.config.runtime_config,
+        &block.header.hash,
+        accounts_changes,
+        accounts_previous_state,
+    )?;
+    Ok(transactions.into_iter().map(|(_transaction_hash, transaction)| transaction).collect())
+}
+
+fn convert_block_changes_to_transactions(
```
Comment (frol) [inline chain/rosetta-rpc/src/adapters/mod.rs:154]: I refactored it into a separate testable function (and covered with snapshot tests)

File: chain/rosetta-rpc/src/adapters/mod.rs [hunk 2]
```diff
@@ -144,54 +142,66 @@ pub(crate) async fn convert_block_to_transactions(
...
+            StateChangeCauseView::InitialState => format!("block:{}", block_hash),
+            StateChangeCauseView::ValidatorAccountsUpdate => {
+                format!("block-validators-update:{}", block_hash)
             }
-            near_primitives::views::StateChangeCauseView::InitialState
-            | near_primitives::views::StateChangeCauseView::ValidatorAccountsUpdate
-            | near_primitives::views::StateChangeCauseView::UpdatedDelayedReceipts => {
-                format!("block:{}", block.header.hash)
+            StateChangeCauseView::UpdatedDelayedReceipts => {
+                format!("block-delayed-receipts:{}", block_hash)
```
Comment (frol) [inline chain/rosetta-rpc/src/adapters/mod.rs:183]: These change events are now decoupled into separate "fake transactions"

File: chain/rosetta-rpc/src/adapters/mod.rs [hunk 3]
```diff
@@ -144,54 +142,66 @@ pub(crate) async fn convert_block_to_transactions(
...
-                transaction_identifier: crate::models::TransactionIdentifier {
-                    hash: transaction_hash.clone(),
-                },
-                operations: vec![],
-                metadata: crate::models::TransactionMetadata {
-                    type_: crate::models::TransactionType::Transaction,
-                },
+
+        let current_transaction =
+            transactions.entry(transaction_hash.clone()).or_insert_with(move || {
```
Comment (frol) [inline chain/rosetta-rpc/src/adapters/mod.rs:193]: Instead of relying on invalid sequential order (the state changes are grouped by account ID instead of preserving in historical order), I switched to using HashMap. If the order of transactions is critical, we should replicate the sorting after we collect this HashMap.

File: chain/rosetta-rpc/src/adapters/mod.rs [hunk 4]
```diff
@@ -144,54 +142,66 @@ pub(crate) async fn convert_block_to_transactions(
...
+            | StateChangeCauseView::ActionReceiptGasReward { receipt_hash }
+            | StateChangeCauseView::ReceiptProcessing { receipt_hash }
+            | StateChangeCauseView::PostponedReceipt { receipt_hash } => {
                 format!("receipt:{}", receipt_hash.to_base())
             }
-            near_primitives::views::StateChangeCauseView::PostponedReceipt { receipt_hash } => {
-                format!("receipt:{}", receipt_hash.to_base())
+            StateChangeCauseView::InitialState => format!("block:{}", block_hash),
+            StateChangeCauseView::ValidatorAccountsUpdate => {
+                format!("block-validators-update:{}", block_hash)
```
Comment (bowenwang1996) [inline chain/rosetta-rpc/src/adapters/mod.rs:180]: doesn't this mean that the transaction identifier will be the same for all validator account updates? Is that intended?

Comment (frol) [reply chain/rosetta-rpc/src/adapters/mod.rs:180]: Good question! Well, Rosetta is fine doing it this way. The problem is that from NEAR point of view there cannot be a transaction to multiple receiver ids (in Rosetta it is possible to express), so you cannot reconstruct such a transaction, but given it is a "fake transaction" anyway, we can get away with it, I guess. Another problematic endpoint is the first block, which we construct from genesis records (and it is a massive single fake transaction with tons of operations).

Ultimately, I consider this solution as good enough to address the original issue of duplicate transaction identifiers. We may redesign the transaction split with more granular transaction identifiers once we have a specific request for that (from Rosetta point of view, it should be indifferent whether it is a single transaction with a generic transaction identifier and N operations or N transactions with specific transaction identifier and 1 operation in every one of them)

**Review by bowenwang1996 — APPROVED** [review]
