### PR TITLE
fix(storage): fix refcount bug

### LINKED ISSUE #2568: Trie refcount bug
- Trie nodes are stored in storage with refcounts
- TrieChanges stores a delta of refcount
- StoreUpdate stores a database transaction with exact writes of refcount
- Applying TrieChanges to storage reads refcount from storage, increments it by delta and creates a write for StoreUpdate
- Writing multiple TrieChanges into StoreUpdate in a single transaction will always read refcount before the transaction, so instead of the sum of increments only one is applied.

This is most likely what causes #2500 #2544 #2556

### PR DESCRIPTION
**Pull request by mikhailOK**
Separate tries from different shards.
Each shard has a Trie with its own prefix in storage and its own
cache.

Fixes #2568

Test plan
---------
debug_assert in StoreUpdate::commit

### CODE REVIEW

File: chain/chain/src/chain.rs [hunk 1]
```diff
@@ -587,7 +587,11 @@ impl Chain {
         Ok(())
     }
 
-    pub fn clear_forks_data(&mut self, trie: Arc<Trie>, height: BlockHeight) -> Result<(), Error> {
+    pub fn clear_forks_data(
+        &mut self,
+        trie: Arc<ShardTries>,
```
Comment (Kouprin) [inline chain/chain/src/chain.rs:592]: trie -> tries?

File: chain/chain/src/store.rs [hunk 2]
```diff
@@ -1750,7 +1750,7 @@ impl<'a> ChainStoreUpdate<'a> {
                     .get_ser(ColTrieChanges, block_hash.as_ref())?
                     .map(|trie_changes: TrieChanges| {
                         trie_changes
-                            .revert_insertions_into(trie.clone(), &mut store_update)
+                            .revert_insertions_into(trie.clone(), 0, &mut store_update)
```
Comment (Kouprin) [inline chain/chain/src/store.rs:1753]: Why does it 0?

File: chain/chain/src/test_utils.rs [hunk 3]
```diff
@@ -682,7 +682,8 @@ impl RuntimeAdapter for KeyValueRuntime {
 
         Ok(ApplyTransactionResult {
             trie_changes: WrappedTrieChanges::new(
-                self.trie.clone(),
+                self.get_tries(),
```
Comment (Kouprin) [inline chain/chain/src/test_utils.rs:685]: we need exact shard at this point, not all of them
why not to use `get_trie_for_shard` instead?

File: core/store/src/lib.rs [hunk 4]
```diff
@@ -129,7 +129,7 @@ pub struct StoreUpdate {
     storage: Arc<dyn Database>,
     transaction: DBTransaction,
     /// Optionally has reference to the trie to clear cache on the commit.
-    trie: Option<Arc<Trie>>,
+    trie: Option<Arc<ShardTries>>,
```
Comment (Kouprin) [inline core/store/src/lib.rs:132]: trie -> tries
and everywhere, where `ShardTries`

File: core/store/src/trie/mod.rs [hunk 5]
```diff
@@ -416,6 +416,60 @@ pub struct Trie {
     pub counter: TouchedNodesCounter,
 }
 
+pub struct ShardTries {
+    tries: Vec<Arc<Trie>>,
```
Comment (Kouprin) [inline core/store/src/trie/mod.rs:420]: I'm surprised that we use it outside in such way: `Arc<Vec<Arc<Trie>>>`. I expect it should be just `Vec<Arc<Trie>>`. What is the reason to keep Arc for Vec?

File: core/store/src/trie/mod.rs [hunk 6]
```diff
@@ -416,6 +416,60 @@ pub struct Trie {
...
+                    let hash = CryptoHash::try_from(&key[8..]).map_err(|_| {
+                        std::io::Error::new(ErrorKind::Other, "Key is always a hash")
+                    })?;
+                    shards[shard_id as usize].push((hash, Some(value.clone())));
+                }
+                DBOp::Delete { col, ref key } if *col == ColState => {
+                    let shard_id = u64::from_le_bytes(key[0..8].try_into().unwrap());
+                    let hash = CryptoHash::try_from(&key[8..]).map_err(|_| {
+                        std::io::Error::new(ErrorKind::Other, "Key is always a hash")
+                    })?;
```
Comment (Kouprin) [inline core/store/src/trie/mod.rs:460]: the code for getting shard_id and hash is complicated and should not be duplicated
please add a method `get_shard_hash_from_bytes`

File: core/store/src/trie/mod.rs [hunk 7]
```diff
@@ -623,7 +678,10 @@ impl WrappedTrieChanges {
     ) -> Result<(), Box<dyn std::error::Error>> {
         self.insertions_into(&mut store_update)?;
         self.state_changes_into(&mut store_update)?;
-        store_update.set_ser(ColTrieChanges, self.block_hash.as_ref(), &self.trie_changes)?;
+        // TODO #2564
```
Comment (Kouprin) [inline core/store/src/trie/mod.rs:681]: are you decided not to apply https://github.com/nearprotocol/nearcore/pull/2592 to this change?

File: core/store/src/lib.rs [hunk 8]
```diff
@@ -187,9 +189,34 @@ impl StoreUpdate {
...
+                    })
+                    .collect::<std::collections::HashSet<_>>()
+                    .len(),
+            "Transaction overwrites itself: {:?}",
+            self
+        );
         if let Some(trie) = self.trie {
             assert_eq!(
-                trie.storage.as_caching_storage().unwrap().store.storage.as_ref() as *const _,
+                trie.get_trie_for_shard(0)
```
Comment (frol) [inline core/store/src/lib.rs:213]: Is it going to work with many shards?

File: core/store/src/trie/mod.rs [hunk 9]
```diff
@@ -454,17 +508,18 @@ impl TrieChanges {
     }
     pub fn insertions_into(
         &self,
-        trie: Arc<Trie>,
+        trie: Arc<ShardTries>,
```
Comment (frol) [inline core/store/src/trie/mod.rs:511]: Why cannot we keep it simple single Trie? I mean, what is the reason to pass a list of all the ShardTries and shard_id index all the way down?

This API is confusing now as it is hard to reason whether one shard can influence other shards.

File: core/store/src/lib.rs (hunk 8 above)
Comment (Kouprin) [reply core/store/src/lib.rs:213]: I guess it should because storage is the same

File: core/store/src/test_utils.rs [hunk 10]
```diff
@@ -15,9 +14,9 @@ pub fn create_test_store() -> Arc<Store> {
 }
 
 /// Creates a Trie using an in-memory database.
```
Comment (bowenwang1996) [inline core/store/src/test_utils.rs:16]: this comment should also be updated?

File: core/store/src/trie/mod.rs (hunk 5 above)
Comment (bowenwang1996) [reply core/store/src/trie/mod.rs:420]: It seems to me that the outer one is the one that is potentially shared between threads. So shouldn't it be `Arc<Vec<Trie>>`?

File: chain/chain/src/store.rs (hunk 2 above)
Comment (mikhailOK) [reply chain/chain/src/store.rs:1753]: separating this fix and #2592

File: chain/chain/src/test_utils.rs (hunk 3 above)
Comment (mikhailOK) [reply chain/chain/src/test_utils.rs:685]: because later we pass all of them to `StoreUpdate`

File: core/store/src/trie/mod.rs (hunk 5 above)
Comment (mikhailOK) [reply core/store/src/trie/mod.rs:420]: `Arc<Trie>` to pass to `TrieUpdate`
`Arc<Vec<Arc<Trie>>>` to pass the whole thing all around without copying the Vec
Later we can refactor the code to non-owning references and lifetime annotations, Arc just makes things simpler

File: core/store/src/trie/mod.rs (hunk 9 above)
Comment (mikhailOK) [reply core/store/src/trie/mod.rs:511]: Here the reason is that someone needs to pass `ShardTries` to `StoreUpdate`.

File: core/store/src/trie/mod.rs (hunk 7 above)
Comment (mikhailOK) [reply core/store/src/trie/mod.rs:681]: correct

File: core/store/src/trie/mod.rs (hunk 6 above)
Comment (mikhailOK) [reply core/store/src/trie/mod.rs]: done

File: core/store/src/trie/mod.rs (hunk 5 above)
Comment (Kouprin) [reply core/store/src/trie/mod.rs:420]: @bowenwang1996 it doesn't make sense because different threads may have different vectors filled with same `Arc<Trie>` data. No need to do `Arc<Vec<Arc<..>>>`.

@mikhailOK why not copy a vector? It's simple and transparent.

Comment (mikhailOK) [reply core/store/src/trie/mod.rs:420]: Having one instance of `ShardTries` is easier to reason about than having copies.

Here is a new issue for a refactor: #2639, this is potentially not the `Arc` to remove.

File: core/store/src/trie/mod.rs (hunk 9 above)
Comment (frol) [reply core/store/src/trie/mod.rs]: Can we decouple that? Create something like TrieUpdate and operate on that level?

Comment (mikhailOK) [reply core/store/src/trie/mod.rs]: How about we move storage mutation methods to `ShardTries`: `ShardTries::apply_insertions(ShardId, &TrieChanges, &mut StoreUpdate)`?

File: core/store/src/trie/mod.rs (hunk 5 above)
Comment (Kouprin) [reply core/store/src/trie/mod.rs:420]: Sounds good.

File: core/store/src/trie/mod.rs (hunk 9 above)
Comment (frol) [reply core/store/src/trie/mod.rs]: @mikhailOK I am not sure I exactly follow the suggestion, so let me try to clarify:

Having the change you proposed we will keep the Trie operations as they used to be (operating on a single Trie and returning TrieChanges), and then, one level up, we apply the TrieChanges into StoreUpdate. This sounds reasonable to me :+1:

**Comment by bowenwang1996** [comment]
> Will it handle gracefully the changes in tracking_shards

What do you mean by "gracefully"? keep in mind that we won't have dynamic resharding any time soon.

**Comment by frol** [comment]
"gracefully" - won't break apart if I restart a node changing the config from tracking [] (empty list) to [0] (a single shard with id 0) or the other way around [0] -> [], or some time in the future [0] -> [2].

File: core/store/src/trie/mod.rs (hunk 9 above)
Comment (mikhailOK) [reply core/store/src/trie/mod.rs]: moved the code out of TrieChanges, now only `WrappedTrieChanges` and `ShardTries` are aware of shard_id

File: core/store/src/lib.rs [hunk 11]
```diff
@@ -129,18 +129,19 @@ pub struct StoreUpdate {
...
 
 impl StoreUpdate {
     pub fn new(storage: Arc<dyn Database>) -> Self {
         let transaction = storage.transaction();
-        StoreUpdate { storage, transaction, trie: None }
+        StoreUpdate { storage, transaction, tries: None }
     }
 
-    pub fn new_with_trie(storage: Arc<dyn Database>, trie: Arc<Trie>) -> Self {
+    pub fn new_with_trie(tries: ShardTries) -> Self {
```
Comment (frol) [inline core/store/src/lib.rs:141]: It is now new_with_tries

File: core/store/src/lib.rs [hunk 12]
```diff
@@ -164,15 +165,17 @@ impl StoreUpdate {
 
     /// Merge another store update into this one.
     pub fn merge(&mut self, other: StoreUpdate) {
-        if self.trie.is_none() {
-            if let Some(trie) = other.trie {
-                assert_eq!(
-                    trie.storage.as_caching_storage().unwrap().store.storage.as_ref() as *const _,
-                    self.storage.as_ref() as *const _
+        if let Some(trie) = other.tries {
```
Comment (frol) [inline core/store/src/lib.rs:168]: Some(tries)

File: core/store/src/lib.rs [hunk 13]
```diff
@@ -187,9 +190,34 @@ impl StoreUpdate {
...
+                        DBOp::Delete { col, key } => {
+                            (*col as u8, key)
+                        }
+                    })
+                    .collect::<std::collections::HashSet<_>>()
+                    .len(),
+            "Transaction overwrites itself: {:?}",
+            self
+        );
+        if let Some(trie) = self.tries {
```
Comment (frol) [inline core/store/src/lib.rs:212]: Some(tries)

File: core/store/src/lib.rs [hunk 14]
```diff
@@ -187,9 +190,34 @@ impl StoreUpdate {
...
             assert_eq!(
-                trie.storage.as_caching_storage().unwrap().store.storage.as_ref() as *const _,
+                trie.get_trie_for_shard(0)
```
Comment (frol) [inline core/store/src/lib.rs:214]: Can we use tries.get_store() here? That would be much easier to reason about otherwise, I would love to see a comment saying that the storage is the same for all the tries.

File: core/store/src/trie/shard_tries.rs [hunk 15]
```diff
@@ -0,0 +1,326 @@
...
+            self.clone(),
+            shard_id,
+            store_update,
+        )
+    }
+
+    pub fn revert_insertions(
+        &self,
+        trie_changes: &TrieChanges,
+        shard_id: ShardId,
```
Comment (frol) [inline core/store/src/trie/shard_tries.rs:159]: It is still easy to make a silly yet crucial mistake with API like this if you pass a wrong shard_id. I propose we have ShardTrie and ShardTrieChanges, which wrap the relevant structures and pass along the shard_id, so we never lose the information about a shard, and thus we don’t need to pass it separately relying on the outer code to maintain the invariant of providing the correct shard_id.

I am a huge fun of making the invalid state to be impossible to express, there is a cool talk about this mindset if I can recommend: https://youtu.be/3Q2hQfYW-XM (A hammer you can only hold by the handle)

Comment (mikhailOK) [reply core/store/src/trie/shard_tries.rs:159]: `revert_insertions` and `apply_deletions` are only called in one place by gc.
`apply_insertions` is only called by `WrappedTrieChanges` which wraps `block_hash`, `tries` and `shard_id`.
`apply_all` is called once in state sync, once in genesis builder and in ~30 places in test code.

For gc usages `ShardTrie` wouldn't have a longer lifetime than creating it for calling this function. I think instead it might make sense to have a `SingleShardTrieForTests` so we don't pass dummy shard in 30 places.

**Comment by mikhailOK** [comment]
ShardTries always has all `num_shards` shards, so no bug possible with indexing

**Comment by nearmax** [comment]
So technically it is still one single trie with one root for all shards, correct? Because if we have separate trie with separate root for each shard it is not going to be forward compatible with dynamic resharding, correct? This change only changes the database representation, do I understand it correctly?

**Comment by mikhailOK** [comment]
It's always been one root per shard, this change only affects internal database representation

**Comment by nearmax** [comment]
If there has been one root per shard then trees must have been completely independent between shards. How can committing transaction for shard A affect transaction for shard B if they update completely non-overlapping key-value records (they are non-overlapping because trees are disjoint)? @mikhailOK

**Comment by mikhailOK** [comment]
independent roots != no overlap in storage representation
Before this change: independent roots, shared storage
After this change: independent roots, separated storage

We decided to completely separate storage because it also makes state sync simple to fix: #2569

**Comment by nearmax** [comment]
@mikhailOK So I am still not understanding while there is an overlap in the storage. Since each shard uses a different record in the state column (because their nodes are completely different) then why when we submit several storage changes concurrently that update different records there is an interference?

**Comment by mikhailOK** [comment]
>(because their nodes are completely different)

Nodes can be equal because a node is entirely defined by its subtree.
Equal values is the simplest example.
