### PR TITLE
fix(chain): Fixed telemetry data sending to HTTPS endpoint

### LINKED ISSUE #2306: Telemetry for devnet and betanet is off
Currently if you run `nearup betanet` or `nearup devnet` you get:
`Telemetry: https://explorer.nearprotocol.com/api/nodes`.

Also note that if you look at the explorer, neither of the networks have any reported nodes.

### PR DESCRIPTION
**Pull request by frol**
*Resolves #2306*

We already have a record of breaking Telemetry once in a while not even noticing this fact till much later, thus I decided not only to fix it, but also put some logging there.

## Test Plan

* [x] Manually checked that the fix works (openssl is statically linked and
  system root CA certificates still get detected and used)
* [x] Added "info" logger to report Telemetry issues (I choose "info" level
  to indicate that it is not critical, and node can operate just fine
  with that when the message appears in the logs)

### CODE REVIEW

File: near/src/main.rs [hunk 1]
```diff
@@ -18,7 +18,7 @@ use near::{get_default_home, get_store_path, init_configs, load_config, start_wi
 use near_primitives::types::Version;
 
 fn init_logging(verbose: Option<&str>) {
-    let mut env_filter = EnvFilter::new("tokio_reactor=info,near=info,stats=info");
+    let mut env_filter = EnvFilter::new("tokio_reactor=info,near=info,stats=info,telemetry=info");
```
Comment (bowenwang1996) [inline near/src/main.rs]: why do we need to include telemetry logs?

Comment (frol) [reply near/src/main.rs]: To make them visible... We have broken Telemetry 3 times since we introduced it, and every single time it took us quite some time to notice that.

Comment (bowenwang1996) [reply near/src/main.rs]: I am not sure whether we want to do this by default. It seems useless for most people.

Comment (frol) [reply near/src/main.rs]: It will only print any log if there is an issue with telemetry, so most of the time it is going to be silent...

Comment (bowenwang1996) [reply near/src/main.rs]: Okay then

**Comment by frol** [comment]
@ailisp Can you help with the failing CI?

**Comment by ailisp** [comment]
Sorry I just see this. could be related to #2337 let me try

**Comment by frol** [comment]
@ailisp That did not work :thinking:

**Comment by ailisp** [comment]
@frol It seems it quite different to debug it locally than how it behaves on ci and very slow to debug by commit some new `print`. I just try a different approach, download beta binary and test against current branch hope that works

**Comment by ailisp** [comment]
also this seems to be your branch name has `/` and state-migration/backward-compatible script doesn't escape `/` in path properly, i'll fix in the pr too
