### PR TITLE
fix: gc test

### LINKED ISSUE #2368: test_gc_with_epoch_length fails
`assertion failed: env.clients[0].chain.get_block(&blocks[i as usize - 1].hash()).is_err()`

Related to #2274 #2084

### PR DESCRIPTION
**Pull request by bowenwang1996**
Fixes `test_gc_with_epoch_length`. It failed because now `clear_block_data` clears the data on the previous block if the block is on the canonical chain. Also increases timeout on nightly gc tests. Resolves #2368.

Test plan
---------
Make sure that `test_gc_with_epoch_length` passes.

### CODE REVIEW

File: chain/client/tests/process_blocks.rs [hunk 1]
```diff
@@ -851,7 +851,8 @@ fn test_gc_with_epoch_length_common(epoch_length: NumBlocks) {
         blocks.push(block);
     }
     for i in 1..=epoch_length * (NUM_EPOCHS_TO_KEEP_STORE_DATA + 1) {
-        if i <= epoch_length {
+        println!("height = {}", i);
```
Comment (mfornet) [inline chain/client/tests/process_blocks.rs:854]: Remove `println`

Comment (bowenwang1996) [reply chain/client/tests/process_blocks.rs:862]: This is in a test, so I think it is fine.
