### PR TITLE
fix(sync): Stop requesting headers from banned peer

### LINKED ISSUE #2305: Mailbox has closed and banning all peers
Running `nearup betanet` via Docker on my laptop via VPN (so might have network issues):

Observing, `near_network::peer_manager: Failed sending message: Mailbox has closed` error.
Post that we also banning this peer `Try to ban a disconnected peer: ed25519:ydgzeXHJ5Xyt7M1gXLxqLBW1Ejx6scNV5Nx2pxFM8su`, which is somewhat unexpected.

```
Mar 24 14:45:29.249  INFO stats: #       0 Downloading headers 0% -/4  5/2/40 peers ⬇ 2.0kiB/s ⬆ 0.5kiB/s 0.00 bps 0 gas/s CPU: 2%, Mem: 24.9 MiB
Mar 24 14:45:32.710 ERROR near_network::peer_manager: Failed sending message: Mailbox has closed
Mar 24 14:45:39.251  INFO stats: #       0 Downloading headers 0% -/4  4/1/40 peers ⬇ 1.2kiB/s ⬆ 0.4kiB/s 0.00 bps 0 gas/s CPU: 2%, Mem: 25.1 MiB
Mar 24 14:45:42.710  WARN network: Try to ban a disconnected peer: ed25519:ydgzeXHJ5Xyt7M1gXLxqLBW1Ejx6scNV5Nx2pxFM8su
Mar 24 14:45:49.255  INFO stats: #       0 Downloading headers 0% -/4  4/1/40 peers ⬇ 1.2kiB/s ⬆ 0.4kiB/s 0.00 bps 0 gas/s CPU: 2%, Mem: 25.1 MiB
Mar 24 14:45:52.719 ERROR near_network::peer_manager: Failed sending message: Mailbox has closed
Mar 24 14:45:59.257  INFO stats: #       0 Downloading headers 0% -/4  3/1/40 peers ⬇ 0.5kiB/s ⬆ 0.3kiB/s 0.00 bps 0 gas/s CPU: 2%, Mem: 25.9 MiB
Mar 24 14:46:02.728  WARN network: Try to ban a disconnected peer: ed25519:6DSjZ8mvsRZDvFqFxo8tCKePG96omXW7eVYVSySmDk8e
Mar 24 14:46:09.259  INFO stats: #       0 Downloading headers 0% -/4  3/1/40 peers ⬇ 0.5kiB/s ⬆ 0.2kiB/s 0.00 bps 0 gas/s CPU: 2%, Mem: 25.9 MiB
Mar 24 14:46:12.736 ERROR near_network::peer_manager: Failed sending message: Mailbox has closed
Mar 24 14:46:19.262  INFO stats: #       0 Downloading headers 0% -/4  2/1/40 peers ⬇ 16 B/s ⬆ 28 B/s 0.00 bps 0 gas/s CPU: 2%, Mem: 25.3 MiB
Mar 24 14:46:22.737  WARN network: Try to ban a disconnected peer: ed25519:7PGseFbWxvYVgZ89K1uTJKYoKetWs7BJtbyXDzfbAcqX
Mar 24 14:46:29.264  INFO stats: #       0 Downloading headers 0% -/4  2/1/40 peers ⬇ 16 B/s ⬆ 28 B/s 0.00 bps 0 gas/s CPU: 2%, Mem: 25.3 MiB
Mar 24 14:46:32.748 ERROR near_network::peer_manager: Failed sending message: Mailbox has closed
```

Note, my GCloud node runs fine at the same time, so it's definitely some issue with degraded network. But it reproduced very well - both inside and outside of the docker.

### PR DESCRIPTION
**Pull request by ilblackdragon**
Also:
 - make header sync parameters read from config (and some that were already from config but were not used).
 - increase default timeout for stalling in header sync to 120s.
 - don't report error about failing to send message when peer is not active any more as it's expected that message doesn't go.

Fix #2305

Test Plan
---------
Run nodes on slow network and see that it doesn't get banned.
With lower header sync limit, observe that it doesn't try to re-request from banned peer.

### CODE REVIEW

File: chain/client/src/sync.rs [hunk 1]
```diff
@@ -182,12 +182,16 @@ impl HeaderSync {
...
-                                    info!(target: "sync", "Sync: ban a fraudulent peer: {}, claimed height: {}, score: {}",
+                                    info!(target: "sync", "Sync: ban a fraudulent peer: {}, claimed height: {}, score: {}", 
                                         peer.peer_info, peer.chain_info.height, peer.chain_info.score);
                                     self.network_adapter.do_send(NetworkRequests::BanPeer {
                                         peer_id: peer.peer_info.id.clone(),
                                         ban_reason: ReasonForBan::HeightFraud,
                                     });
+                                    // This peer is fraudulent, let's skip this beat and wait for
+                                    // the next one when this peer is not in the list anymore.
+                                    self.syncing_peer = None;
```
Comment (bowenwang1996) [inline chain/client/src/sync.rs]: I don't think this is the best way to handle it. While it is true that you may request from the same peer again, it is also possible that you choose a different peer to request from. Maybe it is better to remember this peer and filter it when choosing peers to request from.

File: near/src/config.rs [hunk 2]
```diff
@@ -405,7 +405,7 @@ impl NearConfig {
                 sync_height_threshold: 1,
                 header_sync_initial_timeout: Duration::from_secs(10),
                 header_sync_progress_timeout: Duration::from_secs(2),
-                header_sync_stall_ban_timeout: Duration::from_secs(40),
+                header_sync_stall_ban_timeout: Duration::from_secs(120),
```
Comment (bowenwang1996) [inline near/src/config.rs]: This means a peer can potentially grieve you for more than two minutes (notice that for the ban to trigger it usually requires entering the loop three times). Not sure whether that is acceptable.

Comment (ilblackdragon) [reply near/src/config.rs]: Any period of time can grieve by sending rarely information. We can push this into config and allow people to configure this based on their settings.

**Comment by ilblackdragon** [comment]
@mfornet added a check before reporting error now that peer is still active - as it's expected that we can't send to disconnected peer and it's possible that peer got disconnected between check and sending message.

**Comment by ilblackdragon** [comment]
@mfornet This https://github.com/nearprotocol/nearcore/pull/2324/files#diff-af738dd74b1b3cdbf2abd8c1104326c0R615 addresses the surface of the issue that we can show errors for something that is expected (e.g. sending a message to peer who just got disconnected while we are sending a message).

File: chain/client/src/sync.rs [hunk 3]
```diff
@@ -182,12 +182,16 @@ impl HeaderSync {
...
+                                    return false;
```
Comment (SkidanovAlex) [inline chain/client/src/sync.rs]: It is not really clear what you are doing here.
The boolean here means whether the header sync is due. Returning `false` in the conditions in which it might be due is either a bug or a hack, no?

My understanding of what you attempt to achieve is return false now, so that header sync is not triggered. I presume that you expect that it will still trigger during the next sync beat, at which point you expect that the peer is removed.

I think it is not an acceptable solution for two reasons:
1. There's no guarantee that the peer is removed by the next sync, so you are not solving the problem to begin with? You are just noticeably decreasing the chance of it.
2. It violates the contract of the method. So if we are sticking with this solution, it needs to be documented all the way (here, in the method comment, at the call site, and in the spec).

I would suggest to instead check if our *current* peer is banned, at the beginning of `HeaderSync::run` or `HeaderSync::header_sync_due`, and set it to `None` if it is

Comment (SkidanovAlex) [reply chain/client/src/sync.rs]: Actually, turns out I misunderstood what `header_sync_due` return value means. The change is not as hacky as I thought. Comments would still be good :) But seems like we don't really violate the contract of the method with this change, so no actionable item here.

Comment (ilblackdragon) [reply chain/client/src/sync.rs]: I do agree that it actually doesn't remove banned peer - but there is no actual way to know that some peer didn't get banned by any other part of the system. That's why I'm also disabled showing actual error as it's not an error.

Here we for sure know we will try to send it to the peer who is fraudulent (because he has the highest height) - hence skipping this beat.
