### PR TITLE
fix(bridge): add receiver_id to ExecutionOutcome

### LINKED ISSUE #2902: ExecutionOutcome should include the address of the account/contract that produced it
Currently, execution outcome only contains the receipt id that produced it. In case of the bridge, it makes it unusable, since contract on Ethereum cannot verify that certain amount of tokens was burnt by the specific fungible contract on Near. The situation is even more difficult, since receipts are merkelized in a different block from their outcomes. Execution outcome should include the id of the account/contract that emitted it, similarly to how it is done on Ethereum.

### PR DESCRIPTION
**Pull request by bowenwang1996**
Add `receiver_id` to `ExecutionOutcome` so that the bridge can verify cross contract calls easily. Fixes #2902.

### CODE REVIEW

File: runtime/runtime/src/lib.rs [hunk 1]
```diff
@@ -660,6 +661,7 @@ impl Runtime {
                 receipt_ids,
                 gas_burnt: result.gas_burnt,
                 tokens_burnt,
+                receiver_id: account_id.clone(),
```
Comment (nearmax) [inline runtime/runtime/src/lib.rs:664]: @evgenykuzyakov Could you confirm that since currently we disallow multiple delete actions in the receipt, `account_id == account.account_id`, correct?

Comment (evgenykuzyakov) [reply runtime/runtime/src/lib.rs:664]: This doesn't belong here. You already have `receipt_id`

File: core/primitives/src/views.rs [hunk 2]
```diff
@@ -805,6 +805,8 @@ pub struct ExecutionOutcomeView {
     /// the prepaid gas price might be lower than the actual gas price and it creates a deficit.
     #[serde(with = "u128_dec_format")]
     pub tokens_burnt: Balance,
+    /// Receiver id of the transaction or receipt.
+    pub receiver_id: String,
```
Comment (evgenykuzyakov) [inline core/primitives/src/views.rs:809]:
```suggestion
    pub receiver_id: AccountId,
```

File: runtime/runtime/src/lib.rs (hunk 1 above)
Comment (evgenykuzyakov) [reply runtime/runtime/src/lib.rs:664]: Ok. I read the attached issue and it seems reasonable, but not required. Basically, we want to include duplicated information from `Receipt` to the `ExecutionOutcome` to be able to easier process this on Eth side.

Even though it's a waste of storage, it's still helpful because it allows to identify the shard on which the execution outcome was produced. Eventually we'll need to know the block height to identify the shard, but it's fine until we have dynamic resharding.

File: runtime/runtime/src/lib.rs [hunk 3]
```diff
@@ -260,6 +260,7 @@ impl Runtime {
                         receipt_ids: vec![receipt.receipt_id],
                         gas_burnt: verification_result.gas_burnt,
                         tokens_burnt: verification_result.burnt_amount,
+                        receiver_id: transaction.receiver_id.clone(),
```
Comment (evgenykuzyakov) [inline runtime/runtime/src/lib.rs:263]: This is not right. This should be the account on which the execution happened. In this case the `signer_id`

File: core/primitives/src/transaction.rs [hunk 4]
```diff
@@ -235,9 +235,22 @@ struct PartialExecutionOutcome {
     pub gas_burnt: Gas,
     #[serde(with = "u128_dec_format")]
     pub tokens_burnt: Balance,
+    pub receiver_id: AccountId,
```
Comment (evgenykuzyakov) [inline core/primitives/src/transaction.rs:238]: This one
