### PR TITLE
Check for invalid shard id

### LINKED ISSUE #1948: Nearcore crashes on `chunk` RPC call requesting a shard id that does not exist
```
$ http post http://127.0.0.1:3030/ jsonrpc=2.0 id=dontcare method=chunk 'params:=[[1, 10000]]'
```

### PR DESCRIPTION
**Pull request by bowenwang1996**
When we receive some requests that contain shard id we should first check its validity before using it to index into an array. Fixes #1948

### CODE REVIEW

File: chain/jsonrpc/tests/rpc_query.rs [hunk 1]
```diff
@@ -115,6 +115,27 @@ fn test_chunk_by_hash() {
...
+#[test]
+fn test_chunk_invalid_shard_id() {
+    init_test_logger();
+
+    System::run(|| {
+        let (_view_client_addr, addr) = start_all(true);
+
+        let mut client = new_client(&format!("http://{}", addr.clone()));
+        actix::spawn(client.chunk(ChunkId::BlockShardId(BlockId::Height(0), 100)).then(|res| {
+            if res.is_err() {
```
Comment (SkidanovAlex) [inline chain/jsonrpc/tests/rpc_query.rs]: Test for a specific error. There could be many reasons the request fails.
