### PR TITLE
fix(state viewer): fix state dump inconsistency

### LINKED ISSUE #2435: Inconsistent genesis after network reset
**Describe the bug**
After betanet reset, my account which was previously validator still has locked amount but is not a validator.

**To Reproduce**
1. Stake 100,000 N
2. Get network reset via betanet release process
3. Observe locked amount on the non-validating account:

E.g. 
```
near state illia
Account illia
{
  amount: '109999999898346855000000000',
  locked: '161748960602985038993033587691',
  code_hash: '11111111111111111111111111111111',
  storage_usage: 510,
  storage_paid_at: 0,
  block_height: 2109542,
  block_hash: 'BJcXpqf2zvL98XE1r2gqKH66qxcjtHr3uJt8UqGoRBZt',
  formattedAmount: '109.999999898346855'
}
```

**Expected behavior**
Locked amount should be reset to 0 on network reset if we are reseting `validators` et.

Also we should have a hard failure on inconsistent genesis at the launch between `validators` and `locked` amounts.

**Version (please complete the following information):**
Live betanet

### PR DESCRIPTION
**Pull request by bowenwang1996**
Currently state dump can cause inconsistency between validators in genesis and the state records. This PR fixes the issue by enforcing the following rules:
1) Validators in the new genesis after the state dump are validators from the epoch during which state dump happens.
2) For those that stake and change their stake during the last epoch, the change to state is reset. For example, if someone stakes during the last epoch, their stake will be returned back to balance and locked amount becomes 0.

Resolves #2435.

Test plan
--------
* `test_dump_state_preserve_validators` that tests we preserve the validators from last epoch.
* `test_dump_state_return_locked` that tests we return locked balance for nonvalidators.

### CODE REVIEW

File: test-utils/state-viewer/src/state_dump.rs [hunk 1]
```diff
@@ -0,0 +1,201 @@
...
+
+    let mut records = vec![];
+    for state_root in &state_roots {
+        let trie = TrieIterator::new(&runtime.trie, &state_root).unwrap();
+        for item in trie {
+            let (key, value) = item.unwrap();
+            if let Some(mut sr) = StateRecord::from_raw_key_value(key, value) {
+                if let StateRecord::Account { account_id, account } = &mut sr {
+                    if account.locked > 0 {
+                        if let Some((_, stake)) = validators.get(account_id) {
```
Comment (ilblackdragon) [inline test-utils/state-viewer/src/state_dump.rs:43]: can be just `let stake = get(account_id).or_else(&0)`, because `amount = amount + locked - stake` works in both cases.

File: test-utils/state-viewer/src/state_dump.rs [hunk 2]
```diff
@@ -0,0 +1,201 @@
...
+    use near_store::test_utils::create_test_store;
+    use near_store::Store;
+    use neard::config::GenesisExt;
+    use neard::config::TESTING_INIT_STAKE;
+    use neard::genesis_validate::validate_genesis;
+    use neard::NightshadeRuntime;
+    use std::collections::HashSet;
+    use std::iter::FromIterator;
+    use std::path::Path;
+    use std::sync::Arc;
```
Comment (ilblackdragon) [inline test-utils/state-viewer/src/state_dump.rs:84]: ... I know you guys hate grouping the imports with optimize imports, but crate, then internal deps then stds just looks weird ...

File: test-utils/state-viewer/src/state_dump.rs [hunk 3]
```diff
@@ -0,0 +1,201 @@
...
+            .runtime_adapter
+            .get_epoch_block_producers_ordered(&cur_epoch_id, &last_block_hash)
+            .unwrap();
+        assert_eq!(
+            block_producers.into_iter().map(|(r, _)| r.account_id).collect::<HashSet<_>>(),
+            HashSet::from_iter(vec!["test0".to_string(), "test1".to_string()])
+        );
+        let last_block = env.clients[0].chain.get_block(&head.last_block_hash).unwrap().clone();
+        let mut state_roots = vec![];
+        for chunk in last_block.chunks.iter() {
```
Comment (ilblackdragon) [inline test-utils/state-viewer/src/state_dump.rs:139]: `let state_roots = last_block.chunks.iter().map(|chunk| chunk.inner.prev_state_root.clone()).collect()` ?

also given you are already passing last_block.header and we need state roots so need chunks anyway, can pass block itself and extract roots there instead of doing it on every call?

File: test-utils/state-viewer/src/state_dump.rs [hunk 4]
```diff
@@ -0,0 +1,201 @@
...
+            state_roots.push(chunk.inner.prev_state_root.clone());
+        }
+        let runtime = NightshadeRuntime::new(
```
Comment (ilblackdragon) [inline test-utils/state-viewer/src/state_dump.rs:142]: doesn't `env` has runtime inside?

File: test-utils/state-viewer/src/main.rs [hunk 5]
```diff
@@ -230,26 +236,12 @@ fn main() {
             }
         }
         ("dump_state", Some(_args)) => {
-            let (runtime, state_roots, height) = load_trie(store.clone(), home_dir, &near_config);
+            let (runtime, state_roots, header) = load_trie(store.clone(), home_dir, &near_config);
```
Comment (ilblackdragon) [inline test-utils/state-viewer/src/main.rs:239]: separately from this (and doesn't matter right now), but for multiple shards - this can be done only when all shards are tracked (or we need to figure out how to piece from multiple files of genesis per shard). 

Let's add a test though when not all shards are present (and check with human error if that's not true).

File: test-utils/state-viewer/src/state_dump.rs [hunk 6]
```diff
@@ -0,0 +1,201 @@
...
+use neard::NightshadeRuntime;
+use std::collections::HashMap;
+
+pub fn state_dump(
+    runtime: NightshadeRuntime,
+    state_roots: Vec<StateRoot>,
+    last_block_header: BlockHeader,
+    genesis_config: &GenesisConfig,
+) -> Genesis {
+    println!("Generating genesis from state data");
```
Comment (ilblackdragon) [inline test-utils/state-viewer/src/state_dump.rs:16]: `"Generating genesis from state data of #{} / {}", last_block_header.inner_lite.height`

File: test-utils/state-viewer/src/main.rs [hunk 7]
```diff
@@ -37,7 +40,7 @@ fn load_trie(
     for chunk in last_block.chunks.iter() {
         state_roots.push(chunk.inner.prev_state_root.clone());
     }
-    (runtime, state_roots, last_block.header.inner_lite.height)
```
Comment (ilblackdragon) [inline test-utils/state-viewer/src/main.rs:40]: above `let last_block = ..` should it actually be getting last _final_ block?

Comment (bowenwang1996) [reply test-utils/state-viewer/src/main.rs:40]: I plan to do that in a separate PR as it will change how state dump works: it needs to take one argument as the "expected height" and we will dump state from the first final block with height >= expected height. This way we can guarantee that the state dump result is consistent on every node.

File: test-utils/state-viewer/src/state_dump.rs (hunk 3 above)
Comment (bowenwang1996) [reply test-utils/state-viewer/src/state_dump.rs:139]: This is in tests. In main we first computed state roots in `load_trie` so there is no reason to recompute them.

File: test-utils/state-viewer/src/state_dump.rs (hunk 4 above)
Comment (bowenwang1996) [reply test-utils/state-viewer/src/state_dump.rs:142]: Client has `Arc<RuntimeAdapter>` from which it is annoying to get `NightShadeRuntime` out.

File: test-utils/state-viewer/src/state_dump.rs (hunk 6 above)
Comment (bowenwang1996) [reply test-utils/state-viewer/src/state_dump.rs:16]: what is the second argument?

Comment (ilblackdragon) [reply test-utils/state-viewer/src/state_dump.rs:17]: `block_hash`

File: test-utils/state-viewer/src/main.rs (hunk 7 above)
Comment (ilblackdragon) [reply test-utils/state-viewer/src/main.rs:40]: +1
