### PR TITLE
fix: prevent million-proposal attack by introducing minimum stake req…

### LINKED ISSUE #2610: Excessive copying of ValidatorStake in epoch manager
Currently, every time epoch manager processes block X it produces `BlockInfo` and copies all proposals from `BlockInfo` for block X-1 into `BlockInfo` for block X. It creates an accumulation of cloned proposals with each new block processing, until the end of the epoch. In other words, the proposal submitted in the first block of the epoch will be cloned for each block in that epoch. See the cloning code here: https://github.com/nearprotocol/nearcore/blob/master/chain/epoch_manager/src/lib.rs#L431

This creates a security vulnerability. If someone submits staking transactions from different accounts with 1000 transactions per block, it will take 227 blocks until the total number of cloned memory exceeds 4GiB, since a single `ValidatorStake` can take up to 112 bytes. Since our current cache allows 1000 blocks this attack becomes feasible, see: https://github.com/nearprotocol/nearcore/blob/7c75fe5bc2eb44ae08a3445116157ac8fa77f2ac/chain/epoch_manager/src/lib.rs#L31

### Reducing cache size

We could try reducing the cache size, but even if we had not cache at all, the node would break simply from cloning huge amounts of memory, on each new block. Specifically, after 5 hours (assuming we process 1 block per second) we would be copying 1.8GiB per block. Just having two consecutive `BlockInfo`s would take almost 4GiB of memory.

### Increasing the cost of staking transaction

If we assume that it is safe to copy 100MiB of proposals on each block processing, and epoch consists of 3600*12 blocks, we should raise the fees to prohibit more than 22 staking transactions per block. This number seems to be very low.

## The proposed solution

I suggest to redesign epoch manager to avoid cloning of the `ValidatorStake` altogether.

### PR DESCRIPTION
**Pull request by bowenwang1996**
…uirements

Fixes #2610 in two parts:

1. Introduce a `minimum_stake_divisor` to have a lower limit for staking transactions. If someone tries to stake with less than `last_seat_price / minimum_stake_divisor`, the transaction will fail.

2. Instead of copying the proposals in every block info, use an aggregator that always updates the proposal information to the last final block and at the end of an epoch, process the rest between last final block and last block of the epoch.

Test plan
---------
* Unit tests in epoch manager to make sure that the change in how we store aggregated information doesn't break anything.
* Tests in `neard/src/runtime` to make sure that the proposals that are now invalid are properly rejected.

### CODE REVIEW

File: runtime/runtime/src/lib.rs [hunk 1]
```diff
@@ -128,7 +128,7 @@ pub struct ActionResult {
     pub result: Result<ReturnData, ActionError>,
     pub logs: Vec<LogEntry>,
     pub new_receipts: Vec<Receipt>,
-    pub validator_proposals: Vec<ValidatorStake>,
+    pub validator_proposals: BTreeMap<AccountId, ValidatorStake>,
```
Comment (evgenykuzyakov) [inline runtime/runtime/src/lib.rs:131]: In theory we don't need sorted map, but something like a linked_hash_map, which Rust doesn't really have :)

File: core/chain-configs/src/genesis_config.rs [hunk 2]
```diff
@@ -99,6 +103,10 @@ pub struct GenesisConfig {
     /// Fishermen stake threshold.
     #[serde(with = "u128_dec_format")]
     pub fishermen_threshold: Balance,
+    /// The minimum stake required for staking is last seat price divided by this number.
+    #[serde(default = "default_minimum_stake_divisor")]
+    #[default(10)]
+    pub minimum_stake_divisor: u64,
```
Comment (frol) [inline core/chain-configs/src/genesis_config.rs:109]: How about using Rational instead of encoding the `1/divisor` implicitly?

Comment (bowenwang1996) [reply core/chain-configs/src/genesis_config.rs:109]: I don't think that's needed (at least for now) because the stake is usually a large number (due to yotcoNEAR) and for example there would very little difference if we divide by 33 or multiple by 3/100.

File: runtime/runtime/src/lib.rs (hunk 1 above)
Comment (bowenwang1996) [reply runtime/runtime/src/lib.rs:131]: yep :)

Comment (evgenykuzyakov) [reply runtime/runtime/src/lib.rs:131]: The issue with `BTreeMap` is we're changing the spec by reordering proposals based on lexicographical order of AccountID, which is not great. Ideally, we shouldn't change it. Better to keep it as Vec, but dedup with hashmap at the end.

Comment (bowenwang1996) [reply runtime/runtime/src/lib.rs:131]: > by reordering proposals based on lexicographical order of AccountID, which is not great

Why does it matter?

Comment (evgenykuzyakov) [reply runtime/runtime/src/lib.rs:131]: Because it was not required before, but now it'll have to be enforced.

Comment (bowenwang1996) [reply runtime/runtime/src/lib.rs:131]: Okay

File: chain/epoch_manager/src/lib.rs [hunk 3]
```diff
@@ -397,35 +402,46 @@ impl EpochManager {
...
-                    block_info.all_proposals = all_proposals;
                 }
 
                 // Save current block info.
                 self.save_block_info(&mut store_update, current_hash, block_info.clone())?;
+                let last_block_hash = match self.get_block_info(&block_info.last_final_block_hash) {
+                    Ok(final_block_info) => {
+                        if final_block_info.epoch_id != block_info.epoch_id {
+                            if is_epoch_start {
+                                Some(current_hash)
```
Comment (SkidanovAlex) [inline chain/epoch_manager/src/lib.rs:419]: Let me understand this logic:

1. We need that for all the future calls to the `get_and_update_epoch_info_aggregator` the cached block corresponds to one of the blocks in the ancestry of the `last_block`
2. Thus, it is safe to update the cached block up to the last final block.
3. If there's an epoch switch, and the current block is the first block in the epoch, it is safe to pass the block that is not final, because on the epoch switch `get_and_update_epoch_info_aggregator` will always recreate the aggregator, so even if there's a fork, we won't try to reuse the cache.

I see some problems with it:

1. A final block can be reverted. We should handle such a case gracefully. Seems like right now the aggregator  in case of a fork will merge all the proposals and tracking data from both forks (it will start with the data from the old fork, and will be merging backwards until it sees the last hash, or until the epoch start, but because it will never see the last hash, it will just merge in all the proposals)
2. The fork of a non-final block at the epoch start actually will result in an incorrect behavior. Consider

```

B <- A
  <-    A'
```

B is the last block of the prev epoch, A and A' are the first blocks of the new epoch. A is recognized first, and because `is_epoch_start` here is true, the cache is updated to be all the way up to `A`.
When A' arrives, here we again see `is_epoch_start`, and again set the `last_block_hash = current_hash`, and attempt to update the aggregator. The aggregator however will not consider it as `is_epoch_start`, because from the aggregator's perspective the last cached block and the new block are in the same epoch, so it will just merge their proposals and trackers, again resulting in a wrong stats.

File: chain/epoch_manager/src/lib.rs [hunk 4]
```diff
@@ -1050,12 +1075,75 @@ impl EpochManager {
...
+            let prev_hash = self.get_block_info(&cur_hash)?.prev_hash;
+            let prev_height = self.get_block_info(&prev_hash)?.height;
+            let block_info = self.get_block_info(&cur_hash)?;
+            if &block_info.epoch_id != epoch_id || block_info.prev_hash == CryptoHash::default() {
+                break;
+            }
+            aggregator.update_trackers(&block_info, &epoch_info, prev_height);
+
+            for proposal in block_info.proposals.iter() {
+                proposals.entry(proposal.account_id.clone()).or_insert_with(|| proposal.clone());
```
Comment (SkidanovAlex) [inline chain/epoch_manager/src/lib.rs:1121]: Can the same block contain multiple proposals for the same account? If yes, you probably want to do `rev()` on the iterator above so that the latter of the two is kept.

File: chain/epoch_manager/src/lib.rs (hunk 3 above)
Comment (bowenwang1996) [reply chain/epoch_manager/src/lib.rs:424]: Fixed

File: chain/epoch_manager/src/lib.rs (hunk 4 above)
Comment (bowenwang1996) [reply chain/epoch_manager/src/lib.rs]: No. My change in runtime ensures that for every account, it can have at most one proposal in every chunk (and therefore every block).

File: chain/epoch_manager/src/lib.rs [hunk 5]
```diff
@@ -1105,25 +1113,25 @@ impl EpochManager {
...
         let mut cur_hash = *last_block_hash;
+        let mut overwrite = false;
         while cur_hash != aggregator.last_block_hash || epoch_change {
             // Avoid cloning
             let prev_hash = self.get_block_info(&cur_hash)?.prev_hash;
             let prev_height = self.get_block_info(&prev_hash)?.height;
             let block_info = self.get_block_info(&cur_hash)?;
             if &block_info.epoch_id != epoch_id || block_info.prev_hash == CryptoHash::default() {
+                // This means that we reached the previous epoch and still hasn't seen
+                // `aggregator.last_block_hash` and therefore implies that a fork has happened.
```
Comment (SkidanovAlex) [inline chain/epoch_manager/src/lib.rs:1126]: It doesn't necessarily imply that the fork has happened. If `epoch_start = true`, we are expected to get to this branch even if there was no forks.
