### PR TITLE
fix: Don't drop messages. RouteBack cache update

### LINKED ISSUE #2756: Message loss when network rebalances
In #2490, we introduced network balancing to avoid reaching maximum number of peers. However, it comes at a cost -- when a message is being routed, it can get dropped due to the connection between two nodes on the route getting dropped when they rebalance the network connection. It makes the system slower overall. In some cases, the requester will re-request or request from other peers (for example for partial encoded chunks). In other cases, the message is simply dropped. This can have some fairly undesirable consequences such as block producers not getting enough approvals to produce their blocks. It seems that this also allows an attacker to initiate an eclipse attack on a node that can have some profound impact on the overall network topology.
It is not clear to me, however, how to best solve this issue. Some ideas:
* When we send a message, allow the sender to specify how many times they want to send it and send the messages through different routes.
* When we rebalance network connections, we should minimize the decrease in the number of reachable peers.
* When we send or route a message, instead of using round robin on the shortest paths, we do something like round robin on the peers with most routes to the destination, or the peer with most connection to the destination among the shortest paths, or a combination of the two.

### PR DESCRIPTION
**Pull request by mfornet**
Increased route back cache to avoid dropping messages which
are supposed to be routed back. The problem was that when some
nodes are syncing several chunk request are asked, and request
arrive faster than responses, effectively invalidating the cache
most of the  responses are dropped, since the route back hash was
dropped from the cache.

This PR also introduce cache strategy proposed [here](https://github.com/nearprotocol/nearcore/issues/2756#issuecomment-642961782)

Fix #2756 

Test plan
=========
- Reproduced scenario where several routed messages were dropped locally, and tested with new cache and with old cache. The fix was the size increase.
- Unit tests to check the new strategy is working properly.

### CODE REVIEW

File: chain/network/src/cache.rs [hunk 1]
```diff
@@ -0,0 +1,396 @@
...
+    }
+
+    fn remove_frequent(&mut self) {
+        let (mut size, target) = self.size_per_target.iter().next().cloned().unwrap();
+
+        if let btree_map::Entry::Occupied(mut entry) = self.record_per_target.entry(target.clone())
+        {
+            {
+                let records = entry.get_mut();
+                let first = records.iter().next().cloned().unwrap();
```
Comment (bowenwang1996) [inline chain/network/src/cache.rs:71]: Am I correct that you are using `BTreeSet` as a heap? If so, why bother with the negative number trick and not use `BinaryHeap` instead?

File: chain/network/src/cache.rs [hunk 2]
```diff
@@ -0,0 +1,396 @@
...
+                records.remove(&first);
+                self.main.remove(&first.1);
+            }
+
+            if entry.get().is_empty() {
+                entry.remove();
+            }
+        } else {
+            unreachable!();
```
Comment (bowenwang1996) [inline chain/network/src/cache.rs:80]: Let's not panic unnecessarily.

File: chain/network/src/cache.rs (hunk 1 above)
Comment (mfornet) [reply chain/network/src/cache.rs:71]: Not exactly, because I need to insert/remove arbitrary elements from the collection.

File: chain/network/src/cache.rs [hunk 3]
```diff
@@ -0,0 +1,398 @@
...
+    capacity: u64,
+    /// Maximum time allowed before removing a record from the cache.
+    evict_timeout: u64,
+    /// Main map from message hash to time where it was created + target peer
+    /// Size: O(capacity)
+    main: HashMap<CryptoHash, (Time, PeerId)>,
+    /// Number of records allocated by each PeerId.
+    /// The size is stored with negative sign, to order in PeerId in decreasing order.
+    /// Size: O(number of active connections)
+    size_per_target: BTreeSet<(Size, PeerId)>,
```
Comment (bowenwang1996) [inline chain/network/src/cache.rs:56]: Since size is bounded by `capacity`, why not insert `capacity - size` instead so that we completely avoid negative numbers?

File: chain/network/src/cache.rs [hunk 4]
```diff
@@ -0,0 +1,398 @@
...
+    record_per_target: BTreeMap<PeerId, BTreeSet<(Time, CryptoHash)>>,
+}
+
+impl RouteBackCache {
+    fn is_full(&self) -> bool {
+        self.capacity == self.main.len() as u64
+    }
+
+    fn remove_frequent(&mut self) {
+        let (mut size, target) = self.size_per_target.iter().next().cloned().unwrap();
```
[the remark this answers is not in the document]
Comment (mfornet) [reply chain/network/src/cache.rs:69]: no, this function is only called when the cache is full so it should have at least one element. There is an assertion that cache capacity should be a positive number.

File: chain/network/src/cache.rs [hunk 5]
```diff
@@ -0,0 +1,398 @@
...
+            self.size_per_target.insert((size, target));
+        }
+    }
+
+    fn remove_evicted(&mut self) {
+        if self.is_full() {
+            let now = Utc::now().timestamp_millis() as Time;
+            let remove_until = now.saturating_sub(self.evict_timeout);
+
+            let mut new_size_per_target = BTreeSet::new();
```
[the remark this answers is not in the document]
Comment (mfornet) [reply chain/network/src/cache.rs:99]: Yes I got confused, for some reason thought that since I was holding a mutable reference from an object contained in self, I couldn't mutate another field in self, but it is allowed which makes sense.

**Comment by SkidanovAlex** [comment]
With this implementation once we got to `is_full`, we will likely on each insert trigger the folloiwng:

1. Check if `is_full`, it is, so do `remove_evicted`, which is `O(num_peers)`. In most cases there will be nothing to evict.
2. Call to `remove_frequent`, and actually remove one entry, and is also rather expensive (multiple accesses to a `BTreeMap`).
3. Insert.

It will be happening on each insert, so makes the cache pretty expensive compared to a regular cache that does one insert into a hashtable and one linked list insertion.

One simple-ish approach is to change `remove_frequent` to remove several (like 100) entries from the most offending peer. With a cache size of 1M and 40 peers we expect more than 25K messages from the offending peer, so removing 100 isn't much different from removing 1, it's still a tiny percentage of all the messages, but it removes the necessity to call to `remove_evicted` for 100 iterations, and also makes cost per removal in `remove_frequent` slightly lower, since iterating over the first 100 elements is cheaper than pulling the first 100 times.

With that, I would also always call `remove_frequent` from `remove_evicted`, for the reasons similar to above (`remove_frequent` is cheaper than `remove_evicted`, so doesn't add much to the cost, but makes it more predictable that the expensive evictions won't be happening more than once every 100 inserts)

File: chain/network/src/cache.rs [hunk 6]
```diff
@@ -0,0 +1,443 @@
...
+                }
+            }
+
+            if entry.get().is_empty() {
+                entry.remove();
+            }
+        }
+
+        self.size_per_target.remove(&(size, target.clone()));
+        // Since size has negative sign, adding 1, is equivalent to subtracting 1 from the size.
```
Comment (bowenwang1996) [inline chain/network/src/cache.rs:106]: this comment is no longer correct?
