### PR TITLE
fix(test): test nearlib key path

### LINKED ISSUE #2580: Re-enable create-near-app tests on CI
See https://github.com/nearprotocol/nearcore/pull/2579 for context.

`create-near-app` tests fail with:

```
 Failed to load master account key from /var/lib/buildkite-agent/.near/validator_key.json: Error: 
ENOENT: no such file or directory, open '/var/lib/buildkite-agent/.near/validator_key.json'
```

### PR DESCRIPTION
**Pull request by ailisp**
This Fix #2580, and also eliminate warnings appears in near-api-js about validator_key.json

Test Plan
---------
test_nearlib.sh should work both locally and on CI

### CODE REVIEW

**Comment by vgrichina** [comment]
@ailisp is error you are getting related to https://discordapp.com/channels/490367152054992913/557983089704566787/725088894466523258 ?

**Comment by ailisp** [comment]
I think yes 👍

**Comment by ailisp** [comment]
@vgrichina pass after Bowen's fix. ptal

File: scripts/test_nearlib.sh [hunk 1]
```diff
@@ -16,19 +16,23 @@ git clone https://github.com/near/create-near-app.git
 # Make sure to use local nearcore for tests
 export NODE_ENV=local
 
+SRC_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null 2>&1 && pwd )"
```
Comment (vgrichina) [inline scripts/test_nearlib.sh:19]: @ailisp hard to grasp what this is trying to do. Why not just `SRC_DIR=$(pwd)/../`?

File: scripts/test_nearlib.sh [hunk 2]
```diff
@@ -16,19 +16,23 @@ git clone https://github.com/near/create-near-app.git
...
+export HOME=$SRC_DIR/../testdir
```
Comment (vgrichina) [inline scripts/test_nearlib.sh:20]: it's a bit concerning we have to override `HOME`. Why? Shouldn't it be possible to pass NEAR home dir explicitly to  start_unittest.py (same as you can specify it explicitly with nearup)?

File: scripts/test_nearlib.sh [hunk 3]
```diff
@@ -16,19 +16,23 @@ git clone https://github.com/near/create-near-app.git
...
+
+# Run create-near-app tests
```
Comment (vgrichina) [inline scripts/test_nearlib.sh:22]: Why move these to run before near-api-js tests? near-api-js more likely to fail fast.

File: scripts/test_nearlib.sh (hunk 1 above)
Comment (ailisp) [reply scripts/test_nearlib.sh:19]: BASH_SOURCE[0] would work in any director, `$(pwd)/../` wouldn't if current dir is not at `scripts/`

File: scripts/test_nearlib.sh (hunk 2 above)
Comment (ailisp) [reply scripts/test_nearlib.sh:20]: both create-near-app and near-api-js (when NODE_ENV is local) assume validator_key.json is at `process.env.HOME/.near/validator_key.json` so this has to be overrided. It's fine to override home even when run locally, because it only in the sub-shell, won't affect HOME after script exit

File: scripts/test_nearlib.sh (hunk 3 above)
Comment (ailisp) [reply scripts/test_nearlib.sh:22]: Before Bowen's fix near-api-js was failed and exit, but wanted to test create-near-app on ci. I can move it back now

File: scripts/test_nearlib.sh (hunk 2 above)
Comment (ailisp) [reply scripts/test_nearlib.sh:20]: Maybe should fix in near-api-js and create-near-app side:
https://github.com/near/near-api-js/blob/master/test/config.js#L38
https://github.com/near/create-near-app/blob/master/blank_react_project/src/config.js#L44

But i think it's okay to override $HOME as it's only used in nearcore integration test, not worthy to not hard code in near-api-js/create-near-app

File: scripts/test_nearlib.sh (hunk 1 above)
Comment (vgrichina) [reply scripts/test_nearlib.sh:19]: @ailisp I see, then it can be `SRC_DIR="$(pwd)/$(dirname "${BASH_SOURCE[0]}")"`?

File: scripts/test_nearlib.sh (hunk 2 above)
Comment (vgrichina) [reply scripts/test_nearlib.sh:20]: @ailisp what is default path when I run local nearcore instance? Is it `process.env.HOME/.near/validator_key.json`? Or did it change? I think it did change for `nearup`, right?

Comment (ailisp) [reply scripts/test_nearlib.sh:20]: Yes nearup change it to be `HOME/.near/localnet/validator_key.json`, however the test here isn't using, maybe i should replace it using nearup localnet.

File: scripts/test_nearlib.sh (hunk 1 above)
Comment (ailisp) [reply scripts/test_nearlib.sh:19]: That looks clever! in some case it would leave `.` or `..` on trailling, but should be fine, i can always postfix it with a "/" and `ls workspace/./` or `ls workspace//` both works 👍 
```
workspace bo$ chmod +x a.sh 
workspace bo$ ./a.sh 
/Users/bo/workspace/.
workspace bo$ cd ..
$ workspace/a.sh 
/Users/bo/workspace
$ cd workspace/near-ops
near-ops bo$ ../a.sh 
/Users/bo/workspace/near-ops/..
```

File: scripts/test_nearlib.sh (hunk 2 above)
Comment (vgrichina) [reply scripts/test_nearlib.sh:20]: Created separate issue to track local dev env fixes:
https://github.com/near/devx/issues/221

File: scripts/test_nearlib.sh [hunk 4]
```diff
@@ -24,11 +27,12 @@ yarn build
...
-# yarn && yarn test
-
 # Run create-near-app tests
-# cd ../create-near-app
-# yarn && yarn test
+cd ../create-near-app
+yarn 
+yarn test
 
+# Run near-shell tests
```
Comment (vgrichina) [inline scripts/test_nearlib.sh:35]: @ailisp do you plan to enable these in follow up PR?

Comment (ailisp) [reply scripts/test_nearlib.sh:35]: This still fails of missing masterAccount param, will fix later
