### PR TITLE
fix: generate validator key when chain-id is mainnet

### LINKED ISSUE #3286: validator key generation is not supported in neard when chain_id is mainnet
When `chain_id` is `mainnet`, neard does not generate validator key even if we pass in `--accout-id`,

### PR DESCRIPTION
**Pull request by bowenwang1996**
Fixes #3286.

Test plan
---------
Test locally that when `chain-id` is `mainnet` and we pass an account id to neard, validator key is indeed generated.

### CODE REVIEW

File: neard/src/config.rs [hunk 1]
```diff
@@ -694,6 +694,17 @@ fn state_records_account_with_key(
     ]
 }
 
+/// Generate validator key if account is not `None`.
```
Comment (frol) [inline neard/src/config.rs:697]: This condition looks odd to me. I suggest the method takes AccountId and Option is handled outside of the method.

BTW, having an empty-string AccountId looks error-prone to me. Can we have it resolved to None immediately on receiving an empty string instead of having it in an invalid state?

File: neard/src/config.rs [hunk 2]
```diff
@@ -694,6 +694,13 @@ fn state_records_account_with_key(
...
```
Comment (frol) [inline neard/src/config.rs:697]:
```suggestion
/// Generate a validator key and save it to the file path.
```

File: neard/src/config.rs [hunk 3]
```diff
@@ -694,6 +694,13 @@ fn state_records_account_with_key(
...
+fn generate_validator_key(account_id: &str, path: &Path) {
+    let signer = InMemoryValidatorSigner::from_random(account_id.to_string(), KeyType::ED25519);
+    info!(target: "near", "Use key {} for {} to stake.", signer.public_key(), account_id);
+    signer.write_to_file(path);
```
Comment (frol) [inline neard/src/config.rs:701]: I suggest we either unwrap/expect, log a warning on error, or return the error since it is not uncommon to see various permission errors or out-of-disk states and it would be quite surprising to keep things going without the key.

**Review by frol — APPROVED** [review]

File: neard/src/config.rs (hunk 3 above)
Comment (bowenwang1996) [reply neard/src/config.rs:701]: This function doesn't return any error. The function would panic if writing to file failed. See `KeyFile::write_to_file`

Comment (frol) [reply neard/src/config.rs:701]: I see. LGTM
