### PR TITLE
fix: persist chunk tail

### LINKED ISSUE #2806: Garbage collection is unacceptably slow
When the node garbage collects data, it invokes `clear_data`, which deletes old block and chunk data. However, in practice we have observed extraordinary slowness in this function. Under current setup, at every call to `clear_data`, we garbage collect 100 heights worth of data and it takes 30-60s to execute after the network has been running for a while, which is absolutely devastating and unacceptable. I suspect that this has something to do with rocksdb compaction and deletion of data might have triggered compaction, which can take a while to run, depending on the size of the data. To address this issue, we should
* in the short term find temporary solution (better than #2807) that minimizes the time spent on garbage collection.
* After the temporary fix, we should develop comprehensive benchmarks to test and fine-tune rocksdb options, as well as our garbage collection parameters, or find some other ways to fully fix this issue.

### PR DESCRIPTION
**Pull request by bowenwang1996**
Garbage collection is slow because we do not persist chunk tail and therefore `clear_chunk_data` iterates from 0 to min_chunk_height every time it is called. Fixes #2806.

### CODE REVIEW

File: chain/chain/src/store.rs [hunk 1]
```diff
@@ -2249,6 +2249,11 @@ impl<'a> ChainStoreUpdate<'a> {
                 .set_ser(ColBlockMisc, LARGEST_TARGET_HEIGHT_KEY, &t)
                 .map_err::<Error, _>(|e| e.into())?;
         }
+        if let Some(chunk_tail) = self.chunk_tail {
```
Comment (Kouprin) [inline chain/chain/src/store.rs:2252]: if let Some(chunk_tail) = self.chunk_tail.take() {
            store_update.set_ser(ColBlockMisc, TAIL_KEY, &chunk_tail)?
        }

**Comment by bowenwang1996** [comment]
@Kouprin sure

File: chain/chain/src/store.rs [hunk 2]
```diff
@@ -2244,11 +2244,16 @@ impl<'a> ChainStoreUpdate<'a> {
...
-        if let Some(t) = self.largest_target_height {
+        if let Some(t) = self.largest_target_height.take() {
             store_update
                 .set_ser(ColBlockMisc, LARGEST_TARGET_HEIGHT_KEY, &t)
                 .map_err::<Error, _>(|e| e.into())?;
         }
+        if let Some(chunk_tail) = self.chunk_tail.take() {
+            store_update
+                .set_ser(ColBlockMisc, CHUNK_TAIL_KEY, &chunk_tail)
+                .map_err::<Error, _>(|e| e.into())?;
```
Comment (Kouprin) [inline chain/chain/src/store.rs:2255]: My previous comment was about getting rid of `map_err::<Error, _>(|e| e.into())` :)
